### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by Noemata** [mellinoe/veldrid#1]
I'm getting the following build errors (among several others, but I think these are the most relevant):

1>veldrid\src\Veldrid\Platform\OpenTKWindowBase.cs(75,27,75,34): error CS0012: The type 'CancelEventArgs' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ComponentModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>veldrid\src\Veldrid\Platform\OpenTKWindowBase.cs(75,13,75,53): error CS0123: No overload for 'OnWindowClosing' matches delegate 'EventHandler<CancelEventArgs>'
1>veldrid\src\Veldrid\Octree.cs(403,44,403,47): error CS1061: 'OctreeNode<T>[]' does not contain a definition for 'Sum' and no extension method 'Sum' accepting a first argument of type 'OctreeNode<T>[]' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Octree.cs(436,24,436,27): error CS1061: 'List<OctreeItem<T>>' does not contain a definition for 'Any' and no extension method 'Any' accepting a first argument of type 'List<OctreeItem<T>>' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Octree.cs(441,29,441,32): error CS1061: 'OctreeNode<T>[]' does not contain a definition for 'Any' and no extension method 'Any' accepting a first argument of type 'OctreeNode<T>[]' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Graphics\MtlParser.cs(268,39,268,51): error CS1061: 'IEnumerable<MaterialDefinition>' does not contain a definition for 'ToDictionary' and no extension method 'ToDictionary' accepting a first argument of type 'IEnumerable<MaterialDefinition>' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Graphics\Direct3D\D3DMaterial.cs(225,38,225,41): error CS1061: 'MaterialVertexInput[]' does not contain a definition for 'Sum' and no extension method 'Sum' accepting a first argument of type 'MaterialVertexInput[]' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Graphics\ObjParser.cs(524,29,524,35): error CS1061: 'VertexPositionNormalTexture[]' does not contain a definition for 'Select' and no extension method 'Select' accepting a first argument of type 'VertexPositionNormalTexture[]' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Graphics\OctreeVisibilityManager.cs(72,61,72,69): error CS1061: 'IEnumerable<string>' does not contain a definition for 'Contains' and no extension method 'Contains' accepting a first argument of type 'IEnumerable<string>' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Graphics\SimpleMeshDataProvider.cs(71,29,71,35): error CS1061: 'VertexPositionNormalTexture[]' does not contain a definition for 'Select' and no extension method 'Select' accepting a first argument of type 'VertexPositionNormalTexture[]' could be found (are you missing a using directive or an assembly reference?)
1>veldrid\src\Veldrid\Graphics\OpenGL\OpenGLMaterial.cs(142,33,142,39): error CS1061: 'MaterialVertexInput[]' does not contain a definition for 'Select' and no extension method 'Select' accepting a first argument of type 'MaterialVertexInput[]' could be found (are you missing a using directive or an assembly reference?)

**Comment by mellinoe** [comment]
Hey @Noemata, the build instructions are a little more involved than regular projects, let me try to outline them here:

* Have Visual Studio 2015 Update 3 installed
* Have latest NuGet extension installed (Tools -> Extensions and Updates -> Updates)
* Uncheck these options under Tools ->NuGet Package Manager -> Package Manager Settings:
![image](https://cloud.githubusercontent.com/assets/8918977/20651200/7cba5744-b495-11e6-812c-d9cb4d51b0af.png)
* Have .NET Core SDK installed: https://go.microsoft.com/fwlink/?LinkID=835014
* After cloning the repository, run `dotnet restore <cloned-path>`.

Now you should be able to build the project from Visual Studio or from the command line. If you open it in Visual Studio, make sure to change the active solution configuration to "Windows_Debug" and "x64".

**Comment by mellinoe** [comment]
The above instructions should work; let me know if you end up trying it out.
