### ISSUE TITLE
Using Veldrid for 2d graphics?

### ISSUE THREAD

**Issue by carrierdown** [mellinoe/veldrid#10]
I'm wondering about the viability of using veldrid for 2d UI's? 

I'm looking for a cross-platform UI solution to use for a project. I want it to be lightweight and do not really need any stock UI controls as my use case is quite specialized anyway. As I'm using .NET Core 2 this library seems to be a great fit, but I'm wondering if you have any pointers on how one could approach creating a simple 2d-renderer. I would typically need to draw vector graphics like solid filled rectangles, lines and text. 

Keep up the great work, veldrid looks like an awesome library!

**Comment by mellinoe** [comment]
Hey @carrierdown , thanks for the interest in Veldrid!

Veldrid can certainly be used for creating 2D graphics, or UI's. However, this is a very low-level library, so doing this will be akin to doing 2D rendering with OpenGL or DirectX. You will need to create the appropriate shaders, prepare your UI data on the CPU, and manage those interactions yourselves This is obviously very doable (and is what many UI toolkits do), but it will be more difficult than using a higher-level 2D drawing library with built-in functionality for drawing lines, shapes, boxes, text, etc. It has the potential to be significantly faster than a general-purpose 2D library, though.

The RenderDemo project draws several 2D pieces, notably [the UI](https://github.com/mellinoe/ImGui.NET), and things like the shadow map preview. These use simple quads and shapes generated on the CPU.

**Comment by amerkoleci** [comment]
I would suggest some integration with direct2d on windows platform and SkiaSharp on non windows if you require gpu vector rendering, otherwise as Erik said you can use ortho matrix for 2d rendering and setup all shader + gpu data and perform draw calls on device.

**Comment by carrierdown** [comment]
Thanks for your suggestions, I'll have a look at ImGui. SkiaSharp is also a possibility, I'll look into that as well.
