### ISSUE TITLE
Please support normal to net framework 4.5 and 4.6 or 4.7

### ISSUE THREAD

**Issue by sourceskyboxer** [mellinoe/veldrid#101]
Hello dear Eric, 

please give me chance! I want use Net Framework version with Veldrid because I am only using Net Framework. I don't like net corefx because I feel unknow to net corefx. Please release for netfx ( not only corefx )

**Comment by mellinoe** [comment]
Veldrid is a .NET Standard 2.0 library, so it already supports .NET Framework.

**Comment by sourceskyboxer** [comment]
Oh really? 
> so it already supports .NET Framework.

I will check your source. Thanks!
