### ISSUE TITLE
Problem with SDL2.dll

### ISSUE THREAD

**Issue by sourceskyboxer** [mellinoe/veldrid#102]
Hello Eric, sorry I disturb that.

![image](https://user-images.githubusercontent.com/3496136/42871804-829d3088-8a7b-11e8-9624-8ef14a7217f7.png)

I already installed from Nuget but it shows nothing Veldrid-SDL2-Nativer.

What do I miss that or what do I wrong?

**Comment by mellinoe** [comment]
This is the same as https://github.com/mellinoe/veldrid/issues/19. Long story short, you need to use PackageReferences instead of the old packages.config to reference the Veldrid nuget packages. There are options in the Visual Studio UI somewhere to switch.

**Comment by mellinoe** [comment]
If you want to use a different SDL2 binary, then it needs to be in the same folder as the rest of your application. No guarantees that any random version of SDL2 will work, though -- Veldrid.SDL2 is only tested with the bundled native binaries on Windows.

**Comment by sourceskyboxer** [comment]
Yeah I know how do I make with "working directory" like this:

`Environment.CurrentDirectory = Path.Combine("x64");`
It is like working directory for native dlls. Does it support same to other operating system? Like Linux and macOS?

**Comment by mellinoe** [comment]
Sorry, I'm not sure I understand what you're asking. The library loader doesn't really care what the current working directory is, so changing `Environment.CurrentDirectory` probably won't help. If you put SDL2.dll next to your application .dll, then the loader should be able to find it. On Linux/macOS, the library can also be anywhere on the dynamic load path (LD_LIBRARY_PATH).

**Comment by sourceskyboxer** [comment]
Oh I am sorry for my bad English.

Yes it is correct for LD_LIBRARY_PATH - I know almost.

But my question with Mono MakeBundle ( mkbundle.exe )
I don't like to happen if net assembly exe into native executable and forgets to requierement of installation with net framework. mkbundle can generates as single executable with embedded mscorlib.dll from Mono's assemblies

I understand that. It is hard for net standard 2.0 :/ 

```
mkbundle --static --deps --keeptemp ConsoleApp1.exe -L "C:\Program Files\Mono\lib\mono\4.5" -L "C:\Program Files\Mono\lib\mono\4.7.1-api" -o "TestConsole.exe" -v -L "C:\Program Files (x86)\Xamarin\Workbooks\WorkbookApps\DotNetCore"
OS is: Windows
Sources: 1 Auto-dependencies: True
Attempting to load assembly: ConsoleApp1.exe
Assembly ConsoleApp1.exe loaded successfully.
Attempting to load assembly from: .\I18N.West.dll
Attempting to load assembly from: C:\Program Files\Mono\lib\mono\4.5\I18N.West.dll
Attempting to load assembly from: .\I18N.dll
Attempting to load assembly from: C:\Program Files\Mono\lib\mono\4.5\I18N.dll
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: C:\Program Files\Mono\lib\mono\4.5\mscorlib
Attempting to load assembly from: .\Veldrid
Attempting to load assembly from: .\netstandard
Attempting to load assembly from: C:\Program Files\Mono\lib\mono\4.5\netstandard
Attempting to load assembly from: C:\Program Files\Mono\lib\mono\4.7.1-api\netstandard
Attempting to load assembly from: C:\Program Files (x86)\Xamarin\Workbooks\WorkbookApps\DotNetCore\netstandard
........
```
netstandard.dll requieres Dotnet 2.x 

That is sadly - I can't bundle as single executable :( Thanks for testing with Veldrid-Engine

**Comment by mellinoe** [comment]
I'm going to assume this one is solved and the remaining issues are specific to mono's mkbundle, which I'm not familiar with. If you're not able to solve it, I'd try asking the mono folks if there are any known issues or workarounds needed.
