### ISSUE TITLE
Wrong opengl calling convention on *nix platforms and Mac OS

### ISSUE THREAD

**Issue by hjred** [mellinoe/veldrid#106]
Hello Eric,

I've seen that you recently changed the calling convention in the opengl binding from cdecl to stdcall.
The problem is neither is the correct one. It depends on the system the code is running on.

On *nix systems and on mac the calling convention has to be cdecl and only on windows the calling convention has to be stdcall.

The problem with attributes in this case is, that the expression has to be a constant expression. That leads to the duplication of all function pointers. One set for windows with the stdcall convention and the other set for the rest with cdecl convention.

I've read some hints, that the winapi calling convention would default to stdcall on windows and cdecl on *nix, but can't verify this exactly for Mono and Net Core.

Removing the unmanaged function pointer attribute would also be an option, as delegates are by default marshalled as such and none of the other options are used.

**Comment by mellinoe** [comment]
From reading around, it sounds like both Mono and .NET Core should respect cdecl as the default convention on 32-bit Linux. If that gets us the behavior we want, then we can switch to it. I don't currently have a 32-bit Linux device to test it on, though.

**Comment by mellinoe** [comment]
I've switched the convention and tested it to the best of my abilities. This change will be in 4.4.0.
