### ISSUE TITLE
Support vertex attribute offsets

### ISSUE THREAD

**Issue by tangmi** [mellinoe/veldrid#107]
If I have a vertex buffer with non-interleaved data, e.g.

```c#
var triangle = new float[] {
    // positions
    0, 0, 0,
    1, 0, 0,
    0, 1, 0,

    // normals
    0, 0, 1,
    0, 0, 1,
    0, 0, 1,
};
```

I'd like to reuse the same buffer with different vertex attribute pointers for `position` and `normal`.
- In OpenGL, I can use [`glVertexAttribPointer`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml) with the `pointer` paramter to specify the offset of the first element of a given attribute.
- In DirectX, I can rebind the same buffer to multiple indices and use the `pOffsets` parameter of [`ID3D11DeviceContext::IASetVertexBuffers`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-iasetvertexbuffers).
- Vulkan has `offset` on [`VkVertexInputAttributeDescription`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkVertexInputAttributeDescription.html)
- Metal has `offsets` on [`[MTLRenderCommandEncoder setvertexbuffers]`](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/2928165-setvertexbuffers)

Is this possible in Veldrid? One can set the `VertexLayoutDescription`s on the `ShaderSetDescription`, but it seems that it assumes that we start reading from the start of each buffer for vertex data.

The context here is that I'm trying to read in a GLTF 2.0 model. [This box](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF/Box.gltf) has one `bufferView` (i.e. `DeviceBuffer`?) for two non-interleaved `accessor`s (i.e. vertex attribute pointer?), like the array above. I'm not sure how to express that with a `VertexLayoutDescription`.

Please let me know if I'm just crazy and there's a better way to do this! Thanks for your time!

**Comment by tangmi** [comment]
I believe that would cover my use case.

It may be worth noting that there seems to be two different models APIs take to achieve an attribute offset:
- there's the OpenGL/Vulkan way that adds the offset to the vertex attribute
- and the DirectX/Metal way that doesn't expose offsets on the attributes, but allows the buffers to be rebound with different offsets.

I'm not entirely sure which is a better abstraction, but (without any real evidence) it seems to me that what OpenGL and Vulkan are doing is closer to what GPUs want under the hood (i.e. an initial pointer to some spot in memory, how much to read, a stride, and how often to bump the pointer). It's also what GLTF seems to prefer (for whatever value that has--although I'm very sure its vertex attribute format is very biased towards `glVertexAttribPointer`).

**Comment by mellinoe** [comment]
I've implemented this on the [vertex-layout-offset branch](https://github.com/mellinoe/veldrid/tree/vertex-layout-offset). I need to do more testing of it, but it should go into 4.4.0.

**Comment by tangmi** [comment]
Wow. I'm blown away, thanks for the incredibly fast response and work!

I took a quick look at the branch and think it looks great. Do you think it's worth having the `VertexElementDescription.Offset` be `uint?` and documentation on when it's "tightly-packed"?

Also what is the intended behavior when a `VertexLayoutDescription` has `VertexElementDescription`s that are mixed in whether or not the `Offset` is specified? I can think of a few possibilities:
1. An "all or nothing" approach where it is only valid to have the vertex layout be fully implicit or explicit (with guards against the below two specifications?).
2. A "mixed" set where we lay out the implicit with or without the explicit items and then place the explicit items where they are specified
3. A "mixed" set where the vertex layout is constructed implicitly until an explicit item, which is laid out, then the following implicit items' offsets carry on from there

It looks like the branch currently implements 2. where the the implicit layout is created and the explicit items are moved to where they want to be (relevant line of code, I believe, for [GL](https://github.com/mellinoe/veldrid/blob/8180b63c5aad720cefe247e2bae87538d17dbe7f/src/Veldrid/OpenGL/OpenGLCommandExecutor.cs#L300), [DX](https://github.com/mellinoe/veldrid/blob/8180b63c5aad720cefe247e2bae87538d17dbe7f/src/Veldrid/D3D11/D3D11ResourceCache.cs#L170), [Vk](https://github.com/mellinoe/veldrid/blob/8180b63c5aad720cefe247e2bae87538d17dbe7f/src/Veldrid/Vk/VkPipeline.cs#L166), [Mtl](https://github.com/mellinoe/veldrid/blob/8180b63c5aad720cefe247e2bae87538d17dbe7f/src/Veldrid/MTL/MTLPipeline.cs#L112)).

Thanks again for your time and efforts on this!

**Comment by mellinoe** [comment]
Yeah, there needs to be some validation logic that checks all of the Offset values are valid and agree with each other. I think that option 1 is the best, personally.

**Comment by tangmi** [comment]
I agree. I think it's the easiest to document and validation could probably be done eagerly on `VertexLayoutDescription` creation.

**Comment by mellinoe** [comment]
I added some relevant validation and tests, and have merged this into master now. It will be in 4.4.0.
