### ISSUE TITLE
Having trouble using two texture samplers in a fragment shader (OpenGL)

### ISSUE THREAD

**Issue by AlzPatz** [mellinoe/veldrid#108]
Hi, 

I've been scratching my head a bit. It's getting late so I thought on the off chance this was an easy oversight I thought I'd post up here.

I would appreciate it if anyone has thoughts on the below? 

I wonder if this has anything to do with the fact openGl doesn't split out the concept of a sampler and a texture.

So, I'm using two texturesamplers in a fragment shader (opengl). doing some simple multi-texturing.

Despite being careful to ensure they have different texture resource sets, both samplers are sampling the same texture.

Bit of code..

In fragment shader I'm using something like:

```
uniform sampler2D texSampler0;
uniform sampler2D texSampler1;
```

(there is a matrix uniform in the vertex shader, so the above are resource sets 1 and 2 respectively (not from 0))

Resource Layouts are set up like:

 ```
ResourceLayout layout0 = _resourceFactory.CreateResourceLayout(
                new ResourceLayoutDescription(
                    new ResourceLayoutElementDescription("texture0", ResourceKind.TextureReadOnly, ShaderStages.Fragment),
                    new ResourceLayoutElementDescription("texSampler0", ResourceKind.Sampler, ShaderStages.Fragment)
                )
            );

            ResourceLayout layout1 = _resourceFactory.CreateResourceLayout(
                new ResourceLayoutDescription(
                    new ResourceLayoutElementDescription("texture1", ResourceKind.TextureReadOnly, ShaderStages.Fragment),
                    new ResourceLayoutElementDescription("texSampler1", ResourceKind.Sampler, ShaderStages.Fragment)
                )
            );
```

then resource sets are made

 ```
set0 = _resourceFactory.CreateResourceSet(new ResourceSetDescription(
                layout0,
                textureViews0,
                _graphicsDevice.Aniso4xSampler));

set1 = _resourceFactory.CreateResourceSet(new ResourceSetDescription(
                layout1,
                textureViews1,
                _graphicsDevice.Aniso4xSampler));
```

in the graphics pipeline description i add all 3 resouce layouts (incl matrix)

```
...
new[] { matrixlayout, layout0, layout1 },
...
```

Finally in command list set up i go:

```
_commandList.SetGraphicsResourceSet(0, matrixset); 
_commandList.SetGraphicsResourceSet(1, set0);
_commandList.SetGraphicsResourceSet(2, set1);
```

and everything works, except i always sampler texture 0 from both samplers

If this behaviour seems odd I can post a demo, I made a quick and dirty one to try and replicate the issue, which it did.

Thanks 

Alex

**Comment by mellinoe** [comment]
The only mistake I see is that you have the wrong names for the `ResourceKind.TextureReadOnly` elements in your layout descriptions. Those names should match the names of the sampler2D variables in your shaders. In the OpenGL backend, the name of `ResourceKind.TextureReadOnly` elements doesn't actually matter -- they just apply to the previous TextureReadOnly in the list.

Does changing that fix the issue?

**Comment by AlzPatz** [comment]
Jackpot - fixed - I knew it smelt like a Sampler/Texture vs. OpenGl abstraction thing.

Thanks so much - I wasted an hour or two :)

Note to self: Name the Texture Resources the Same as the Samplers for OpenGL 

:) :) :) :)

**Comment by mellinoe** [comment]
Glad to help! Sorry that you were stuck on this. I am going to improve the documentation around this (https://mellinoe.github.io/veldrid-docs/articles/shaders.html) so that it's more clear how things work. It doesn't explicitly mention that the TextureReadOnly element should match with the name of the sampler2D variable.

Let me know if you hit any other snags.

**Comment by AlzPatz** [comment]
Thank you again. I really should have been able to figure this out, knowing from your existing docs that these samplers and textures were not separate objects and that the last bound persists, I should have tried swapping the order in the layouts, harmonising or switching the names. Doh. But a tweak in the docs if you have the time may help another :)

**Comment by mellinoe** [comment]
I added this to the docs:

> NOTE: GLSL sampler2D variables are matched to a resource with ResourceKind.TextureReadOnly. The name of the element with ResourceKind.TextureReadOnly must match the name of the sampler2D variable exactly. When specifying an element with ResourceKind.Sampler, the name of the element is irrelevant and unused -- the sampler in that slot will apply to the closest previous element(s) with ResourceKind.TextureReadOnly.
