### ISSUE TITLE
NuGet package has a broken dependency

### ISSUE THREAD

**Issue by orthoxerox** [mellinoe/veldrid#11]
Hi.

Veldrid depends on a missing package `System.Text.Primitives (>= 0.1.0-e170627-2)`.

**Comment by mellinoe** [comment]
Hey @orthoxerox , sorry about that. The package is actually available from this myget feed: https://dotnet.myget.org/gallery/dotnet-corefxlab.

It is a bit inconvenient, but that functionality should be moving into nuget.org at some point, so it won't always be on a third-party feed.
