### ISSUE TITLE
Race condition in D3D11ResourceCache

### ISSUE THREAD

**Issue by MillerJames** [mellinoe/veldrid#110]
The overview on multi-threading states that methods on ResourceFactory can be invoked from any thread at any time. But, D3D11ResourceCache can throw if multiple threads create Pipeline objects which have similar state. For example, if multiple threads request the same uncached InputLayout, they might call `_inputLayouts.Add` multiple times with the same key.

```C#
internal InputLayout GetInputLayout(VertexLayoutDescription[] vertexLayouts, byte[] vsBytecode)
{
    InputLayoutCacheKey tempKey = InputLayoutCacheKey.CreateTempKey(vertexLayouts);
    if (!_inputLayouts.TryGetValue(tempKey, out InputLayout inputLayout))
    {
        inputLayout = CreateNewInputLayout(vertexLayouts, vsBytecode);
        InputLayoutCacheKey permanentKey = InputLayoutCacheKey.CreatePermanentKey(vertexLayouts);
        _inputLayouts.Add(permanentKey, inputLayout);
    }

    return inputLayout;
}
```

**Comment by mellinoe** [comment]
Good catch, there is definitely some additional synchronization required here. I'll follow up with a fix shortly.

**Comment by mellinoe** [comment]
This should be fixed by https://github.com/mellinoe/veldrid/commit/1d32be2b64f869c454b3b9071aafc4cf79d8b4d6.

**Comment by tangmi** [comment]
Just curious (trying to capitalize on your .NET knowledge), is there a major difference in this case between using `lock` on all cache accesses vs `ConcurrentDictionary` for the relevant caches?

**Comment by MillerJames** [comment]
Thanks for the fast fix!

**Comment by mellinoe** [comment]
@tangmi The main reason I didn't use ConcurrentDictionary is that there isn't a simple way to "get or add" a disposable resource. ConcurrentDictionary.GetOrAdd doesn't guarantee that the "creation delegate" you give it will be called only once per key. The D3D11 objects I'm caching are disposable, so they can't just be "thrown away" if they aren't added to the dictionary.
