### ISSUE TITLE
MTLTextureDescriptor sampleCount (2) is not supported by device.

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#114]
Running NeoDemo on a mac with the default backend (metal).
When switching MSAA to x2, demo crashes with:

```
-[MTLTextureDescriptorInternal validateWithDevice:]:842: failed assertion `MTLTextureDescriptor sampleCount (2) is not supported by device.'
```

All other MSAA options work.

**Comment by mellinoe** [comment]
Ah, I think I see the problem:

https://developer.apple.com/documentation/metal/mtldevice/1433355-supportstexturesamplecount

1 and 4 are supported by all devices, but 2 is not supported by some macOS devices. I had assumed that support for 4 implied support for 2, but that's not the case. I'll need to add some extra logic here to track that information, but it shouldn't be too difficult.

**Comment by mellinoe** [comment]
This should be fixed on master now, please let me know if you're able to try with your device.

**Comment by mellinoe** [comment]
I'm going to assume this one was fixed by https://github.com/mellinoe/veldrid/commit/8c1a90a0c9e8be580ada4bd788aa039cba1c42a8. Please re-open if that's not the case.
