### ISSUE TITLE
[Memory leak] OpenGL graphics device retains strong reference to disposed command lists

### ISSUE THREAD

**Issue by SamVanheer** [mellinoe/veldrid#118]
The OpenGL graphics device retains strong references to disposed command lists.
The `_submittedCommandListCounts` dictionary is keyed to OpenGLCommandList, and keys are not removed when the command list is disposed.

This results in memory leaks. When using `ImageSharpTexture` a considerable number of temporary command lists can be created when uploading many textures, resulting in runaway memory allocations that eventually cause an `OutOfMemoryException`.

The graphics device methods `EnqueueDisposal` and `CheckCommandListDisposal` need to be updated to remove the command list from the dictionary.

**Comment by mellinoe** [comment]
I made a couple of changes:

* OpenGLGraphicsDevice.DecrementCount now removes the CommandList if it's reference count reaches 0.
* ImageSharpTexture doesn't use CommandLists / staging Textures anymore. The way it was implemented required a call to GraphicsDevice.WaitForIdle, or resources would not be destroyed even with the first fix above.

**Comment by SamVanheer** [comment]
I checked the heap snapshot after loading a map, there is now only one command list loaded. Textures look good, so ImageSharpTexture is working as expected as well.

Thanks for the quick response.

**Comment by mellinoe** [comment]
Sure thing, thanks again for the bug report.
