### ISSUE TITLE
Build failing on Ubuntu 18.04.1 via WLS

### ISSUE THREAD

**Issue by christopher-landress** [mellinoe/veldrid#119]
I'm using WSL on Windows 10 with Ubuntu 18.04. Getting an odd compilation error. OpenGL is installed correctly and I am able to run OpenGL apps over X11 remoting via VcXsrv.

-------------------------------------------------------------------------------------------------------------------

/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library '/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at MSBuildExtensionTask.ContextAwareTask.CustomAssemblyLoader.LoadUnmanagedDll(String unmanagedDllName) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    --- End of inner exception stack trace --- [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.OpenGitRepo(String repoRoot) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library '/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at MSBuildExtensionTask.ContextAwareTask.CustomAssemblyLoader.LoadUnmanagedDll(String unmanagedDllName) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    --- End of inner exception stack trace --- [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.OpenGitRepo(String repoRoot) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [/home/clandress/veldrid/src/Veldrid.SDL2/Veldrid.SDL2.csproj]
MSBUILD : error MSB4166: Child node "6" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library '/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at MSBuildExtensionTask.ContextAwareTask.CustomAssemblyLoader.LoadUnmanagedDll(String unmanagedDllName) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor() [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    --- End of inner exception stack trace --- [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.OpenGitRepo(String repoRoot) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot) [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [/home/clandress/veldrid/src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj]

Build FAILED.

/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]

/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoUnhandled Exception:undException: Unable to load shared library '/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the L D_DEBUG environment variable: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library '/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/MSBuildFull/lib/linux/x86_64/libgit2-1196807.so)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
   at MSBuildExtensionTask.ContextAwareTask.CustomAssemblyLoader.LoadUnmanagedDll(String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.RemoveHandle()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject.Finalize()/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/
Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) [/home/clandress/veldrid/src/Veldrid.OpenGLBindings/Veldrid.OpenGLBindings.csproj]
/home/clandress/.nuget/packages/nerdbank.gitversioning/2.1.23/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at MSBuildExtensionTask.ContextAwareTask.CustomAssemblyLoader.LoadUnmanagedDll(String unmanagedDllName) [/home/clandress/veldrid/src

**Comment by mellinoe** [comment]
You are likely missing some dependency of [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning), like libcurl -- not sure of the exact apt package to install. That said, I can't really guarantee that everything is going to work on WSL -- to be honest I doubt it. You can likely build the library, but I've certainly not tested the graphics library integration there at all. If GitVersioning does not work, it's also possible to just turn it off by removing this line: https://github.com/mellinoe/veldrid/blob/master/Directory.Build.props#L36

**Comment by tzachshabtay** [comment]
I got the same issue on a different application (not using veldrid) which uses Nerdbank.GitVersioning, on ubuntu 18.04 (not WSL).
I think it's this bug: https://github.com/libgit2/libgit2sharp/issues/1585

**Comment by DylanFPS** [comment]
This fixes this issue.
```
apt-get install libc6 libcurl3
```

**Comment by jsutlovic** [comment]
Sorry to re-open this issue, but I'm not able to build on Ubuntu 18.04. Since `libcurl4` is default, a number of applications will be removed if installed (including `curl` itself):``

```
The following packages will be REMOVED:
  cmake cmake-curses-gui curl feh lastpass-cli libcurl4
```

It looks like the same issue is happening over at dotnet/roslyn#29289 and they seem to have a fix (with a newer build of LibGit2Sharp). Upgrading `Microsoft.SourceLink.GitHub` to `1.0.0-beta2-18618-05` and `NerdbankGitVersioningVersion` to `2.3.38` is allowing me to build (albeit with warnings).

**Comment by mellinoe** [comment]
> Upgrading Microsoft.SourceLink.GitHub to 1.0.0-beta2-18618-05 and NerdbankGitVersioningVersion to 2.3.38 is allowing me to build (albeit with warnings).

Good to know. I will make that change tonight or this weekend. What are the warnings you see?

**Comment by mellinoe** [comment]
That’s strange. Are you building from a valid git repository, or did you download a zip and build that? Ideally either would work, but it’s possible the latter gives warnings. It’s also possible there are some bugs in the newer versions of those dependencies

**Comment by jsutlovic** [comment]
I was running from a cloned version of this repo, but just to be sure I re-cloned and found the issue. With **just** `NerdbankGitVersioningVersion` upgraded to `2.3.38` it builds with no warnings. Looks like updating `Microsoft.SourceLink.GitHub` causes the issues, so might be best to leave that one as-is.

**Comment by jsutlovic** [comment]
Correct. Should I create a pull request for this and reference the issue?

**Comment by mellinoe** [comment]
@jsutlovic Sure, that would be much appreciated.
