### ISSUE TITLE
GLTF2 loader

### ISSUE THREAD

**Issue by amerkoleci** [mellinoe/veldrid#12]
I think as gltf2 growing as standard model/scene format would be good to have support for it

**Comment by amerkoleci** [comment]
There is also a fbx to gltf converter, https://github.com/facebookincubator/FBX2glTF

**Comment by mellinoe** [comment]
Yeah, I would like to support this, and it shouldn't be terribly hard given that it's a JSON-based format. It probably makes sense to split out individual formats into a separate utility library (libraries?).

**Comment by mellinoe** [comment]
This seems to be relevant: https://github.com/KhronosGroup/glTF-CSharp-Loader

**Comment by amerkoleci** [comment]
Just note here dude, i just update the assimp .net version to 4.1.0 on windows as it supports GLTF.
https://github.com/amerkoleci/assimp-net, https://github.com/assimp/assimp/releases/tag/v4.1.0

**Comment by mellinoe** [comment]
@amerkoleci Cool! I remember trying to do that, but I couldn't get it to load GLTF files even when building from source. I kept getting an error of some sort -- can't recall anymore.

I would probably be happier getting assimp working easily with Veldrid than I would be doing something GLTF-specific. I'm using assimp in my projects personally.

**Comment by mellinoe** [comment]
I'm not planning on doing anything directly with GLTF2 for the forseeable future. Projects like assimp can load such formats and work well with Veldrid already, and anything more specific would probably be built outside of this repository.

**Comment by gleblebedev** [comment]
I'm working towards Veldrid-based GLTF viewer. I have some progress:
https://gyazo.com/81b59aa949681832bea8954837d142ab

@amerkoleci would you help me with the project? :)

**Comment by amerkoleci** [comment]
@gleblebedev that looks cool, actually I'm working on my C++ game engine during my spare time (https://github.com/amerkoleci/alimer)
