### ISSUE TITLE
VertexElementSemantic.Position

### ISSUE THREAD

**Issue by pzgulyas** [mellinoe/veldrid#121]
When I try to use `VertexElementSemantic.Position` in my first attempts, I always get a SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

I can reproduce this error in NeoDemo as well, by modifying the line 57 of file Objects\SkyBox.cs, where you use `VertexElementSemantic.TextureCoordinate` semantic originally for uploading the position. Actually I don't see NeoDemo using `VertexElementSemantic.Position` anywhere. Is there a particular reason for that? (Should I keep away from that too?)

I'm not very experienced in graphics programming, so probably I'm just overlooking something.

**Comment by mellinoe** [comment]
These semantics depend on what is authored in your HLSL code. The actual names themselves ("Position", "Normal") do not have any formal meaning or functional implications. They are just identifiers that allow Veldrid to match up the vertex element in code with the vertex element in your shader.

The part that is not obvious (and which needs to be documented better), is that Veldrid.SPIRV always generates `TEXCOORD` semantics when translating to HLSL. This is why NeoDemo uses `VertexElementSemantic.TextureCoordinate` for all of its vertex data.

If you write HLSL yourself and provide Veldrid with HLSL text (in the D3D11 backend only), then you can use other semantic strings. Again, there's no functional difference between them.

**Comment by pzgulyas** [comment]
Thank you, this makes sense. You were right, I got this error using Veldrid.SPIRV on D3D11 backend, not with pure HLSL.

**Comment by mellinoe** [comment]
@pzgulyas Glad to help. I am making a note to myself to document this part of Veldrid.SPIRV better, since it's a common point of confusion.

**Comment by borup3** [comment]
I propose having the information here included at the relevant parts in both NeoDemo and VertexElementSemantic as inline documentation, having spent a while looking through the Veldrid and NeoDemo source code for clues as to why NeoDemo would work when my code wouldn't.

The cause was that I _presumed_ correct usage of VertexElementSemantic. I would have expected implementation details like this to be on the enum itself.

**Comment by mellinoe** [comment]
@borup3 I went ahead and added some more notes to the XML docs for the VertexElementSemantic and VertexElementDescription types.
