### ISSUE TITLE
No SDL_Hint in the SDL wrapper

### ISSUE THREAD

**Issue by crazywig** [mellinoe/veldrid#124]
On Windows it would be handy to call this before creating a window 
SDL_SetHint(SDL_HINT_VIDEO_HIGHDPI_DISABLED, "1")
As otherwise it scales the resolution of your window for you. Unfortunately there is no SDL_SetHint in Veldrids wrapper.

**Comment by crazywig** [comment]
An update on this, even calling this SDL_SetHint does not disable the DPI scaling on windows. You either have to set it in a manifest file (which is difficult when dotnet is loading your netcore DLL) or by calling a specific user32.dll function before you create a window.

[DllImport("User32.dll")]
public static extern bool SetProcessDPIAware();

This allows the units given to SDL_CreateWindow to not be scaled.

**Comment by mellinoe** [comment]
In 4.4.0, Sdl2.LoadFunction is now public, so you are free to wrap extra functions that aren't directly exposed from Veldrid.SDL2.

```C#
[UnmanagedFunctionPointer(CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
public delegate bool SDL_SetHint_t(string name, string value);

// At runtime:
SDL_SetHint_tfuncPtr = Sdl2.LoadFunction<SDL_SetHint_t>("SDL_SetHint");
```

I didn't test the above, but it should be correct. That said, I don't see this function couldn't be wrapped directly. I'll put it on the list for next release.

**Comment by crazywig** [comment]
Thanks for the suggestion. Yeah it was easy for me to add it to your code directly and given how much coverage you have of SDL I thought it a little weird it wasn't already in there which is why I mentioned it.
