### ISSUE TITLE
Veldrid.SDL2 should not throw a TypeInitializationException when function pointers can't be loaded

### ISSUE THREAD

**Issue by mellinoe** [mellinoe/veldrid#125]
Currently, all of the functions that Veldrid.SDL2 supports must be available, or `Veldrid.Sdl2.Sdl2Native` will throw an exception during its type initializer. This is fine on Windows and Linux, because the native library is bundled with the nuget package. However, it would be better if these exceptions were deferred until the missing function is actually invoked, a la DllImport.

**Comment by tzachshabtay** [comment]
Why would it be better? Wouldn't you rather get the error sooner rather than later?

**Comment by mellinoe** [comment]
There is some minimum version that should be absolutely required, but there are also functions like `SDL_SetWindowOpacity` which should not cause a TypeInitializationException. If that function isn't present (SDL2 version < 2.0.5), you should only get an exception if you try to use it, but otherwise things should proceed normally.

**Comment by mellinoe** [comment]
This has been implemented; missing functions no longer cause a `TypeInitializationException`.
