### ISSUE TITLE
Adaptive VSync

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#132]
Hi, I've noticed SyncToVerticalBlank is a boolean value, either on or off.
Is there a way to set adaptive vsync?

I'm trying to migrate from OpenTK, which have VSync as an enum (on, off, adaptive) and as a property of the game window: https://github.com/opentk/opentk/blob/e911f0b7698e7bc32fa1c4eab37f9e50f7bd92a3/src/OpenTK/GameWindow.cs#L1004

Thanks.

**Comment by mellinoe** [comment]
Veldrid only exposes a simple "on/off" mode for vsync currently. Generally speaking, all of Veldrid's backends offer more control than that, but it's not clear what kind of abstraction would work best and most portably. "Adaptive Vsync" isn't a standard setting, seems to be specific to OpenGL, and even then potentially only to particular vendors (I'd have to read more to understand fully). As far as I can tell, there's not a direct analog in Vulkan, D3D11, or Metal, but those API's do offer other kinds of "presentation" or "swap" modes.

**Comment by mellinoe** [comment]
Given the above, I don't have any plans to add anything concrete here. If anyone has recommendations for finer-grained control over the vsync settings that can be implemented on all backends, then I am open to suggestions.

**Comment by tzachshabtay** [comment]
Will it be possible to have a per-backend settings then?

**Comment by mellinoe** [comment]
Unless there’s a very strong reason to add something backend- or platform-specific, then I will try to avoid adding it. Veldrid is designed to be as portable as possible, and in this case I only see a small potential benefit to one backend.
