### ISSUE TITLE
Sampling R32Float Format Textures - Likely user error... anyone have experience with this?

### ISSUE THREAD

**Issue by AlzPatz** [mellinoe/veldrid#133]
Hi,

hmmmm

This is 99% likely user error. Sorry. 

It's probably an issue with using sampling a 32 bit value in this version of glsl.

But anyway, i've been experimenting and failing enough that it's time to throw it out there in case anyone has experience with using R32Float textures as render surfaces and then sampling them back. in the <<<1% chance there is something up with veldrid, then hopefully the following useful.

I've experienced a number of visual artifacts using OpenGl backend and sampling a signed 32 bit float texture in a fragment shader. I've distilled the issue down into a simple example. Here an R32 texture is created and rendered too with, split vertically, with +1 on one side, -1 on the other. 

In the main render loop this is sampled by a full screen quad which should display half green and half blue. Instead I get patchy colour and artifacts (green and blue specs on background).

In my other more involved and complex use cases / tests, it actually causes major screen issues, tearing and whole screen artifacts when just sampling this type of texture. it wouldn't be that instructive to show that code at the moment however.  

I know not all GPUs / OpenGL versions can use 32 bit floats, but I've tested this out on a few machines with modern hardware and from what i've read glsl version 330 should be ok...

i'm ready to look foolish

thanks in advance

https://github.com/AlzPatz/VeldridSamplingR32FloatTexture

**Comment by mellinoe** [comment]
Hey @AlzPatz , I think I've identified the problem. When you generate the texture, you are using `BlendStateDescription.SingleAlphaBlend`. If you switch that to `BlendStateDescription.SingleOverrideBlend`, then the R32_Float texture gets generated correctly for me. Here's what I see after I change that:

BlendStateDescription.SingleOverrideBlend
![image](https://user-images.githubusercontent.com/8918977/48815973-42672a00-ecf5-11e8-8df0-848fbdac2474.png)

**Comment by AlzPatz** [comment]
Hi - thank you so much for taking a look! and yes I feel a bit stupid ... I had previously tried SingleAdditiveBlend but stopped short trying each option. My end use case will be drawing a number of times on the R32_Float with the hope that drawing a -1 over a +1 will result in a zero. I need to look more closely into BlendStates but fear overrideblend may just replace the number already present.

in any case, this has been a huge help, thanks again :)

**Comment by AlzPatz** [comment]
You the man - that was exactly what I wanted to work out if was possible (custom blend state in Velcro’s) when I next get some keyboard time.i was worried I wouldn’t be able to use anything beyond the pre-sets. Thanks (again) :)

**Comment by AlzPatz** [comment]
can confirm custom blendstate did the trick :) queue some fun corny waves

![thanks](https://user-images.githubusercontent.com/3255197/48909866-4bc3d400-ee66-11e8-89b1-b871e00b8e39.png)

will close

**Comment by mellinoe** [comment]
You're welcome 😄 . Glad to help.
