### ISSUE TITLE
Cannot create TextureView of TextureUsage.Storage Texture in D3D

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [mellinoe/veldrid#134]
[ID3D11Device::CreateShaderResource](https://msdn.microsoft.com/de-de/library/windows/desktop/ff476521(v=vs.85).aspx) requires the resource to have a D3D11_BIND_SHADER_RESOURCE flag, which corresponds to TextureUsage.Sampled. Veldrid does not, however, allow this to be enabled at the same time as TextureUsage.Storage.

How else should I pass a read/write texture to a shader?

**Comment by mellinoe** [comment]
Hey there @InterplanetaryEngineer, you should be able to combine `TextureUsage.Sampled` and `TextureUsage.Storage` without a problem. The "ComputeTexture" sample project does this: https://github.com/mellinoe/veldrid-samples/blob/master/src/ComputeTexture/Application/ComputeTexture.cs#L109-L115. Did you hit any particular issue regarding this?

**Comment by InterplanetaryEngineer** [comment]
Please excuse me, I had worked on this late at night and seem to have combined the flags wrongly.

Thanks for the quick response and the sample project though!
