### ISSUE TITLE
[OpenGL ES] Improve detection for non-zero base vertex support

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid#136]
``DrawIndexed`` with a non-zero vertex offset can work just fine on my mobile device (Xiaomi Redmi 4X), even though ``GL_OES_draw_elements_base_vertex`` is not listed as a supported extension.
According to [the docs](https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glDrawElementsBaseVertex.xhtml), ``glDrawElementsBaseVertex`` is part of core GLES 3.2. As far as I understand, there is no need to check for any extensions if the device implements ES 3.2. 

Proposed change:
```diff
-DrawElementsBaseVertex = GLVersion(3, 2)
+DrawElementsBaseVertex = GLVersion(3, 2) || GLESVersion(3, 2)
    || IsExtensionSupported("GL_ARB_draw_elements_base_vertex")
    || IsExtensionSupported("GL_OES_draw_elements_base_vertex");
```

**Comment by mellinoe** [comment]
Good catch. I have pushed a commit with this change.
