### ISSUE TITLE
Metal backend

### ISSUE THREAD

**Issue by amerkoleci** [mellinoe/veldrid#14]
Hi dude,
This is something I'm working on my engine also, would be fine to add the Metal backend support for macOS and if you plan in the future even for iOS.

Take look here:
http://metalbyexample.com/
https://github.com/xamarin/ios-samples/tree/master/ios8/MetalTexturedQuad/MetalTexturedQuad

**Comment by mellinoe** [comment]
Yeah, I would love to add a Metal backend. The OpenGL backend can't possibly be fully-featured on macOS and iOS because of the primitive version of OpenGL/ES used there. I think the current API should translate decently to Metal, from what I've read of it.

Unfortunately, I don't actually have a Mac to build it out on. I'm planning to put out an initial version without it, and at some point buy a cheap-ish device to test the Metal version on.

**Comment by mellinoe** [comment]
I now have a MacBook, so I will start adding this soon.

**Comment by amerkoleci** [comment]
Still wondering how you are going to bridge metal (ObjectiveC) under .NET standard

**Comment by mellinoe** [comment]
I'm planning to write my own bindings, most likely using the [Objective-C Runtime APIs](https://developer.apple.com/documentation/objectivec/objective_c_runtime) directly. I'll probably do something minimal like I've done for OpenGL, and just import the functions I use.

**Comment by mellinoe** [comment]
<img width="966" alt="screen shot 2017-12-17 at 1 00 18 pm" src="https://user-images.githubusercontent.com/8918977/34083749-58bf03ca-e32a-11e7-94be-ba1470b89794.png">

I've gotten really basic rendering working, so I at least know how the basic API works. Nothing integrated into Veldrid yet, though.

**Comment by mellinoe** [comment]
I have almost everything working in the Metal backend at this point.

![image](https://user-images.githubusercontent.com/8918977/34588207-9a4659f8-f160-11e7-805f-9e807bdccfd9.png)

Despite a lot of stuff being REALLY hacky right now (suboptimal Objective-C interop, allocating tons of transient resources, general unfamiliarity with the API, etc), it's already significantly faster than the OpenGL backend on macOS. There are still a few things I haven't implemented yet (which aren't needed by that demo program in the screenshot), but they shouldn't be very difficult. Those are things like compute shaders, MSAA, indirect rendering, and a few other odds and ends.

**Comment by mellinoe** [comment]
The  Metal backend is now merged into master. It will go into the first stable release, because it's already fully-featured and tested.
