### ISSUE TITLE
Is it possible to render to a view rather than winodw?

### ISSUE THREAD

**Issue by equinox2k** [mellinoe/veldrid#140]
Hi,

Looking into using Veldrid for rendering on iOS/Android/Mac/Win but one thing I noticed is that it seems to need a window to be created. However my current use case is to embed 3d rendering inside an existing window/view. Is it currently possible?

As a side note been having problems running the mobile samples as always says can't find x embedded asset for example on iOS on texture cube demo crashes with "Cube-vertex.ios.metallib" not existing.

I also had to re-setup Veldrid NuGet dependancies in the TextureCube.iOS / other projects as they were not found.

**Comment by mellinoe** [comment]
> it seems to need a window to be created

Generally speaking, you don’t need a window at all to use Veldrid (with the exception of the OpenGL backend). You can create a device and render entirely outside of any visible window if you want. To present images to the user (e.g. to a window or other application view), you do need a “Swapchain”, a special kind of resource. You can create Swapchains for several native UI views, including UIViews on iOS, SurfaceViews on Android, and custom controls in WPF. However, making Swapchains is platform-specific (because it relies on the specific operating system and UI framework being used) and can be a bit confusing. If I knew what you were trying to accomplish I could provide some more specific help and guidance.

> As a side note been having problems running the mobile samples as always says can't find x embedded asset for example on iOS on texture cube demo crashes with "Cube-vertex.ios.metallib" not existing.

What version of macOS and Xcode do you have installed? I recently found that the newer versions of Xcode changed some parameters in the metal compiler, which could have affected the sample projects since they invoke the compiler during the build.

**Comment by equinox2k** [comment]
Hi Thanks for getting back so quickly.

To try and summarize, I have a native application where user goes thru many steps. But at various points they can do a 3d preview. The 3d preview comes with a native side panel and native controls as an overlay. The app in question is also multi platform. I currently created the 3d part using OpenTK but since OpenGL is no longer officially supported on Mac. I thought it's time to switch to a more cross backend platform, hence why I think Veldrid is a perfect solution. 

If i'm understanding correctly it is mostly case of setting up the viewing layer (i.e for metal a CAMetalLayer ) as you would normally do natively on MacOS then using render cycle code as per OffScreen example.

However i'm not quite sure what to do about this part, and if any extra steps needed...

```
            GraphicsDeviceOptions options = new GraphicsDeviceOptions(
                debug: false,
                swapchainDepthFormat: PixelFormat.R16_UNorm,
                syncToVerticalBlank: true,
                resourceBindingModel: ResourceBindingModel.Improved);
#if DEBUG
            options.Debug = true;
#endif
            _gd = VeldridStartup.CreateGraphicsDevice(_window, options);
            _factory = new DisposeCollectorResourceFactory(_gd.ResourceFactory);
            GraphicsDeviceCreated?.Invoke(_gd, _factory, _gd.MainSwapchain); 
```

Any example code to get me started on MacOS would be greatly appreciated.

Im currently running Mac OS 10.14.1 (Mojave) with latest stable VisualStudio for Mac, with Xcode 10.1

**Comment by mellinoe** [comment]
> To try and summarize, I have a native application where user goes thru many steps. But at various points they can do a 3d preview. The 3d preview comes with a native side panel and native controls as an overlay. The app in question is also multi platform.

I see -- so the 3D viewer (written in C#) interoperates in some way with the native application and serves as a visualization of sorts? I think what would help most would be to understand how you are currently creating the OpenGL widget. If you indeed have a CAMetalLayer (or can create one), then it should be very easy to integrate with Veldrid. Currently, there isn't a way to create a Swapchain from an already-created CAMetalLayer, but a subset of the NSWindow Swapchain code can be pulled out to support that directly very easily.

> since OpenGL is no longer officially supported on Mac. I thought it's time to switch to a more cross backend platform, hence why I think Veldrid is a perfect solution.

Yes, Veldrid will be a very good replacement -- performance on macOS will be significantly better using the Metal backend, and you'll have more consistent behavior all around compared to OpenGL (on all platforms).

> Im currently running Mac OS 10.14.1 (Mojave) with latest stable VisualStudio for Mac, with Xcode 10.1

I suspect you are hitting the same problem I just dealt with after my own Xcode upgrade, then. I will try to implement a fix for ShaderGen sometime soon and update the samples repository.

**Comment by mellinoe** [comment]
@equinox2k After looking into this some more over the weekend, I added support for creating a Metal Swapchain directly from an `NSView`. I will upload a usage example sometime soon.

**Comment by equinox2k** [comment]
Awesome I can’t thank you enough, I’m looking forward to be able to contribute to this project once I get my bearings :)

**Comment by equinox2k** [comment]
@mellinoe so ive forked example here... https://github.com/equinox2k/VeldridNSViewExample

I fixed duplicated solution file + added a iOS example so far, however it says..

Attempting to JIT compile method '(wrapper native-to-managed) Veldrid.MTL.MTLGraphicsDevice:OnCommandBufferCompleted (intptr,Veldrid.MetalBindings.MTLCommandBuffer)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

I know iOS doesn't allow JIT but not sure what to do in the case of Veldrid?

**Comment by mellinoe** [comment]
That is part of some very new code in the Metal backend. I will take a look tonight to see what the problem is. Likely it’s just missing an attribute that Xamarin wants it to have.

**Comment by equinox2k** [comment]
@mellinoe thanks, I've now created an android example (using Vulkan) and deployed to device but getting...

"SamplerFilter.Anisotropic cannot be used unless GraphicsDeviceFeatures.SamplerAnisotropy is supported."

When CreateVulkan is called...

```
        GraphicsDeviceOptions options = new GraphicsDeviceOptions(
                debug: false,
                swapchainDepthFormat: null,
                syncToVerticalBlank: false,
                resourceBindingModel: ResourceBindingModel.Improved,
                preferDepthRangeZeroToOne: true,
                preferStandardClipSpaceYDirection: true);

            Device = GraphicsDevice.CreateVulkan(options);
```

Is there a way to disable filter?

**Comment by mellinoe** [comment]
Interesting, your device doesn’t support anisotropic filtering. I’ll put up a fix for that tonight as well. What device are you using, out of curiosity?

**Comment by equinox2k** [comment]
Samsung S8, btw I did pr for shadergen which solves fact my Xcode is not Xcode.app but updating samples to use new version I still have problems but at least fixes that part :)

**Comment by mellinoe** [comment]
I've fixed the Metal backend on iOS in the prerelease packages, and also allowed the Vulkan backend to work when anisotropic filtering is unavailable.

**Comment by equinox2k** [comment]
@mellinoe I can confirm fixes are working. I have one issue with my android test VeldridActivityExample located in https://github.com/equinox2k/VeldridNSViewExample 

I have forced app to use OpenGLES and works in emulator, however I get error on device. Wondering if works for you?

**Comment by equinox2k** [comment]
@mellinoe as to doing a windows example I have got a bit stuck...

I am assuming for windows I create a custom user control and do a similar setup to android. However im not sure what to pass into...

public static SwapchainSource CreateWin32(IntPtr hwnd, IntPtr hinstance)

**Comment by mellinoe** [comment]
Heres a WPF example that I shared when this came up previously:

https://gist.github.com/mellinoe/2ba885476f51ef867715e5aa64b390de#file-veldridcomponent-cs

**Comment by equinox2k** [comment]
@melinoe thanks so much. Spent most of day wondering why I get problem above with OpenGLES on android. Wondering if for some reason velgrid thinks i want to use compressed textures or is doing checks and crashing causing device to return null.

**Comment by mellinoe** [comment]
> Wondering if for some reason velgrid thinks i want to use compressed textures or is doing checks and failing causing device to return null.

I'm not sure that's a fatal error message, since it appears twice, and seems to keep doing a bunch of stuff after the first occurrence. I can't really identify what is actually going wrong other than that -- the log seems normal for the most part. I see some hits on Google from other folks with Samsung devices complaining about that error message, but it's not clear to me whether it's actually problematic, or just a weird driver message that is harmless. 

> `<uses-feature android:glEsVersion="0x00020000" android:required="true" />`

Veldrid actually requires GLES 3.0, so you might try changing it to `0x00030000`

Feel free to open a different issue if you keep running up against that. The message overall suggests you should add something to the app's permissions, but I'm not sure what.
