### ISSUE TITLE
Handling WindowEvents not thrown by sdl2window

### ISSUE THREAD

**Issue by Eightvo** [mellinoe/veldrid#147]
In Src/Veldrid.SDL2/Sdl2Windows.cs

There is a method: ProcessEvents which accepts an SDLEventHandler.

If the eventhandler is not populated it uses the method HandleEvent and if it is populated it uses the SDLEventHandler to handle all events.

The issue is that that the default eventhandler does not thow events for many of the possible events (In particular the gamepad events).  I was going to simply re-write the default event handler in the consuming code and pass that to the function... but the default EventHandler utilizes Unsafe code.... this means that I'd have to mark my entire assembly Unsafe for this one simple operation.

Are there any plans to modify this part to include throwing events for gamepad events? Otherwise, what is the recommended method for detecting and handling gamepad input?  

I know this is not meant to be an all-out game engine library and only the display portion... but I am not sure how else I would access the events that are not being thrown by Veldrid.SDl2Window.

**Comment by Eightvo** [comment]
Another possiblity would to allow the a version of PumpEvents with a EventType->Delegate map... then uses would be able to override specific eventtypes without overriding the entire enventhandler.

**Comment by mellinoe** [comment]
Hm, one possible option would be exposing the default event handler method, which you could use as a fallback for events you don't want to handle. It's unsafe as you mention, but a safe version wrapper could be made public.

> Another possiblity would to allow the a version of PumpEvents with a EventType->Delegate map... then uses would be able to override specific eventtypes without overriding the entire enventhandler.

I'd rather just add more strongly-typed events for the things that are important. I think that is more usable and discoverable than a map.

**Comment by mellinoe** [comment]
Related: #156

**Comment by mellinoe** [comment]
This is covered by the new `Sdl2Events` class, which has static functions that allow you to register arbitrary SDL2 event handlers and pump the message loop yourself. The feature integrates cleanly with the window-based events generated by Sdl2Window.
