### ISSUE TITLE
Generate Mipmaps for BC1 texture

### ISSUE THREAD

**Issue by pzgulyas** [mellinoe/veldrid#151]
Is it possible to generate mipmaps for BC1 textures? When I try to create a texture, like:
```
Texture texture1 = graphicsDevice.ResourceFactory.CreateTexture(TextureDescription.Texture2D(256, 256, 9, 1, PixelFormat.BC1_Rgba_UNorm, TextureUsage.RenderTarget | TextureUsage.Sampled | TextureUsage.GenerateMipmaps));
```
I get a SharpDX exception saying the parameter is not valid.

**Comment by mellinoe** [comment]
Unfortunately, runtime mipmap generation will not work on compressed textures. Generally, you are only able to de-compress textures in a compressed format -- this also means that you're not able to create a Framebuffer with a compressed format color target. You will need to generate the mipmaps for such a texture offline.

**Comment by pzgulyas** [comment]
Ah, thank you. I just wasn't aware of that, because MonoGame, that I was using before, silently ignores this combination.
