### ISSUE TITLE
CreateWayland method not found

### ISSUE THREAD

**Issue by vpenades** [mellinoe/veldrid#153]
Hi, I've just noticed you've began supporting VR, which is great!

I wanted to give it a try by running Veldrid.VirtualReality.Sample , but It gave me this exception:

```
VeldridStartup:

public static GraphicsDevice CreateDefaultD3D11GraphicsDevice(
            GraphicsDeviceOptions options,
            Sdl2Window window)
        {
            SwapchainSource source = GetSwapchainSource(window); *

System.MissingMethodException: 

Method not found: 'Veldrid.SwapchainSource Veldrid.SwapchainSource.CreateWayland(IntPtr, IntPtr)'.
```

Any clues?

**Comment by mellinoe** [comment]
Hey @vpenades , thanks for pointing this out. There was an issue with how various projects were referencing each other, which resulted in this error. I have pushed a change to master which should fix this problem. Can you pull that down and try running it again?

**Comment by vpenades** [comment]
Hi, it worked with the latest update!

I am definitely going to do some tests with it, I really wanted to start digging with VR!

Btw, I have an Oculus Rift DK2, the sample worked just fine. I am considering picking an Oculus GO!... given that Veldrid runs on Android, maybe you cound explore the possibility to suport the Android VR SDKs.... so far there's Google's Cardboard, Google's Daydream and Oculus Gear VR SDK

**Comment by mellinoe** [comment]
Yes, I'd like to support the mobile VR SDK's eventually. I'll need to acquire some extra hardware for that, but I doubt the implementation will be all that complicated. The groundwork is already in place, assuming the mobile SDKs are similar to PC.

Let me know if you hit any more snags in your testing; marking this one as closed for now.
