### ISSUE TITLE
[Question] Gamepad support using SDL2

### ISSUE THREAD

**Issue by phelioz** [mellinoe/veldrid#156]
Really enjoying Veldrid, great library!
But lately I have been trying to add gamepad/joystick support to one of my project using Veldrid. I know Veldrid only inits the SDL_Video SDL initialization. But even when I initialise SDL_Joystick and SDL_Gamepad manually I don't get any event from joysticks or gamepads in the pumpEvents delegate?

Any help to enable joystick/gamepad support would be deeply appreciated!

**Comment by phelioz** [comment]
I see, was wondering where they got filtered out but I now see that they are filtered in the Sdl2EventProcessor by window. 
That solution looks perfect! would make it much easier to handle the events 👍

**Comment by phelioz** [comment]
Not to hurry you or anything but I could help if you know it will be a long time until you can implement this.

**Comment by mellinoe** [comment]
@phelioz The work is pretty much complete, so I've merged it to master. I may make some minor tweaks to the public API before 4.6.0 is officially released, but it shouldn't change too drastically.

NeoDemo now contains an "Sdl2ControllerTracker" class which uses the new SDL2 event subscription feature to track a single game controller. The camera in NeoDemo can also be controlled by a controller now.

**Comment by phelioz** [comment]
I really appreciate that you added this so fast :) Was like the only thing related to Veldrid holding my project back. So again thanks and really nice of you to add even a simple demo of it!

**Comment by AlzPatz** [comment]
I second the thanks. This was on my to do list too :) nice one

**Comment by mellinoe** [comment]
The feature is in master now, and NeoDemo has basic controller tracking implemented, which can be taken as a base for anyone wanting gamepad integration in their app. Closing this issue out, but feel free to open a new one for specific problems with the new support.

**Comment by Eightvo** [comment]
I'd also like to say thanks, is this available in the nuget lib yet? I can't seem to find the class... 

What is the preferred method of referencing this library? Like... is it better to fork this and reference by project?  Or subscribe to the nuget pkg?

**Comment by mellinoe** [comment]
@Eightvo It has not been included in a stable release on NuGet yet.

The preferred method is to reference the stable NuGet package (from nuget.org) -- it is guaranteed to be stable, and with no breaking changes. You can reference the project directly or use the myget feed, but I don't make any guarantees about work that is still in-progress.

Hopefully I will get some time soon to nail down the 4.6.0 release.

**Comment by Eightvo** [comment]
@mellinoe The event passed to the delegate supplied with Sdl2Events.Subscribe contains a field WindowId... however the class Sdl2Window does not seem to expose the windowId..
