### ISSUE TITLE
dotnet quit unexpectedly when running textured cube sample on Mac

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#158]
When running the TexturedCube sample (cloned from today) I get "dotnet quit unexpectedly" pop-up dialog, and the application closes. There are no other visible errors.
If I run it from commandline (`dotnet run -p src/TexturedCube/Desktop/TexturedCube.Desktop.csproj`) this always happens. If I run it from VS for Mac then it sometimes happens, and sometimes the app displays normally.

After adding printouts to try and track where the crash is coming from, I eventually traced it to the `WaitForIdle` call here: 
https://github.com/mellinoe/veldrid-samples/blob/13d8611ea48ee4467cbd35e760e3e62bb58da5de/src/TexturedCube/Application/TexturedCube.cs#L132

This never happens on the first draw call, but either the second or third draw calls for some reason.

If I comment that line out, the application runs fine every single time.

**Comment by mellinoe** [comment]
Hi @tzachshabtay, I'm sorry that you hit this. I'm debugging through it now, and I believe I see the problem. I will update the thread once I've worked through it completely.

**Comment by mellinoe** [comment]
I've tested out a fix and committed it to master: https://github.com/mellinoe/veldrid/commit/ea055f119a6359f0a473faa5cf4d0b5c0a1573eb.

The samples repo isn't yet updated, but I will do that shortly.

**Comment by mellinoe** [comment]
The samples repo has been updated.
