### ISSUE TITLE
[Question] Any books you'd recommend for learning 3D graphics?

### ISSUE THREAD

**Issue by allisterb** [mellinoe/veldrid#16]
This is a pretty cool project and I plan on reading the code a lot but I've never done any graphics programming before. Any books you'd recommend as a companion for learning 3D graphics?

**Comment by mellinoe** [comment]
I'm not really one to learn from books, personally, so I don't really have any good recommendations on that front. Unfortunately, a lot of the books that people recommend are extremely old and/or reference long-obsolete technologies.

For me, the best way to learn was to just start building stuff. I actually found that learning multiple graphics APIs helped me to learn each of them better, even if that sounds a bit counterintuitive.
