### ISSUE TITLE
BackendInfo*****.cs do not take into consideration EXCLUDE_XXXX_BACKEND defines

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#162]
Isn't these files should be wrapped into EXCLUDE_XXXXX_BACKEND defines?
Same note for GraphicsDevice.cs: functions GetD3D11Info/GetVulkanInfo/GetOpenGLInfo I suppose also should be wrapped to these defines

**Comment by mellinoe** [comment]
Yes, these new files should probably be wrapped in those define constants to work correctly with the backend exclusion stuff, as well as the new methods on GraphicsDevice.

**Comment by Krakean** [comment]
@mellinoe then hope to see #161 and #162 fixed in master :)

**Comment by mellinoe** [comment]
These are excluded now.
