### ISSUE TITLE
OpenGL and Texture1D arrays

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid#165]
I'm not entirely sure if OpenGL actually supports 1D texture arrays. At least on my machine ``glCreateTextures`` fails with error 1280 (invalid enum) when passing Texture1DArray as the texture target. I also noticed that [xenko](https://github.com/xenko3d/xenko/blob/e6c7966fc3acca5bad012daeba9fc4c1587fb01f/sources/engine/Xenko.Graphics/OpenGL/Texture.OpenGL.cs#L169) specifically doesn't support Texture1D arrays under OpenGL. I wonder if Veldrid should do the same.

**Comment by mellinoe** [comment]
The GL docs imply that it should be supported (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCreateTextures.xhtml), but that’s not necessarily a guarantee of anything. I’ll take a look on my machine in a bit and see if it works there.

**Comment by mellinoe** [comment]
@SomeAnon42 There were a few other code paths that weren't handling 1D textures and texture arrays correctly, but they should all be fixed now. I've tested that this works on macOS as well.

**Comment by mellinoe** [comment]
This should be fixed now.
