### ISSUE TITLE
Ability to add / remove textures in ImGui.Net ImGuiRenderer.cs

### ISSUE THREAD

**Issue by equinox2k** [mellinoe/veldrid#166]
Would like to have the addition of the ability to add / remove textures in ImGui.Net ImGuiRenderer.cs by IntPtr as have dynamic textures being loaded but only way to tear them down is to ClearCache which means I also have to reload non dynamic textures.

**Comment by zaafar** [comment]
would love to have this feature!

**Comment by mellinoe** [comment]
This has been added to master, and will be a part of 4.6.0.

```C#
public void RemoveImGuiBinding(TextureView textureView);
public void RemoveImGuiBinding(Texture texture);
```

There is no overload accepting an IntPtr, but you shouldn't need to be storing the IntPtr in your own code anyways, and I'd like to encourage users to rely on the caching that GetOrCreateImGuiBinding does.
