### ISSUE TITLE
[Vulkan] Exception for textures equal or larger than 4096

### ISSUE THREAD

**Issue by phelioz** [mellinoe/veldrid#173]
Get an exception when using ImageSharpTexture CreateDeviceTexture with texture sizes 4096 * 4096 or larger. Doesn't happen when running OpenGL or Direct3D11 as backend. Only Vulkan from the backends I have tested.
The exception is a System.ExecutionEngineException in CopyTextureRegion in Util.cs. More specific from
`
Buffer.MemoryCopy(
                    src,
                    dst,
                    totalCopySize,
                    totalCopySize);
`

**Comment by mellinoe** [comment]
Good catch on that. This should be fixed in https://github.com/mellinoe/veldrid/commit/3bcd470d6ad3a1b5398b9b1614177db269686d6a
