### ISSUE TITLE
Using a Pipeline in multiple CommandLists

### ISSUE THREAD

**Issue by generatives** [mellinoe/veldrid#174]
Are there any potential issues with binding the same Pipeline to multiple CommandLists and using them concurrently? Could it add a performance overhead on certain backends?

**Comment by mellinoe** [comment]
No, I don't think there should be any particular issues with that. Keep in mind that CommandLists just record commands for the GPU to execute later (when submitted), so in many cases they don't do anything particularly expensive during the recording phase. I wouldn't expect using a Pipeline in multiple CommandLists to be much different from other resources (DeviceBuffers, Textures, etc.).

**Comment by generatives** [comment]
Okay thank you!
