### ISSUE TITLE
SamplerAddressMode axis mapping is different between backends

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#176]
I'm setting a custom SamplerDescription for my 2d game.
On OpenGL (on mac), addressModeU corresponds to the x-axis and addressModeV corresponds to the y-axis (like I would expect), but on Metal addressModeV corresponds to the x-axis and addressModeW corresponds to the y-axis.

**Comment by mellinoe** [comment]
Ouch, you're correct about that. The [documentation](https://developer.apple.com/documentation/metal/mtlsamplerdescriptor) makes this clear. I'll push up a fix shortly.

**Comment by mellinoe** [comment]
@tzachshabtay This should be fixed in the latest commit to master: https://github.com/mellinoe/veldrid/commit/be6d1db3d6d05344d35e0e0c57a8122a4305c395

**Comment by tzachshabtay** [comment]
@mellinoe I am super confused currently. Now it seems that the OpenGL mappings have the same behavior I was previously describing metal had (i.e addressModeV corresponds to the x-axis and addressModeW corresponds to the y-axis). I could have sworn I tested this on OpenGL but maybe I didn't?

Anyway, looking at the ctor for SamplerDescription U/V/W correspond to R/S/T, and in OpenGL S&T correspond to X&Y, so I think actually that my assumption that addressModeU corresponds to the x-axis (which was based on the order of the arguments in SamplerDescription) was wrong and that the previous mapping for metal was right all along?
Sorry for confusing you...
