### ISSUE TITLE
VertexElementDescription can't describe matrix elements to DirectX

### ISSUE THREAD

**Issue by TheMostCuriousThing** [mellinoe/veldrid#177]
GLSL allows the declaration of matrix vertex attributes like so:

```
layout(location = 0) in vec3 Position;
layout(location = 1) in vec4 Color;
layout(location = 2) in mat4 World;
layout(location = 6) in vec3 Normal;
```

SPIR-V translates this to DirectX in a way corresponding to seven input elements with the following semantic names, semantic indices, and DXGI formats:
- "TEXCOORD", 0, `R32G32B32_Float`
- "TEXCOORD", 1, `R32G32B32A32_Float`
- "TEXCOORD2_", 0, `R32G32B32A32_Float`
- "TEXCOORD2_", 1, `R32G32B32A32_Float`
- "TEXCOORD2_", 2, `R32G32B32A32_Float`
- "TEXCOORD2_", 3, `R32G32B32A32_Float`
- "TEXCOORD", 6, `R32G32B32_Float`

(The "2" in "TEXCOORD2_" being the location index of the `World` matrix.)

However, `VertexElementDescription` depends on an `VertexElementSemantic` enum and doesn't allow arbitrary strings.

This *specific* issue could be fixed outside the public API, by `D3D11ResourceCache.CreateNewInputLayout` detecting consecutive vertex elements with the same name and adjusting the semantic names and indices accordingly. But this is a bodgy and inelegant fix:
- Changing logic within `D3D11ResourceCache` would require some coupling to / knowledge of SPIR-V.
- I don't know the ramification of repeating `VertexElementDescription.Name` values on OpenGL, as I don't have a way of testing OpenGL.

So, since this is probably a public-facing change, it needs design guidance before I can put work into it. Could `VertexElementDescription`s allow for arbitrary semantic names?

**Comment by mellinoe** [comment]
This one is tricky. To be honest, I'm inclined to not support this directly. Given how rare this is (relatively speaking), I think it's reasonable to just declare 4 separate vertex attributes and then combine them in the vertex shader. Given how the HLSL compiler behaves, it appears that this is likely what's going on behind the scenes anyways. Additionally, I'm very hesitant to rely on on a particular implementation detail of SPIRV-Cross. Thoughts?

**Comment by TheMostCuriousThing** [comment]
That is indeed a reasonable workaround, fair enough.
