### ISSUE TITLE
Can't find SDL on Ubuntu 17.10 Wayland

### ISSUE THREAD

**Issue by klaussilveira** [mellinoe/veldrid#18]
I've compiled SDL2 from source and, for some reason, Veldrid can't find the lib. 

```
System.TypeInitializationException: The type initializer for 'Veldrid.Sdl2.Sdl2Native' threw an exception. ---> System.IO.FileNotFoundException: Could not find or load the native library: libSDL2-2.0.so
``` 

I've tracked the code to: https://github.com/mellinoe/veldrid/blob/444d3295bf97346ffafdbdd0960c96fdce91d0a8/src/Veldrid.SDL2/Sdl2.cs#L19

Switching the library name to `libSDL2-2.0.so.0` solved the issue. Maybe adding a regex for the NativeLoader lib that looks like this `libSDL2-2.0.so(|.1|.0)` would make builds more friendly?

**Comment by mellinoe** [comment]
> Maybe adding a regex for the NativeLoader lib that looks like this libSDL2-2.0.so(|.1|.0) would make builds more friendly?

Yeah, it shouldn't be too hard to make the library loading a little bit more lenient. There is already an extension point in `NativeLibraryLoader` that should allow multiple names to be tried (although I forget exactly how I did it).

**Comment by mellinoe** [comment]
This is fixed in beta 2.
