### ISSUE TITLE
[OpenGL] Map can return a pointer to a different resource

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid#183]
In the OpenGL backend, Map is executed on the worker thread, and the result is propagated to the caller using a shared field, ``_mapResultHolder``.
https://github.com/mellinoe/veldrid/blob/cb08faf1a22fd328a14dce4435ebe2377538587f/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs#L858-L859
This code is placed outside the lock, meaning multiple threads can submit their Map work items to the execution thread's queue at the same time. ``_mapResultHolder``, however, can only hold the result of the last call. If the worker thread is fast enough, a pointer to the wrong resource may be returned to some of the callers:
![image](https://user-images.githubusercontent.com/6377116/57052897-fa303880-6c92-11e9-8e2b-80462a5c5101.png)

I think we should find another way to propagate the result to the caller, maybe something like a ``TaskCompletionSource<MapResult>``.

**Comment by mellinoe** [comment]
Can you test out this branch? https://github.com/mellinoe/veldrid/tree/opengl-concurrent-map

**Comment by SomeAnon42** [comment]
That worked.
Also it looks like these two lines can be safely deleted.
https://github.com/mellinoe/veldrid/blob/580c72786687c557d0d25c9abe18a0aeb10c9205/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs#L1586
https://github.com/mellinoe/veldrid/blob/580c72786687c557d0d25c9abe18a0aeb10c9205/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs#L1608

**Comment by mellinoe** [comment]
Thanks for the confirmation. This is merged to master now.

> Also it looks like these two lines can be safely deleted.

Yep, you're right, thanks.
