### ISSUE TITLE
VALIDATE_USAGE macro issue

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#184]
@mellinoe 
Veldrid have ValidationHelper.cs, which is compiled only when VALIDATE_USAGE is defined.
But, in several files (****ResourceFactory.cs) it used without checking for VALIDATE_USAGE, like in case of D3D11ResourceFactory.cs:
   47         public override ResourceSet CreateResourceSet(ref ResourceSetDescription description)
   48         {
   49             ValidationHelpers.ValidateResourceSet(_gd, ref description); <-- compile error without VALIDATE_USAGE.
   50             return new D3D11ResourceSet(ref description);
   51         }

**Comment by mellinoe** [comment]
Thanks for catching this. It should be fixed on master now.
