### ISSUE TITLE
cannot draw image using pixel format PixelFormat.R8_G8_B8_A8_UInt

### ISSUE THREAD

**Issue by mjkkirschner** [mellinoe/veldrid#188]
when I attempt to use a texture with `PixelFormat.R8_G8_B8_A8_UInt` or `PixelFormat.R8_G8_B8_A8_SInt` (actually I only seem to be able to use `UNorm` formats) - I do not see my texture rendered as an image.

When I switch to using a `R8_G8_B8_A8_UNorm` I can see the image - I've tried passing varying data, random data, `FFFF` etc - draws fine with UNorm, but not with Uint.

I am on Mac, consuming Veldrid via Nuget and calling it through ImgGUI.net

my code looks like this:

``` c#
    var texture = gd.ResourceFactory.CreateTexture(TextureDescription.Texture2D(256, 256, 1, 1, PixelFormat.R8_G8_B8_A8_UInt, TextureUsage.Sampled));
            CPUframeBufferTextureId = controller.GetOrCreateImGuiBinding(gd.ResourceFactory, texture);


 RgbaByte[] data = new RgbaByte[256 * 256];
                for (int y = 0; y < 256; y++)
                    for (int x = 0; x < 256; x++)
                    {
                        data[y * 256 + x] = new RgbaByte(128,255,128,250);
                    }

                gd.UpdateTexture(texture, data, 0, 0, 0, 256, 256, 1, 0, 0);

                ImGui.Image(CPUframeBufferTextureId, new Vector2(256));


```

I've tried passing various other types for data[] as well, `int32`, `byte` etc.

Am I missing something obvious?

**Comment by mellinoe** [comment]
> Am I missing something obvious?

@mjkkirschner  The standard ImGui shaders work with regular floating-point or `UNorm` textures, e.g. they expect the colors they sample to be in the 0.0 - 1.0 range. Sampling from a UInt/SInt texture will not give you the result you want (because e.g. the range would be 0 - 255), and in general those formats shouldn't be used to store "color" information. You should just use a standard `UNorm` format, or one of the floating-point formats. The `UInt`/`SInt` texture formats are used to store more specialized data that is actually integral in nature.

Does that help?

**Comment by mjkkirschner** [comment]
@mellinoe thanks! - definitely helps.

If I wanted to use one of these integer formats (I actually do have a non standard integer color format from a cpu emulator) would I only need to change the imgui.net shaders which are bundled into veldrid imgui renderer - here:
https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.ImGui/ImGuiRenderer.cs#L119

or would I still run into a wall with dear imgui itself?

**Comment by mellinoe** [comment]
> I actually do have a non standard integer color format from a cpu emulator

What is the format of that data?

Another option that I didn't mention is to create a TextureView with a UNorm format. This would cause a UInt texture to be viewed as a UNorm texture when sampled in a shader:

```C#
Texture texUInt8 = CreateTexture(PixelFormat.R8_G8_B8_A8_UInt); // Existing code
var viewDesc = new TextureViewDescription(texUInt8, PixelFormat.R8_G8_B8_A8_UNorm_SRgb);
var textureView = factory.CreateTextureView(viewDesc); // Use textureView instead of texUInt8 when passing to ImGui.
```

**Comment by mjkkirschner** [comment]
the format is something like RGBA4 - (16 bit) if that existed. Currently I am creating a RGBA8 Unorm texture - and expanding each value like this:
https://github.com/mjkkirschner/8chips-assembly-simulator/blob/master/simulatorUI/simulatorUI.cs#L193

seems to give me the colors I am expecting - I will definitely try your suggestion above though - and thanks for this awesome tool in c#!

![image](https://user-images.githubusercontent.com/508936/58768225-c1230680-8565-11e9-8883-f4ddf36fcccd.png)

**Comment by mellinoe** [comment]
Yes, it sounds like you have an RGBA4 UNorm texture, and the correct approach is to expand it to an RGBA8 UNorm texture. You don't need to involve integral formats at all in this case.

BTW, is your screenshot intentionally blue-ish tinted?

**Comment by mjkkirschner** [comment]
<img width="527" alt="Screen Shot 2019-06-06 at 9 00 19 PM" src="https://user-images.githubusercontent.com/508936/59075365-23e60c00-889e-11e9-9254-3fb0f5e3b4fa.png">

yes, messed a bit with the style colors for imgui, and image that was being displayed was blueish - here's a more varied one.

Thanks for the help here - closing.
