### ISSUE TITLE
Type initializer for Veldrid.Sdl2.Sdl2Native: NullReferenceException

### ISSUE THREAD

**Issue by parzivail** [mellinoe/veldrid#19]
Exception thrown: 'System.TypeInitializationException' in Veldrid.SDL2.dll
    An unhandled exception of type 'System.TypeInitializationException' occurred in Veldrid.SDL2.dll
    The type initializer for 'Veldrid.Sdl2.Sdl2Native' threw an exception
    ---
    NullReferenceException: Object reference not set to an instance of an object.

The code is the Part 1 tutorial:

```csharp
using Veldrid;
using Veldrid.Sdl2;
using Veldrid.StartupUtilities;

namespace VeldridTutorial
{
    class Program
    {
        private static GraphicsDevice _graphicsDevice;

        static void Main(string[] args)
        {
            WindowCreateInfo windowCI = new WindowCreateInfo()
            {
                X = 100,
                Y = 100,
                WindowWidth = 960,
                WindowHeight = 540,
                WindowTitle = "Veldrid Tutorial"
            };
            Sdl2Window window = VeldridStartup.CreateWindow(ref windowCI);

            _graphicsDevice = VeldridStartup.CreateGraphicsDevice(window);

            while (window.Exists)
            {
                window.PumpEvents();
            }
        }
    }
}
```

I'm running Windows 10, using the `v4.0.0-beta1` from NuGet. Any help is appreciated.

**Comment by parzivail** [comment]
Here's the stacktrace:
```
   at NativeLibraryLoader.DefaultPathResolver.TryLocateNativeAssetFromDeps(String name, String& depsResolvedPath)
   at NativeLibraryLoader.DefaultPathResolver.<EnumeratePossibleLibraryLoadTargets>d__0.MoveNext()
   at NativeLibraryLoader.LibraryLoader.LoadNativeLibrary(String name, PathResolver pathResolver)
   at Veldrid.Sdl2.Sdl2Native.LoadSdl2()
   at Veldrid.Sdl2.Sdl2Native..cctor()
   at Veldrid.Sdl2.Sdl2Native.SDL_CreateWindow(String title, Int32 x, Int32 y, Int32 w, Int32 h, SDL_WindowFlags flags)
   at Veldrid.Sdl2.Sdl2Window..ctor(String title, Int32 x, Int32 y, Int32 width, Int32 height, SDL_WindowFlags flags, Boolean threadedProcessing)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindow(WindowCreateInfo& windowCI)
```

**Comment by mellinoe** [comment]
I think this will be fixed in the next version, because it looks like something I fixed along with this issue: #17 

Could you try running your program in 64-bit mode?

**Comment by parzivail** [comment]
Thank you for the speedy response! Specifically targeting x64 produces the same error. I tried targeting x86 too for good measure but it didn't seem to help either.

**Comment by parzivail** [comment]
I should note I'm targeting .NET 4.7.1

**Comment by mellinoe** [comment]
It seems that this issue only occurs if you are using packages.config rather than PackageReferences. There's an option to switch to it in the Options menu (assuming you're using VS):

![image](https://user-images.githubusercontent.com/8918977/34316237-7b6e9d4e-e745-11e7-8a75-00e6e055ea21.png)

I will investigate whether it's possible to support packages.config as well.

**Comment by parzivail** [comment]
Success! The combination of the PackageReferences instead of the .config and explicitly targeting x64 works great. Thanks for the help!

**Comment by mellinoe** [comment]
No problem!

It is technically possible to get it to work with packages.config, but I'd have to add custom build targets into the nuget package, which I'd like to avoid if at all possible. If a lot of people need to use packages.config for some reason (you really shouldn't need to though...), then I could reconsider. For the time being, PackageReference is the preferred solution.
