### ISSUE TITLE
Add support for Alpha to Coverage (Transparency MSAA)

### ISSUE THREAD

**Issue by omegachysis** [mellinoe/veldrid#191]
Thank you for the fantastic library. I have been using it for quite a bit over the last year. I have run into a roadblock though as my current project requires Alpha to Coverage because I'm using a forward renderer with a lot of foliage and MSAA and I want AA with alpha testing.

I believe all this needs in OpenGL is a call to `glEnable` with `GL_SAMPLE_ALPHA_TO_COVERAGE`. 
https://www.khronos.org/registry/OpenGL-Refpages/es1.1/xhtml/glEnable.xml

In Vulkan this can be done in `VkPipelineMultisampleStateCreationInfo` with `alphaToCoverageEnable`.
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPipelineMultisampleStateCreateInfo.html

Is there some way I can do this with the existing version or does Veldrid need an update to support this? I would be happy to help in some way but right now I'm on a Linux machine and I haven't been able to build Veldrid for some reason on .NET Core 3.0.

**Comment by mellinoe** [comment]
This seems like a pretty simple thing to support -- it's a single switch in all of the backends. You would need a new version of Veldrid to enable this. The flag would need to be exposed somewhere on `GraphicsPipelineDescription`, or one of its child objects (`BlendStateDescription`, maybe).

> Is there some way I can do this with the existing version or does Veldrid need an update to support this? I would be happy to help in some way but right now I'm on a Linux machine and I haven't been able to build Veldrid for some reason on .NET Core 3.0.

I will try to spend some more time fixing that. The problem (unless yours is different) is that a couple of the build configuration utilities I'm using aren't compatible with all Linux versions. They can be turned off, but then the assembly versions are wrong. That might not be a problem if you're just using a local build, but I'd like to figure out if I can fix that in a better way.

**Comment by mellinoe** [comment]
@omegachysis I added support for this in the [alpha-to-coverage](https://github.com/mellinoe/veldrid/tree/alpha-to-coverage) branch. You can now set `BlendStateDescription.AlphaToCoverageEnabled` to `true` to enable this for a Pipeline. I know that you're not able to build on Linux at the moment, so I will share the pre-release NuGet packages once they finish building in CI.

**Comment by mellinoe** [comment]
@omegachysis You should be able to try out the 4.7.0-g49047704f0 packages from MyGet to test this.

**Comment by omegachysis** [comment]
This is fantastic, thank you so much for your prompt and swift help! Alpha-to-coverage is a very powerful feature, so I'm very happy about this.

**Comment by omegachysis** [comment]
I tested it out, I can confirm the feature works on Linux with OpenGL. I don't really have the ability at the moment to test the other backends. My foliage textures look so much better now and I don't have to depth sort my geometry! Huzzah! Leaving this open for you to close if you wish. Thank you!

**Comment by mellinoe** [comment]
@omegachysis Sounds good. This is merged into master now, so I'll close this out. It will be included in the next stable release, and is in preview builds for the time being.
