### ISSUE TITLE
NeoDemo sample fails to enable RenderDoc when window recreation is disabled

### ISSUE THREAD

**Issue by SamVanheer** [mellinoe/veldrid#193]
Enabling RenderDoc will fail if the `Always Recreate Sdl2Window` option is disabled. This is because RenderDoc can only inject into newly created windows, not existing ones.

This code needs to force window recreation:
https://github.com/mellinoe/veldrid/blob/8a03f3a4a68277e9f3ce1b0762ddb4bf1cf3011a/src/NeoDemo/NeoDemo.cs#L395-L398

**Comment by mellinoe** [comment]
This should only be true if you are using OpenGL, since the GraphicsDevice/OpenGL context is tied to a window. Other backends shouldn't care if the window is recreated or not. So the logic could check whether OpenGL is currently being used and only recreate the window in that case.

**Comment by mellinoe** [comment]
Fixed on master. I am always recreating the window after loading RenderDoc now; it does seem to require that.
