### ISSUE TITLE
Interfaces not prefixed with I

### ISSUE THREAD

**Issue by IntelOrca** [mellinoe/veldrid#2]
I once worked on my own similar project:
https://github.com/IntelOrca/OrcaML

Which closely mirrored ASP.NET core using dependency injection as a means for selecting different components (e.g. OpenGL over DirectX).

I noticed that many of your interfaces are not prefixed with uppercase `I`, how come?

**Comment by IntelOrca** [comment]
> The lack of an I-prefix for interfaces is just a stylistic choice; there's no particular reason. I find it more straightforward and less obfuscated, personally. In reality, most of the usages in the library should be translated into abstract classes with internal constructors, because it is not feasible to provide an external implementation of them.

I think it will upset a lot of people if you don't stick to Microsoft's style guidelines. Having the I prefix makes it obvious that types are interfaces. I prefer interfaces to abstract classes, they have many more benefits. And if you look at modern coding practices done in e.g. ASP.NET core, you will see that extension methods are used more often to achieve non-implementation specific code.

> Thanks for the link. Your project is pretty interesting, particularly how you are handling shaders. Do you have anything written up about the approach?

I haven't written anything about the design. My idea was to create infrastructure where the uniforms and attributes for shaders are strongly typed and then compiled to GLSL or HLSL at runtime. And where possible laying out structs so that OpenGL and DirectX can block copy the memory efficiently from them. Another idea was for applications to only define interfaces for their shaders' uniforms and then have implementations compiled at runtime with backing properties that would record which uniforms were changed in order to minimise the number OpenGL state changes.

The current code I have in there allows you to compile shaders by writing a set of chainable C# method calls. But it ended up being a bit untidy. Expression trees would be better, but they don't offer loops etc.

**Comment by mellinoe** [comment]
I don't really have a goal to follow the Microsoft guidelines very closely, and I'm certainly not following them in a lot of other places. For example:

* I prefix fields with `_`, which is forbidden by the guidelines.
* I prefix static fields with `s_`, which is also forbidden.
* I try to never use `var`, although I frequently get lazy and use it anyways 😄 
* Various other little things.

I don't really want to get into a style war, but IMO adding the `I` prefixes would make things worse, for a few reasons, so I probably wouldn't switch it. It's pretty inconsequential in the grand scheme of things, especially if you consider how interfaces are used in the library. Anyways, like I said above, I would probably just switch them to be abstract classes for the most part if I were going to change anything there.

I think your concept for shaders is really intriguing. Do you have any examples of the actual generated code for some medium-complexity shaders using the approach? Also, have you seen whether it's possible to parse your shader object model out of an already-written shader somehow?

**Comment by IntelOrca** [comment]
> and I'm certainly not following them in a lot of other places. For example:

They don't matter so much as they not exposed externally.

**Comment by mellinoe** [comment]
I appreciate the interest in this, but right now I'm going to keep the library as it is. If others are really off-put by the style here, I will consider changing things.
