### ISSUE TITLE
(Ubuntu 17.10) Veldrid.VeldridException: The required instance extension was not available: Veldrid.Vk.FixedUtf8String

### ISSUE THREAD

**Issue by misnor** [mellinoe/veldrid#20]
Hi Mellinoe,

I am trying to give your framework a try (I'm **really** interested in true cross platform graphics with .NET core).

I have run into an issue during basic testing, specifically around [Part 1](https://mellinoe.github.io/veldrid-docs/articles/getting-started/getting-started-part1.html) in the documentation.

I've created a bare bones new console application and added nuget references to _Veldrid_ and _Veldrid.StartupUtilities_, then I used the finished example at the bottom to try and get a blank window to appear.

This works perfectly on Windows 10, however, I am having problems getting this to work on my Ubuntu System (17.10)

I did have some original issues with OpenGL and Vulkan, but those were due to missing dependencies on my system and got those cleared up.

Is there a chance i'm missing something else that may be causing this issue? I've dug around a bit but nothing jumped out at me.

I've also attached my project I was trying to use as well (even though its the same as the documentation code)
[VeldridTest.zip](https://github.com/mellinoe/veldrid/files/1617085/VeldridTest.zip)

And if there is anything else I can provide please let me know!

Full Exception:

```
misnor@SINIX:~/Documents/VeldridTest$ dotnet run

Unhandled Exception: Veldrid.VeldridException: The required instance extension was not available: Veldrid.Vk.FixedUtf8String
   at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug)
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, VkSurfaceSource surfaceSource, UInt32 width, UInt32 height)
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window)
   at VeldridTest.Program.Main() in /home/misnor/Documents/VeldridTest/Program.cs:line 24
```

**Comment by misnor** [comment]
Switching

`_graphicsDevice = VeldridStartup.CreateGraphicsDevice(window);`
to
`_graphicsDevice = VeldridStartup.CreateDefaultOpenGLGraphicsDevice(new GraphicsDeviceOptions(), window);` 

Makes it work, which seems to imply its a problem with Vulkan dependencies on my system?

**Comment by mellinoe** [comment]
Right now, the Vulkan backend requires the Vulkan Xlib extension (`VK_KHR_xlib_surface`) to be available. The error message is wrong -- it should print out that extension's name, not "Veldrid.Vk.FixedUtf8String" 😅. I've fixed that with the latest commit (https://github.com/mellinoe/veldrid/commit/da6721d9b471a419b97fd9d918ec6151e1e16b68)

> Makes it work, which seems to imply its a problem with Vulkan dependencies on my system?

Yes, that seems to be the most likely problem. On my Ubuntu machine, I have the following packages installed for Vulkan:

* libvulkan-dev
* libvulkan1
* vulkan-utils

I don't think all of those are necessary, but adding those could be a good start.

If you have the "vulkaninfo" program installed (it's in the vulkan-utils package), then seeing the output from it would be helpful. It prints out all of the available extensions and some other diagnostic info.

**Comment by mellinoe** [comment]
I made several changes to help detect when the system doesn't support Vulkan, and to avoid using it in those cases:

* There is a new method `GraphicsDevice.IsBackendSupported`, which lets you ask up front whether a backend is supported.
* The Vulkan backend checks two things to determine if it's supported:
  * Whether Vulkan functions were even successfully loaded
  * Whether the necessary extensions are available (`VK_KHR_surface` and the platform-specific surface extension).
* VeldridStartup now checks if Vulkan is supported before using it as the default backend on Linux. For you, it should automatically select OpenGL, unless you are able to get Vulkan drivers working for your system. Then it should just work with Vulkan.
* Mentioned above -- the Vulkan error message is correct now and actually prints out the missing extension's name.

**Comment by misnor** [comment]
I just pulled latest from master and ran the same code I attached above, and the blank window appeared and stayed - no crash. (I didn't install the missing Vulkan dependencies either)

Thank you for the quick turn around on that fix!

**Comment by mellinoe** [comment]
Sure thing! From what you've described, it's probably just defaulting to the OpenGL backend now, rather than trying to use Vulkan when it's not supported. You could possibly still get Vulkan to work, but it might involve fiddling with the packages on your system. Anyways, let me know if you have any more questions or concerns. Cheers!
