### ISSUE TITLE
IsBackendSupported fails on an android with no Vulcan support

### ISSUE THREAD

**Issue by gleblebedev** [mellinoe/veldrid#201]
Fails with ArgumentNullException at "path1" and the following stack:

 	0x3 in System.IO.Path.Combine	C#
 	0x29 in Vulkan.NativeLibrary.UnixNativeLibrary.LoadLibrary	C#
 	0x15 in Vulkan.NativeLibrary..ctor	C#
 	0x2 in Vulkan.NativeLibrary.UnixNativeLibrary..ctor	C#
 	0x2C in Vulkan.NativeLibrary.Load	C#
 	0x5 in Vulkan.VulkanNative.LoadNativeLibrary	C#
 	0xA in Vulkan.VulkanNative..cctor	C#
 	0x7 in Veldrid.Vk.VulkanUtil.TryLoadVulkan at C:\projects\veldrid\src\Veldrid\Vk\VulkanUtil.cs:148,17	C#
 	0x1E in System.Lazy<bool>.ViaFactory	C#
 	0x24 in System.Lazy<bool>.ExecutionAndPublication	C#
 	0x77 in System.Lazy<bool>.CreateValue	C#
 	0xB in System.Lazy<bool>.get_Value	C#
 	0x5 in Veldrid.Vk.VulkanUtil.IsVulkanLoaded at C:\projects\veldrid\src\Veldrid\Vk\VulkanUtil.cs:142,48	C#
 	0x0 in Veldrid.Vk.VkGraphicsDevice.CheckIsSupported at C:\projects\veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:1226,13	C#
 	0x1E in System.Lazy<bool>.ViaFactory	C#
 	0x24 in System.Lazy<bool>.ExecutionAndPublication	C#
 	0x77 in System.Lazy<bool>.CreateValue	C#
 	0xB in System.Lazy<bool>.get_Value	C#
 	0x5 in Veldrid.Vk.VkGraphicsDevice.IsSupported at C:\projects\veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:1221,13	C#
 	0x27 in Veldrid.GraphicsDevice.IsBackendSupported at C:\projects\veldrid\src\Veldrid\GraphicsDevice.cs:845,21	C#
>	0x3 in VeldridGlTF.Viewer.Android.VeldridSurfaceView.GetDefaultBackend at E:\MyWork\VeldridGlTF\src\VeldridGlTF.Viewer.Android\VeldridSurfaceView.cs:53,17	C#
 	0x1A in VeldridGlTF.Viewer.Android.VeldridSurfaceView..ctor at E:\MyWork\VeldridGlTF\src\VeldridGlTF.Viewer.Android\VeldridSurfaceView.cs:37,13	C#
 	0x27 in VeldridGlTF.Viewer.Android.MainActivity.OnCreate at E:\MyWork\VeldridGlTF\src\VeldridGlTF.Viewer.Android\MainActivity.cs:41,13	C#
 	0x13 in Android.App.Activity.n_OnCreate_Landroid_os_Bundle_	C#
 	0x17 in Android.Runtime.DynamicMethodNameCounter.4	C#

**Comment by mellinoe** [comment]
This should be fixed in the master branch now. If the system doesn't support Vulkan, it should return `false` instead of throwing an exception.
