### ISSUE TITLE
[Question] Write pixel block to frame buffer

### ISSUE THREAD

**Issue by bntre** [mellinoe/veldrid#204]
A clueless question.
How i know .NET Core 2.0 supports System.Drawing. 
Is it possible to draw some primitives to a memory bitmap (e.g. with System.Drawing.Graphics.DrawEllipse)
and then put the pixel data directly to veldrid frame buffer (something like "glDrawPixels") ?

**Comment by mellinoe** [comment]
There's nothing exactly like `glDrawPixels` built in to Veldrid. To accomplish this, you will need to create a Texture out of the System.Drawing Bitmap and then render that onto a quad with some simple shaders.
