### ISSUE TITLE
Android OpenGL ES crash when Texture has Name

### ISSUE THREAD

**Issue by gleblebedev** [mellinoe/veldrid#205]
Crash callstack:

0x0 in Veldrid.OpenGLBinding.OpenGLNative.glObjectLabel at C:\projects\veldrid\src\Veldrid.OpenGLBindings\OpenGLNative.cs:789,16    C#
     0x39 in Veldrid.OpenGL.OpenGLUtil.SetObjectLabel at C:\projects\veldrid\src\Veldrid\OpenGL\OpenGLUtil.cs:33,17    C#
     0x40 in Veldrid.OpenGL.OpenGLTexture.EnsureResourcesCreated at C:\projects\veldrid\src\Veldrid\OpenGL\OpenGLTexture.cs:188,21    C#
     0x8 in Veldrid.OpenGL.OpenGLCommandExecutor.UpdateTexture at C:\projects\veldrid\src\Veldrid\OpenGL\OpenGLCommandExecutor.cs:1085,13    C#
     0x1D3 in Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.ExecuteWorkItem at C:\projects\veldrid\src\Veldrid\OpenGL\OpenGLGraphicsDevice.cs:1184,29    C#
     0x21 in Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.Run at C:\projects\veldrid\src\Veldrid\OpenGL\OpenGLGraphicsDevice.cs:1115,21    C#
     0x1F in System.Threading.ThreadHelper.ThreadStart_Context    C#
     0x73 in System.Threading.ExecutionContext.RunInternal    C#
     0x4 in System.Threading.ExecutionContext.Run    C#
     0x2F in System.Threading.ExecutionContext.Run    C#
     0x14 in System.Threading.ThreadHelper.ThreadStart    C#

It only happened on one mobile device out of 2 I've tested, on older Android 6.0.1 phone.

**Comment by gleblebedev** [comment]
The glObjectLabel function is only available on OpenGL ES 3.2 and the phone has OpenGL ES 3.1. I guess the Veldrid code have to check if the function is available.

**Comment by mellinoe** [comment]
The code does already check if the "GL_KHR_debug" extension is available (which `glObjectLabel` is a part of), but I'll add extra checks in for this.

**Comment by gleblebedev** [comment]
Hmm... I can see GL_KHR_debug extension available on the device too.

**Comment by gleblebedev** [comment]
I've doublechecked it:

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.

So I guess there should be a check for version too.

**Comment by mellinoe** [comment]
I pushed a change to master that should address this. glObjectLabel usage is now guarded by a null check.
