### ISSUE TITLE
OpenGLCommandExecutor.cs has a wrong error message

### ISSUE THREAD

**Issue by gleblebedev** [mellinoe/veldrid#213]
File
veldrid/src/Veldrid/OpenGL/OpenGLCommandExecutor.cs

Lines
                            if (range.SizeInBytes < uniformBindingInfo.BlockSize)
                            {
                                string name = glResourceSet.Layout.Elements[element].Name;
                                throw new VeldridException(
                                    $"Not enough data in uniform buffer \"{name}\" (slot {slot}, element {element}). Shader expects at least {uniformBindingInfo.BlockSize} bytes, but buffer only contains {glUB.SizeInBytes} bytes");
                            }

The message should be 
...but buffer only contains {range.SizeInBytes} bytes...

**Comment by gleblebedev** [comment]
Although it works fine on the textured cube sample...

**Comment by gleblebedev** [comment]
I've updated the bug description.

**Comment by gleblebedev** [comment]
https://github.com/mellinoe/veldrid/pull/214

**Comment by mellinoe** [comment]
This should be fixed now. Thanks!
