### ISSUE TITLE
Help needed, Trying to create two quads 

### ISSUE THREAD

**Issue by FutureCake** [mellinoe/veldrid#217]
Hi, 

Disclaimer I am a complete newbie to doing graphics programming on such a low level. 
I am asking this here instead of stackoverflow since this is such a new library I think you guys have a bit more knowledge then SO. If I am wrong happy to move my question to there!

So here I go: 

I have been doing the getting started doc on the Veldrid website, and I managed to create a quad! So for the next challenge I was trying to create two quads. But I only see one of my quads appear. I am almost certain it has to do with me swapping the Vertexbuffer of the commandlist in the same frame to use the Vertices of my second quad. But i don't really understand how to do it in any other way. I have been trying to figure it out by digging through the NeoDemo project, but to be honest that confuses me even more :/  

See here a short hand piece of the code I tried: 

`// We want to render directly to the output window.
            _commandList.SetFramebuffer(graphicsManager.SwapchainFramebuffer);
			_commandList.ClearColorTarget(0, RgbaFloat.Black);

            // Set all relevant state to draw our quad.
            _commandList.SetVertexBuffer(0, _vertexBuffer);
            // here i swap to the other vertices buffer for my second quad. 
	    _commandList.SetVertexBuffer(4, _vertexBuffer2);
            _commandList.SetIndexBuffer(_indexBuffer, IndexFormat.UInt16);
            _commandList.SetPipeline(_pipeline);`

I hope anyone finds the time to help a newb like me :) 
I really like the idea of the library!

Thomas

**Comment by tzachshabtay** [comment]
Hard to answer without seeing the entire code, so some wild guesses:

Do you call 'DrawIndexed' before overriding the buffer (you should call it twice, once for each buffer)?

Are the buffer coordinates maybe the same so one overrides the other?

If you switch the order of drawing in the code, do you now see the second one instead of the first? This will tell you if the problem is in the workflow or in that specific quad.

**Comment by FutureCake** [comment]
@tzachshabtay Your guess was right :) I didn't call the DrawIndexed method before I updated the vertex buffer. Now I see two lovely quads! Thank you for your help, much appreciated!
