### ISSUE TITLE
Extending Sdl2Window

### ISSUE THREAD

**Issue by leafi** [mellinoe/veldrid#22]
Hi,

I've used Veldrid.Sdl2 & Veldrid.StartupUtilities - at least initially - for convenience's sake. (I'm more used to GLFW). I've stuck with them as they seem to be quite sufficient for what I need to do, and I like the Sdl2Window abstraction.

But I've got a few gripes with InputSnapshot; I'm integrating a GUI system into my project and timestamps for events seems important, so that if e.g. a mouse click and a key press comes in on the same frame I can tell whether the click (which may change focus) came before or after the key press. The InputSnapshot API precludes being able to figure this out.

I'd also like to get my claws into some of the joystick/controller events, which are just ignored atm. So I've been thinking about extensibility w.r.t. Sdl2Window more generally.

What are your thoughts on the following approaches:

- Adding an `Action<SDL_Event> handler` parameter to PumpEvents & ProcessEvents / `public event Action<SDL_Event> SDLEvent;` field to the class, and have this be called before the switch block inside the `while (SDL_PollEvent(&ev) != 0)` loop?
- Changing ProcessEvents to `protected virtual` & a bunch of private fields to `protected` accessibility, so it could be possible to override some of this behaviour
- Changing/Adding additional overloads in Veldrid.StartupUtilities.VeldridStartup.cs with `IntPtr sdlWindowHandle` in place of `Sdl2Window window` arguments, so it's easy to use a project-specific class that isn't Sdl2Window w/Veldrid.SU. (Would also need to add `int windowWidth`, `int windowHeight` arguments... bah)
- Possibly just exposing a kind of EventSnapshot that just has a list of the received SDL_Events in order?

The first option is IMO minimally invasive & my favourite option, but I'd like to hear your thoughts.

Thanks for your time (& for veldrid) :)

**Comment by mellinoe** [comment]
Hey @leafi, thanks for the thoughts. You have some good ideas, and I think that the extensibility could definitely be improved.

> Adding an Action<SDL_Event> handler parameter to PumpEvents & ProcessEvents / public event Action<SDL_Event> SDLEvent; field to the class, and have this be called before the switch block inside the while (SDL_PollEvent(&ev) != 0) loop?

Yeah, some way to simply expose the "raw" `SDL_Event` that is encountered as the window goes through the message pump is probably the most useful solution.

A "related" idea would be to just use a `List<SDL_Event>` somewhere and have it returned or filled up in some way when the window's events are being processed. Then you could iterate over it yourself. 

> Changing/Adding additional overloads in Veldrid.StartupUtilities.VeldridStartup.cs with IntPtr sdlWindowHandle in place of Sdl2Window window arguments, so it's easy to use a project-specific class that isn't Sdl2Window w/Veldrid.SU. (Would also need to add int windowWidth, int windowHeight arguments... bah)

The width/height should be queryable via `SDL_GetWindowSize`, so I think that should be fine. I agree that those overloads are definitely worth thinking about.

I'm really busy at the moment, so I may not start thinking about what the best option is until the weekend. Thanks for the ideas!

**Comment by mellinoe** [comment]
Hey @leafi, To me, option one still seems like the most reasonable. I put a simple version of it up here: https://github.com/mellinoe/veldrid/commit/c407e835e8210cd979a7e9c8d9abeac4a3b07c75

Ignore the "continuous resize" stuff. That's dead code from a while back.

The only thing I can think to change: should the callback take the `SDL_Event` parameter by-ref?

`public delegate void SDL_EventHandler(ref SDL_Event ev);`

**Comment by leafi** [comment]
Hey @mellinoe, sorry for the delay in getting back to you!

Yeah, that commit is perfect for my use cases :)

Re. `ref`... Given that SDL_Event is 56 bytes, and it's a struct so default assign semantics are copy semantics, I think making it a `ref` argument is probably a good idea.

You'd have to go out of your way (using `ref` again in user code) to accidentally retain a reference to this event that's about to be overwritten, but it likely makes sense to reduce by 1 the number of times the number of times this thing must be copied no matter what, given the rest of Veldrid. Even if Sdl2Window is just an 'ease of use' class.

**Comment by mellinoe** [comment]
I've added this new overload, with a ref-parameter delegate.  https://github.com/mellinoe/veldrid/commit/c1263c901c6c2e341851269d4d896255064fc3e7
