### ISSUE TITLE
question about editable shader properties 

### ISSUE THREAD

**Issue by FutureCake** [mellinoe/veldrid#230]
I am trying all the samples on the Veldrid samples page. And I have a question about shaders and shader properties that are editable during run time. In the getting started tutorial we create a quad with different colors at each vertex. When I change the color property during runtime of a vertex i see it change  yay! 

But now i have to define all the information i want to change on a per vertex basis. So let's say i have a shader property called transparency.  And it is the same for each vertex and i want to change all vertices at once do i still have to loop over all vertices and change the transparency setting per vertex? Or is there a way to change the property once for all vertices? Because if i have many properties all the same per vertex it would get quite tedious? Or if i have many vertices i will have to loop over all to change a single property that is the same for all vertices? Which i guess isn't super efficient, right? 

I am very new to graphics programming on such a basic level, so sorry if this question makes no sense whats so ever.. I am happy to clarify anything that is unclear. 

I am asking this question here and not on stackoverflow because this has to do more with how veldrid works than me not understanding a piece of code or how to implement a piece of code :)

Thanks in advance!

**Comment by mellinoe** [comment]
What you are looking for is a "uniform buffer". A really basic form of this is used in the [TexturedCube](https://github.com/mellinoe/veldrid-samples/blob/master/src/TexturedCube/Application/TexturedCube.cs#L192-L205) sample, but they are used in pretty much every example and most every useful shader will include some uniform information. In the TexturedCube shader, the same 3 matrices are used to transform every vertex in the mesh. I would start there and see if any other questions pop up. There are also a variety of resources on the subject online if you search for "uniform buffer", or "constant buffer" (D3D parlance)

**Comment by FutureCake** [comment]
Hi again,

Thanks for the great explanation of last time :) 
But I have an other question probably related but I can't seem to figure it out.. 
I have managed to change properties now of Vertex shaders! 
But now I am looking how to change properties of Fragment shaders. Like setting a boolean value during runtime of this shader, changing some float value etc so the shader gets a different appearance. How would I go about this? 

I couldn't really find any examples on how to do this in Veldrid. If you could give me some pointers (or example) that would be awesome!

Thanks in advance again  :)
