### ISSUE TITLE
Veldrid<>ImGuiNET sample

### ISSUE THREAD

**Issue by enquel** [mellinoe/veldrid#231]
Hi,
I would love to know how to create a Veldrid context inside of Imgui window. Should I make a new device, and push framebuffers texture to ImGui image? What about event handling, if I want to interact with window contents?

**Comment by mellinoe** [comment]
Hey @enquel. I think what you're asking (correct me if I'm wrong) is how to render a rendered Framebuffer into an `ImGui.Image` call. Basically the process is:

1. Create the Veldrid Texture(s) and Framebuffer object
2. Render into it
3. Call `GetOrCreateImGuiBinding` to get an IntPtr
4. Pass the IntPtr to ImGui.Image
5. Render as normal.

**Comment by enquel** [comment]
Hi @mellinoe ,
Thank you very much for explanation. Yes, I want to render 3D output to a render texture to be presented inside ImGui window. This is more or less what I was trying to achieve, unfortunately my knowledge of low-level 3D graphics API is poor. I assumed I needed a separate window/gd/pipeline for this, but now that I think of it, I don't, right? So I used graphics device that already existed, but ran into another problem : when I try to create ImGui binding, I get the exception:

Veldrid.VeldridException: 'To create a TextureView, the target texture must have either Sampled or Storage usage flags.'

But then again, I thought the texture should be set to RenderTexture? This is a resource setup I use for (trying) to render a texture (most of this is from getting started secion of Veldrid - I only added new dedicated Framebuffer). Also, do I need to call UpdateTexture on the render texture?

`
        private void CreateResources(GraphicsDevice _gd)
        {
            ResourceFactory factory = _gd.ResourceFactory;

            VertexPositionColor[] quadVertices =
            {
                new VertexPositionColor(new Vector2(-.75f, .75f), RgbaFloat.Red),
                new VertexPositionColor(new Vector2(.75f, .75f), RgbaFloat.Green),
                new VertexPositionColor(new Vector2(-.75f, -.75f), RgbaFloat.Blue),
                new VertexPositionColor(new Vector2(.75f, -.75f), RgbaFloat.Yellow)
            };

            ushort[] quadIndices = { 0, 1, 2, 3 };

            _vertexBuffer = factory.CreateBuffer(new BufferDescription(4 * VertexPositionColor.SizeInBytes, BufferUsage.VertexBuffer));
            _indexBuffer = factory.CreateBuffer(new BufferDescription(4 * sizeof(ushort), BufferUsage.IndexBuffer));

            _graphicsDevice.UpdateBuffer(_vertexBuffer, 0, quadVertices);
            _graphicsDevice.UpdateBuffer(_indexBuffer, 0, quadIndices);

            VertexLayoutDescription vertexLayout = new VertexLayoutDescription(
                new VertexElementDescription("Position", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float2),
                new VertexElementDescription("Color", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float4));

            ShaderDescription vertexShaderDesc = new ShaderDescription(
                ShaderStages.Vertex,
                Encoding.UTF8.GetBytes(VertexCode),
                "main");
            ShaderDescription fragmentShaderDesc = new ShaderDescription(
                ShaderStages.Fragment,
                Encoding.UTF8.GetBytes(FragmentCode),
                "main");

            _shaders = factory.CreateFromSpirv(vertexShaderDesc, fragmentShaderDesc);

            GraphicsPipelineDescription pipelineDescription = new GraphicsPipelineDescription();
            pipelineDescription.BlendState = BlendStateDescription.SingleOverrideBlend;

            pipelineDescription.DepthStencilState = new DepthStencilStateDescription(
                depthTestEnabled: true,
                depthWriteEnabled: true,
                comparisonKind: ComparisonKind.LessEqual);

            pipelineDescription.RasterizerState = new RasterizerStateDescription(
                cullMode: FaceCullMode.Back,
                fillMode: PolygonFillMode.Solid,
                frontFace: FrontFace.Clockwise,
                depthClipEnabled: true,
                scissorTestEnabled: false);

            pipelineDescription.PrimitiveTopology = PrimitiveTopology.TriangleStrip;
            pipelineDescription.ResourceLayouts = System.Array.Empty<ResourceLayout>();

            pipelineDescription.ShaderSet = new ShaderSetDescription(
                vertexLayouts: new VertexLayoutDescription[] { vertexLayout },
                shaders: _shaders);


            mTexture = _graphicsDevice.ResourceFactory.CreateTexture(TextureDescription.Texture2D(256, 256, 1, 1, PixelFormat.R8_G8_B8_A8_UInt, TextureUsage.RenderTarget));
            
            FramebufferAttachmentDescription fbad = new FramebufferAttachmentDescription();
            fbad.Target = mTexture;
            FramebufferDescription fbd = new FramebufferDescription();
            fbd.ColorTargets = new FramebufferAttachmentDescription[1];
            fbd.ColorTargets[0] = fbad;

            mFb = factory.CreateFramebuffer(fbd);

            pipelineDescription.Outputs = mFb.OutputDescription;
           
            _pipeline = factory.CreateGraphicsPipeline(pipelineDescription);

            testPtrRndr = Application.mManagerWindow._controller.GetOrCreateImGuiBinding(_graphicsDevice.ResourceFactory, mTexture);
        }


        public void Draw(CommandList _commandList)
        {
            // Begin() must be called before commands can be issued.
            _commandList.Begin();

            // We want to render directly to the output window.
            
            _commandList.SetFramebuffer(mFb);
            _commandList.ClearColorTarget(0, RgbaFloat.Black);

            // Set all relevant state to draw our quad.
            _commandList.SetVertexBuffer(0, _vertexBuffer);
            _commandList.SetIndexBuffer(_indexBuffer, IndexFormat.UInt16);
            _commandList.SetPipeline(_pipeline);
            // Issue a Draw command for a single instance with 4 indices.
            _commandList.DrawIndexed(
                indexCount: 4,
                instanceCount: 1,
                indexStart: 0,
                vertexOffset: 0,
                instanceStart: 0);

            // End() must be called before commands can be submitted for execution.
            _commandList.End();
            _graphicsDevice.SubmitCommands(_commandList);

            // Once commands have been submitted, the rendered image can be presented to the application window.
            _graphicsDevice.SwapBuffers();
        }
    }
`


Could you point me in the right direction?

**Comment by mellinoe** [comment]
You can create a Texture with multiple `TextureFlags`. In this case you can use both `Sampled` and `RenderTarget`.

**Comment by enquel** [comment]
@mellinoe thank you very much. This allowed me to execute the code, but yields no result, as if the texture weren't there.(I also tried copying the render texture to staging texture and then mapping the texture and getting the mapped data to create ImGui pointer - but also this gives empty texture). Do I need to update the Render Texture manually as well?

**Comment by enquel** [comment]
All works fine, thank you very much for assistance!
