### ISSUE TITLE
Vulkan surface never gets disposed

### ISSUE THREAD

**Issue by bootzin** [mellinoe/veldrid#234]
In [this](https://github.com/mellinoe/veldrid/blob/f963bdcccbb3ecd8de8d9ae62cd72b33ab5ff21f/src/Veldrid/Vk/VkGraphicsDevice.cs#L115) line of code, you create a surface that never gets properly disposed. That leads to a `VkSurfaceKHR not destroyed` message when trying to dispose of a VkGraphicsDevice

**Comment by JulienNoble** [comment]
Can reproduce systematically on disposing my vulkan backend app : on device dispose, the vk instance destroy doesn't throw but still informs me that the surface hasn't been destroyed as an error.

```
VUID-vkDestroyInstance-instance-00629(ERROR / SPEC): msgNum: 0 - OBJ ERROR : For VkInstance 0x225f6940f20[], VkSurfaceKHR 0xf8ce070000000002[] has not been destroyed. The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying instance (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyInstance-instance-00629)
    Objects: 1
        [0] 0xf8ce070000000002, type: 1000000000, name: NULL
```

**Comment by mellinoe** [comment]
This should be fixed by https://github.com/mellinoe/veldrid/commit/31e3f023ec47cbb51a6009de111b78c5bcc44251
