### ISSUE TITLE
Equivalent of glEnable(GL_FRAMEBUFFER_SRGB)

### ISSUE THREAD

**Issue by TJYSunset** [mellinoe/veldrid#243]
Sorry if I asked a stupid question, but does veldrid offer an option to render in SRGB color space (as in `glEnable(GL_FRAMEBUFFER_SRGB)`) other than performing gamma correction in shaders? I saw SRGB support was mentioned in in #41 and several branches' names - is it already implemented?

**Comment by mellinoe** [comment]
If you create a Texture with some SRGB-suffixed format (for example, `PixelFormat.R8_G8_B8_A8_UNorm_SRgb`), then any Framebuffer rendering to that Texture will automatically do the expected SRGB conversions for you. This is already implemented as of [version 4.5.0](https://veldrid.dev/updates/4.5.0.html#srgb-textures)
