### ISSUE TITLE
[OpenGL] [Bug] ClearColorTarget doesn't reset the color attachments

### ISSUE THREAD

**Issue by Doom2fan** [mellinoe/veldrid#251]
`OpenGLCommandExecutor.ClearColorTarget` calls `glDrawBuffers` to limit which colour target gets cleared, but doesn't reset it afterwards, which makes it so only that target gets rendered to.

From some simple testing, it seems this bug can be fixed by simply adding this snippet of code to the end of that function:
```CSharp
    if (!_isSwapchainFB)
    {
        int colorCount = _fb.ColorTargets.Count;
        DrawBuffersEnum* bufs = stackalloc DrawBuffersEnum[colorCount];
        for (int i = 0; i < colorCount; i++)
        {
            bufs[i] = DrawBuffersEnum.ColorAttachment0 + i;
        }
        glDrawBuffers((uint)colorCount, bufs);
        CheckLastError();
    }
```

**Comment by mellinoe** [comment]
Hey @Doom2fan sorry that you've hit this issue, and thanks for looking into it. Are you able to submit a pull request with that fix in it?
