### ISSUE TITLE
NeoDemo on Vulkan in debug mode crashes with a validation error

### ISSUE THREAD

**Issue by Perksey** [mellinoe/veldrid#254]
- Can be reproduced on `master` as of 22/02/2020
- NVIDIA RTX 2060 Founders
- Driver Version: NVIDIA Studio Driver 442.19 (release date 02/03/2020)
```
 [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ]
Object: 0x1f4d770d520 (Type = 6) |
Submitted command buffer expects VkImage 0x3ba5830000000006[]
(subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout
VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL--instead, current layout
is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR.
```

**Comment by mellinoe** [comment]
I can repro this with your validation layer version (SDK 1.1.121.2), but no warnings or errors are triggered with the latest SDK.

**Comment by sboron** [comment]
Issue is still there. Also with an newer sdk.

**Comment by sboron** [comment]
Thats how i get the error. 1 Main Thread, 2 Sub threads

Main thread calls:
![image](https://user-images.githubusercontent.com/76991284/154863579-d222b2c1-4cc8-41c4-aaef-53c36f5090fa.png)
Sub thread 1 and subthread 2 calls:
![image](https://user-images.githubusercontent.com/76991284/154863588-2ec29a54-d2ca-4259-9202-6a3b4ae83a7a.png)

**Comment by sboron** [comment]
And here the complete error:

[ErrorEXT] (QueueEXT) Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01296 ] Object 0: handle = 0x263f7f15810, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xc7aabc16 | vkQueuePresentKHR(): pSwapchains[0] images passed to present must be in layout VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR but is in VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout at the time the operation is executed on a VkDevice (https://github.com/KhronosGroup/Vulkan-Docs/search?q=)VUID-VkPresentInfoKHR-pImageIndices-01296)

![image](https://user-images.githubusercontent.com/76991284/154863686-04751621-65d8-4056-9663-f62e046b6f92.png)
