### ISSUE TITLE
wrong image width height in linux

### ISSUE THREAD

**Issue by godshades** [mellinoe/veldrid#264]
### Description
Hi, my project running .net core 2.0 and lastest ImageSharp 4.7.0
I use ImageSharp to get width heigh of image
It's running fine in window pc, but when I publish to aws server it's alway return wrong size
I try publish many times but not work
Does someone have same problem ?
( I was used System.common dll from MS but aws can't install gdiplus so not work...)

### Steps to Reproduce
Code:

```
private string ProcessUrl(string url)
{
	var req = (HttpWebRequest)WebRequest.Create(url);
	var response = (HttpWebResponse)req.GetResponse();
	using (Stream stream = response.GetResponseStream())
	{
		var img = Image.Load(stream);
		string size = img.Width.ToString() + "x" + img.Height.ToString() ;
	}
	return size ;
}
```

Input URL: https://internal.codenet.fointl.com/product/f.o.online/V249070/V249070_sub01_2.jpg
When I running on visual studio for window it return: 750x750
But when I deploy Linux return: 1800x1800
Here is my publish profile:
![image](https://user-images.githubusercontent.com/12244851/77383226-f75f9a00-6db4-11ea-80ae-894925b14c11.png)

### System Configuration

- ImageSharp version: 4.7.0
- Environment (Operating system, version and so on): Window 10 x64 and Amazon Linux AMI
- .NET Framework version: .net core 2.0

**Comment by mellinoe** [comment]
Hey @godshades, it doesn't look like this is related to Veldrid. You may want to post this over in the ImageSharp repo instead.
