### ISSUE TITLE
OpenGL - ResourceSet binding bug

### ISSUE THREAD

**Issue by itayronen** [mellinoe/veldrid#278]
Seems that OpenGL has a bug binding resource set elements to the correct slots.
I have a `Camera Resourse Set` holding:
- Projection matrix
- View matrix
- Camera position

Vulkan works as expected.
D3D11 has a known bug in resource set binding (https://github.com/mellinoe/veldrid/issues/276).

On OpenGL:
- When I place the camera position 3rd in the resource set, bindings slots seems incorrect.
- When I bind it 1st, it works.

### Camera position - Bounded 3rd (not working):
```glsl
#version 450

layout(set = 0, binding = 0) uniform ProjectionBuffer { mat4 Projection; };
layout(set = 0, binding = 1) uniform ViewBuffer { mat4 View; };
layout(set = 0, binding = 2) uniform CenterPositionBuffer { vec3 CenterPosition; };

// Irrelevant but just in case you think it may affect:
layout(set = 2, binding = 0) uniform GridSizesBuffer { vec3 GridSizes; };
layout(location = 0) in vec3 ParticleGridOrigin;
layout(location = 1) in vec2 Position;
layout(location = 0) out vec2 outPosition;
layout(location = 1) out float outSalt;

void main()
{
...
```

![image](https://user-images.githubusercontent.com/21139000/80864273-45a46a80-8c8a-11ea-90ef-cbbbbf133476.png)

### Camera position - Bounded 1st (working):
```glsl
#version 450

layout(set = 0, binding = 1) uniform ProjectionBuffer { mat4 Projection; };
layout(set = 0, binding = 2) uniform ViewBuffer { mat4 View; };
layout(set = 0, binding = 0) uniform CenterPositionBuffer { vec3 CenterPosition; };

// Irrelevant but just in case you think it may affect:
layout(set = 2, binding = 0) uniform GridSizesBuffer { vec3 GridSizes; };
layout(location = 0) in vec3 ParticleGridOrigin;
layout(location = 1) in vec2 Position;
layout(location = 0) out vec2 outPosition;
layout(location = 1) out float outSalt;

void main()
{
...
```
![image](https://user-images.githubusercontent.com/21139000/80864365-cf543800-8c8a-11ea-8f5a-c1fe4b0ab151.png)

Same if I put it 2nd.
In both cases (3rd and 2nd) it "merges" with the projection in slot 0.

I don't know why the order affects anything.
I tried allocating the buffer in different order.
I tried making the camera position buffer size 64.

**Comment by mellinoe** [comment]
Can you paste the code that defines the ResourceLayout in your code? Note that in the OpenGL/ES backends, resources are matched strictly by name, so the strings need to be exactly the same.

**Comment by itayronen** [comment]
```cs
var layoutDesc = new ResourceLayoutDescription(this.elementsLayouts.ToArray());

ResourceLayout layout = factory.CreateResourceLayout(layoutDesc);
layout.Name = name + " layout";

ResourceSetDescription resourceSetDescription = new ResourceSetDescription(layout, this.resources.ToArray());

var resource = factory.CreateResourceSet(resourceSetDescription);
```
Those are the values in runtime:
![image](https://user-images.githubusercontent.com/21139000/81000614-34f12180-8e4f-11ea-98bf-d526ccd9ed00.png)

**Comment by mellinoe** [comment]
The name in the third description ("CameraPositionBuffer") doesn't match what you have in your shader ("CenterPositionBuffer"). These need to match exactly in order for the resource to bind correctly.

**Comment by itayronen** [comment]
Oh I understand. Thank you!
Is it an OpenGL backend limitation that is going to stay?
In this case it's probably not a bug, although I find it confusing that I must sync my shaders and buffer names (and only for OpenGL backend).
It collides with the concept of explicit `set` and `binding`.

**Comment by itayronen** [comment]
Just for documentation, maybe others will find it useful:
- In my project I bind the uniforms to the shader parameters dynamically in code (I change the shader text in runtime).
- On non-OpenGL backends, I have one layout per resource (uniform buffer or resource set), and it is used in all the pipelines using this resource, because they don't affect the binding.
- Only on OpenGL backend, for each pipline I regenerate each resource layout, making each `ResourceLayoutElementDescription`'s name match the shader parameters name. This way I avoid the limitation described in the issue.

**Comment by mellinoe** [comment]
Sorry about the delayed reply.

> Is it an OpenGL backend limitation that is going to stay?

Yes, I intend for this behavior to stay, with the caveat that I may add some optional coupling to allow Veldrid.SPIRV to handle naming problems for you automatically, if you use that library to manage your shaders.

Other abstractions tend to handle this by forcing you to use a particular shading language, or a particular compiler toolchain (which handle naming variables according to some convention automatically). Veldrid takes a different approach, and allows you to pass in any valid GLSL, but in exchange requires you to specify a little bit more about how the resources are defined.

I'm having a little trouble understanding why you need to specially handle the OpenGL backend for your use case. `ResourceLayoutElementDescription.Name` is effectively ignored outside of OpenGL, so there's no harm in setting that to the correct name for every backend.

**Comment by itayronen** [comment]
I use the same resources in multiple pipelines (and shaders).
In other backends I use the same `ResourceLayout`.
In openGL I can't unless I sync all the names between the shaders (GLSL code) and pipelines.

**Comment by mellinoe** [comment]
I think this was answered sufficiently above. If you are doing modifications to your GLSL code specifically (and not to any other shader code), you may need some adjustments to the corresponding `ResourceLayoutElementDescription`s. Other than that, there is no reason the `Name` for each element can't be specified for every backend.
