### ISSUE TITLE
Calling CommandList.SetVertexBuffer with a null DeviceBuffer throws a NullReferenceException

### ISSUE THREAD

**Issue by tgjones** [mellinoe/veldrid#29]
I'm trying to do this:

``` csharp
commandList.SetVertexBuffer(1, null);
```

in order to clear any previously-set buffers for that slot. But both `CommandList.SetVertexBuffer` and the derived implementations of `CommandList.SetVertexBufferCore` expect the `buffer` argument to be non-null.

Is this by-design, or a bug? If it's a bug I can create a PR to fix it. If it's by-design, is there a better way to do what I'm trying to do?

I suppose that what I'm trying to do is actually unnecessary, as long as the current pipeline doesn't reference a vertex buffer in that slot (and if it did I should be setting a non-null buffer anyway), but it doesn't feel right to leave the old buffer lying around.

**Comment by mellinoe** [comment]
This is by-design. You don't need to un-bind the buffers that aren't used by the current Pipeline -- they are just ignored.

I guess the proper thing to do here is
1. Document this behavior, so it's less surprising
2. Throw an exception when a null buffer is passed (perhaps referencing the behavior)

**Comment by tgjones** [comment]
Okay, that makes sense. I guess it's best practice not to unbind vertex buffers.

My only thought was around garbage collection - a vertex buffer *might* (unlikely) end up still referenced by a command list, long after it was last used. But that's a very minor concern.

**Comment by mellinoe** [comment]
I added an extra note in the XML doc for this method which hopefully will help explain the behavior.
