### ISSUE TITLE
Unable to load SDL2.dll when moving the output dir of Veldrid

### ISSUE THREAD

**Issue by RoyAwesome** [mellinoe/veldrid#293]
So, I have a bit of a weird use case. 

I have Veldrid in a "Renderer" module that exists it it's own folder that I am changing the output dir in the project file into a Renderers/ folder.  

I have traced the bug down to the NativeLibraryLoader dependency searching for the native sdl2.dll file in the Application's base directory, rather than the location of the veldrid renderer.  This leads to Veldrid throwing an exception on startup unable to find the sdl library.

**Comment by mellinoe** [comment]
I think I understand your scenario, but I'm not sure how to fix it in general or automatically. What you could do is force SDL2 to load from a particular place in your code, before you call into Veldrid.SDL2 (or use Veldrid.StartupUtilities, etc.). Something like this should work:

```C#
// Force SDL2 native library to load from a non-standard location.
new NativeLibrary("my/custom/sdl2/path");

// Regular startup code. Veldrid.SDL2 will use the pre-loaded SDL2 binary.
```
