### ISSUE TITLE
Sdl2Window.Resized blocking thread

### ISSUE THREAD

**Issue by ScottKane** [mellinoe/veldrid#303]
I'm printing a log message on every frame with the window width, height and delta time. On resize I'm logging that the resize happened.

When I start resizing the window my logging from the main loop stops until I stop resizing, at that point I get 2 resize happened logs and the main loop resumes. The same thing happens (main loop is blocked) when I move the window via title bar.

Is there some way to configure if the resized callback is invoked repeatedly?

**Comment by ScottKane** [comment]
Nobody feel like commenting on this?

**Comment by mellinoe** [comment]
I think it will take someone more knowledgeable about the low-level workings of SDL2 to get this working. I've tried various things over the years to get continuous resizing to work, but haven't figured it out.

**Comment by zaafar** [comment]
(I am not an expert) but isn't it the OS/SDL_window itself blocking the infinite while loop thread during resizing? Is this something we can do with any other window e.g. WPF window?

**Comment by ScottKane** [comment]
Sorry I assumed it was a bug as I had previously been using Silk.NET which manages to create a window that doesn't block the thread on resize

**Comment by zaafar** [comment]
I am curious in understanding how does Silk.NET manages it.
Kindly point me to one of their sample project which I can download/compile & study. :)

**Comment by ScottKane** [comment]
These are the samples they currently have available: https://github.com/Ultz/Silk.NET/tree/master/examples/CSharp

I would look at: https://github.com/Ultz/Silk.NET/blob/master/examples/CSharp/Tutorial%201.2%20-%20Hello%20quad/Program.cs

Under Main they have:

``` c#
window.Load += OnLoad;
window.Render += OnRender;
window.Update += OnUpdate;
window.Closing += OnClose;
```

If you want to see resize working add the following to Main:

``` c#
window.Resize += OnResize;
```
And create the following method:
``` c#
private void OnResize()
{
    Console.WriteLine("Resizing"); // or something so you know the thread isn't blocked
}
```

This should at least demonstrate the functionality.

**Comment by bjth** [comment]
Silk.NET uses GLFW rather than SDL2. 
Resizing blocking the main thread seems to be an outstanding bug in SDL2 [Source](https://bugzilla.libsdl.org/show_bug.cgi?id=2077)

**Comment by mellinoe** [comment]
Since this is an issue in SDL2 rather than Veldrid, I'm going to close this. Note that Veldrid CAN be used with other window systems, it's just the StartupUtilities helpers that are designed around SDL2 for simplicity.
