### ISSUE TITLE
NeoDemo (intermittently) failing to close gracefully

### ISSUE THREAD

**Issue by zaafar** [mellinoe/veldrid#305]
On the latest code (99f48fc1fd4a0698d136799d727e7ad2ea17b9a7), NeoDemo is throwing an exception intermittently  (more common when running in debug mode) when closing the NeoDemo application. Following is the screenshot of the exception message.

<img src="https://i.imgur.com/dyBHLmA.png" width="500px">

Another example of this issue.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SharpGen.Runtime.ComObject.Release()
   at SharpGen.Runtime.ComObject.Dispose(Boolean)
   at SharpGen.Runtime.DisposeBase.CheckAndDispose(Boolean)
   at Veldrid.D3D11.D3D11GraphicsDevice.PlatformDispose()
   at Veldrid.GraphicsDevice.Dispose()
```

Sorry, couldn't provide any more details since it's rare.

**Comment by zaafar** [comment]
Since the failure is in disposing Vortice.Windows objects. Not sure if we should track this failure over here or in https://github.com/amerkoleci/Vortice.Windows repository. Kindly suggest @amerkoleci

**Comment by amerkoleci** [comment]
Can you provide how to reproduce the issue?

**Comment by zaafar** [comment]
Unfortunately, at this point in time, I have not been able to figure out the steps to deterministically reproduce the issue. All I know is that if I start/terminate NeoDemo application repeatedly (default settings/no code/config change), I will hit this issue 1 in 20 times.

I am not sure if something is wrong in my graphic-card driver or my windows OS or in Vortice library.
Windows Version: 10.0.19041 Build 19041
Nvidia Driver Version: 452.06
NeoDemo Commit id: 99f48fc1fd4a0698d136799d727e7ad2ea17b9a7

**Comment by amerkoleci** [comment]
Vortice.Windows https://github.com/amerkoleci/Vortice.Windows/blob/master/src/Vortice.DXGI/IDXGIDevice.cs#L26 stores and releases reference to IDXGIAdapter, will release PR soon with fix.

**Comment by zaafar** [comment]
Thank you for your time and for working with the limited information I provided. (after office/work) I will pull your branch and test it on my side too.

**Comment by zaafar** [comment]
tried 20  times on your branch, no issue (which isn't the case on master branch)
So thanks!! :)

**Comment by amerkoleci** [comment]
Glad to hear that, lets wait for Eric to merge it
