### ISSUE TITLE
SetPipeline,Multiple this functions are used,Why is the last pipeline always rendered on top,Cover up the old ones，even if the depth test is turned on

### ISSUE THREAD

**Issue by MiaoYue188** [mellinoe/veldrid#309]
//main draw
public void Draw()
        {
            Commands.Begin();

            Commands.SetFramebuffer(Device.SwapchainFramebuffer);
            Commands.SetFullViewports();
            Commands.ClearColorTarget(0, RgbaFloat.CornflowerBlue);
            Commands.ClearDepthStencil(1f);

            CoordinateSysDraw?.Invoke();
            ModelDraw?.Invoke();

            Commands.End();

            Device.SubmitCommands(Commands);
            Device.SwapBuffers();
        }

//bound to action CoordinateSysDraw
public override void Draw()
        {
            vdEngine.Commands.SetPipeline(_pipeline);
            vdEngine.Commands.ClearDepthStencil(1f);
            vdEngine.Commands.SetGraphicsResourceSet(0, _resourceSet);
            vdEngine.Commands.SetVertexBuffer(0, _positionBuffer);
            vdEngine.Commands.SetVertexBuffer(1, _colorBuffer);
            vdEngine.Commands.SetIndexBuffer(_indexBuffer, IndexFormat.UInt32);
            vdEngine.Commands.DrawIndexed(_indexCount, 1, 0, 0, 0);
        }

//Pipeline  definition
public void updatePipelineToTriangle()
        {
            GraphicsPipelineDescription mirrorPD = new GraphicsPipelineDescription(
                BlendStateDescription.SingleOverrideBlend,
                DepthStencilStateDescription.DepthOnlyLessEqual,
                new RasterizerStateDescription(FaceCullMode.None, PolygonFillMode.Solid, FrontFace.Clockwise, true, false),
                PrimitiveTopology.TriangleList,
                shaderSet,
                new[] { _resourceLayout },
                vdEngine.Device.SwapchainFramebuffer.OutputDescription);
            _pipeline = vdEngine.Factory.CreateGraphicsPipeline(ref mirrorPD);
        }

**Comment by mellinoe** [comment]
@MiaoYue188 Could you provide a little bit more information about what isn't working for you? It's not clear from the code what the problem is. You should be able to use multiple pipelines and have everything respect the depth buffer, assuming it is configured properly.

**Comment by mellinoe** [comment]
Needs more information, please re-open with more details if this is still a problem.
