### ISSUE TITLE
[OpenGL] Redundant calls to vertex layout setup code when pipeline and/or vertex buffer hasn't changed

### ISSUE THREAD

**Issue by RaZeR-RBI** [mellinoe/veldrid#312]
When making multiple draw calls without changing pipeline or currently bound vertex buffers the command executor seems to be pushing out glBindBuffer and glVertexAttrib* calls before each draw call despite that there is no need to do so (if I understand correctly).

Here is how it looks in a trace:

<details>
<summary>Trace screenshot</summary>

![Screenshot](https://i.imgur.com/fMz5kes.png)
</details>

[Relevant code is here](https://github.com/mellinoe/veldrid/blob/cdfaa674f069875e2c7758c01681ca20548f04b3/src/Veldrid/OpenGL/OpenGLCommandExecutor.cs#L255).

Seems like a simple solution to this would be making a boolean flag indicating whether we should update the vertex layouts and reset it at SetVertexBuffer(...) and SetPipeline(...), and do a flush in the PreDraw() method only if this flag is set.

I do have a patch ready and can send you a pull request if you don't mind. Of course, if I'm correctly understanding how this works and only if this change wouldn't break anything :wink:

<details>
<summary>Trace after the patch</summary>

![Screenshot](https://i.imgur.com/ucNsXoj.png)
(not sure why glGetError calls are not present in the first trace though)
</details>

Best regards!

**Comment by mellinoe** [comment]
Hey @RaZeR-RBI This is definitely just an oversight, or a regression introduced at some point. Feel free to submit the patch, as long as all of the tests in the project continue passing.
