### ISSUE TITLE
[Question] Batch Rendering

### ISSUE THREAD

**Issue by bootzin** [mellinoe/veldrid#314]
Hello
I'm trying to implement Batch Rendering using Veldrid, and I'd like to ask a question regarding vertex buffers

If I update a vertex buffer with my data and call cl.DrawIndexed(indexCount, 1, 0, 0, 0), can I modify the data in the vertex buffer and call DrawIndexed again?

I'm asking this because I'm currently updating my vertex buffer with some data and drawing (first batch). Then, I change that data with info regarding the next batch and update/draw the next batch. The problem is, only the last batch is being rendered (do note that I don't call cl.End() nor gd.SubmitCommands(cl) in between, but I tried doing this and it didn't change much)

So, what is the proper way of doing this? Is there any examples of batch rendering using veldrid? I know there is one for instancing, but that's not what I'm looking for

---EDIT---
I have the (partial) code available [here](https://github.com/bootzin/BootEngine/blob/c3a3dc0773f8ace18c21717014b15281b3f61740/BootEngine/BootEngine/Renderer/Renderer2D.cs#L305), if you're interested

**Comment by mellinoe** [comment]
`GraphicsDevice.UpdateBuffer` updates the contents of the buffer "immediately", and thus can't be used to update a single buffer more than once for a stream of draw calls (which are executed asynchronously on the GPU). `CommandList.UpdateBuffer` exists for this purpose: the data is not uploaded into the buffer until that part of the command list is reached, and multiple updates can be queued into a single command list. `CommandList.UpdateBuffer` is more expensive for a few reasons, but it should be a drop-in replacement for your code [here](https://github.com/bootzin/BootEngine/blob/c3a3dc0773f8ace18c21717014b15281b3f61740/BootEngine/BootEngine/Renderer/Renderer2D.cs#L345).

**Comment by bootzin** [comment]
Worked perfectly, thank you very much!
