### ISSUE TITLE
or a what?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/veldrid#316]
documentation seems to have a error on this page https://veldrid.dev/articles/getting-started/getting-started-part1.html
```
This walkthrough assumes you are using the .NET Core toolchain, although the same code could be run on .NET Framework or Mono. Veldrid is a .NET Standard 2.0 library, so you will need the .NET Core 2.0 SDK, or a

Create a new console application by running dotnet new console, or by using a "New Project" dialogue in
```

**Comment by mellinoe** [comment]
Sorry about that! I've done a quick pass over the article and fixed this. You just need a relatively recent .NET SDK, which is much less of a problem nowadays than it was when the article was written.
