### ISSUE TITLE
Strange Buffer Indexing Behaviour when using Metal

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#32]
Hello,

So I wanted to port my OpenGL instancing example to Metal. 
By doing so I discovered strange behaviour in 2 instances.

# VertexLayoutDescription

Most importantly the use of multiple `VertexLayoutDescription` will change the buffer index that metal expects by 1.

E.g.

    ShaderSet 
       = new ShaderSetDescription(
          vertexLayouts: new VertexLayoutDescription[ {vertexLayout,vertexLayoutPerInstance},
          shaders: new Shader[] {_vertexShader,_fragmentShader}
       )

With this layout I still expected that I have the following method signature in metal:
`vertex PixelInput VS(VertexInput input[[stage_in]],constant projView &pj [[ buffer(1) ]])`

However, it is actually: `vertex PixelInput VS(VertexInput input[[stage_in]],constant projView &pj [[ buffer(2) ]])`

# UpdateBuffer Placement in Command List

The uniform buffer locations have to be written to before the memory associated with VertexLayouts are set. This is different from using the OpenGL backend.

            _commandList.Begin();
            _commandList.SetFramebuffer(_graphicsDevice.SwapchainFramebuffer);
            _commandList.SetFullViewports();
            _commandList.ClearColorTarget(0,RgbaFloat.White);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,0,_camera.ViewMatrix);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,64,_camera.ProjectionMatrix);
            _commandList.SetVertexBuffer(0,_vertexBuffer);
            _commandList.SetIndexBuffer(_indexBuffer,IndexFormat.UInt16);
            _commandList.SetVertexBuffer(1,_xOffsetBuffer);
            _commandList.SetPipeline(_pipeline);
            _commandList.SetGraphicsResourceSet(0,_resourceSet); // Always after SetPipeline
            // Updatebuffer here will not work
            // _commandList.UpdateBuffer(_cameraProjViewBuffer,0,_camera.ViewMatrix);
            //_commandList.UpdateBuffer(_cameraProjViewBuffer,64,_camera.ProjectionMatrix);
            _commandList.DrawIndexed(
                indexCount: 4,
                instanceCount: 2,
                indexStart: 0,
                vertexOffset: 0,
                instanceStart: 0
            );
            _commandList.End();

Best,
Marc

**Comment by mellinoe** [comment]
It's my understanding that 1) is just how Metal works. Vertex buffers share the same binding slots as all other kinds of buffers ("uniform" buffers, "structured" buffers, etc.). In Veldrid, the slots are first assigned to all of the vertex buffers, and then to all of the "other" kinds of buffers used by a Pipeline. This is probably not documented well because the Metal backend is so new.

As for 2), that definitely seems like a bug. Could you clarify: does the `UpdateBuffer` call work if you simply place it earlier? You said "before the memory associated with VertexLayouts are set". Does it work if you call it before `SetVertexBuffer` then? Or is it before `SetGraphicsResourceSet`?

**Comment by mellinoe** [comment]
I think I understand the problem behind 2). It seems quite obvious to me now, so hopefully I will have a quick fix.

**Comment by geoeo** [comment]
1) Interesting. If thats the case, thanks for clearing that up!

2) For OpenGL I can set the `UpdateBuffer` "anywhere" i.e. before the draw call and it works.
For Metal, I have to set it before writing to the `VertexBuffers`

# Doesn't Work
## After Set Vertex, After Set Graphics Resouce
            _commandList.Begin();
            _commandList.SetFramebuffer(_graphicsDevice.SwapchainFramebuffer);
            _commandList.SetFullViewports();
            _commandList.ClearColorTarget(0,RgbaFloat.White);
            _commandList.SetVertexBuffer(0,_vertexBuffer);
            _commandList.SetIndexBuffer(_indexBuffer,IndexFormat.UInt16);
            _commandList.SetVertexBuffer(1,_xOffsetBuffer);
            _commandList.SetPipeline(_pipeline);
            _commandList.SetGraphicsResourceSet(0,_resourceSet); // Always after SetPipeline
            _commandList.UpdateBuffer(_cameraProjViewBuffer,0,_camera.ViewMatrix);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,64,_camera.ProjectionMatrix);
            _commandList.DrawIndexed(
                indexCount: 4,
                instanceCount: 2,
                indexStart: 0,
                vertexOffset: 0,
                instanceStart: 0
            );
            _commandList.End();

## After Set Vertex, Before Set Graphics Resource
            _graphicsDevice.SubmitCommands(_commandList);
            _graphicsDevice.SwapBuffers();

            _commandList.Begin();
            _commandList.SetFramebuffer(_graphicsDevice.SwapchainFramebuffer);
            _commandList.SetFullViewports();
            _commandList.ClearColorTarget(0,RgbaFloat.White);
            _commandList.SetVertexBuffer(0,_vertexBuffer);
            _commandList.SetIndexBuffer(_indexBuffer,IndexFormat.UInt16);
            _commandList.SetVertexBuffer(1,_xOffsetBuffer);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,0,_camera.ViewMatrix);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,64,_camera.ProjectionMatrix);
            _commandList.SetPipeline(_pipeline);
            _commandList.SetGraphicsResourceSet(0,_resourceSet); // Always after SetPipeline
            _commandList.DrawIndexed(
                indexCount: 4,
                instanceCount: 2,
                indexStart: 0,
                vertexOffset: 0,
                instanceStart: 0
            );
            _commandList.End();
            _graphicsDevice.SubmitCommands(_commandList);
            _graphicsDevice.SwapBuffers();


# Works
## Before Set Vertex, Before Set Graphics Resource
            _commandList.Begin();
            _commandList.SetFramebuffer(_graphicsDevice.SwapchainFramebuffer);
            _commandList.SetFullViewports();
            _commandList.ClearColorTarget(0,RgbaFloat.White);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,0,_camera.ViewMatrix);
            _commandList.UpdateBuffer(_cameraProjViewBuffer,64,_camera.ProjectionMatrix);
            _commandList.SetVertexBuffer(0,_vertexBuffer);
            _commandList.SetIndexBuffer(_indexBuffer,IndexFormat.UInt16);
            _commandList.SetVertexBuffer(1,_xOffsetBuffer);
            _commandList.SetPipeline(_pipeline);
            _commandList.SetGraphicsResourceSet(0,_resourceSet); // Always after SetPipeline
            _commandList.DrawIndexed(
                indexCount: 4,
                instanceCount: 2,
                indexStart: 0,
                vertexOffset: 0,
                instanceStart: 0
            );
            _commandList.End();
            _graphicsDevice.SubmitCommands(_commandList);
            _graphicsDevice.SwapBuffers();

**Comment by mellinoe** [comment]
Thanks for the extra info. I believe I have a fix here: https://github.com/mellinoe/veldrid/commit/fbed2a059ec5e7c19047a693a3b2389481a7e53e.

I tested your scenario and the problem now seems obvious to me. Most things in MTLCommandList are lazily set upon a draw call because of the way it switches between render, blit, and compute "modes". Vertex buffers were not being lazily set this way, so if you issued a blit operation in between setting a vertex buffer and drawing something with it, the state would be lost. It was a fairly simple fix.

**Comment by mellinoe** [comment]
I cherry-picked that commit into master, so the problem should be fixed now. Let me know if you're able to test with that version.

**Comment by geoeo** [comment]
Works like a charm 👍 

On a side note: I have to references the source dlls directly, which is not a big problem and actually preferred since I get the .pdb files now. 

But I am now seeing some strange openGL behaviour when I quit my window with **cmd+q.** This does not happen when I run the debugger and quit with the red square (Stop) or with Metal.

I tested this with your samples, so Im pretty sure (not 100%) its because of the new changes.

    Unhandled Exception: Veldrid.VeldridException: Error(s) were encountered during the execution of OpenGL commands. See InnerException for more information. ---> Veldrid.VeldridException: glGetError indicated an error: InvalidFramebufferOperationExt
    at Veldrid.OpenGL.OpenGLUtil.CheckLastError() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLUtil.cs:line 24
    at Veldrid.OpenGL.OpenGLCommandExecutor.ClearColorTarget(UInt32 index, RgbaFloat clearColor) in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLCommandExecutor.cs:line 56
    at Veldrid.OpenGL.NoAllocEntryList.OpenGLNoAllocCommandEntryList.ExecuteAll(OpenGLCommandExecutor executor) in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/NoAllocEntryList/OpenGLNoAllocCommandEntryList.cs:line 217
    at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.ExecuteWorkItem(ExecutionThreadWorkItem workItem) in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 503
    --- End of inner exception stack trace ---
    at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.CheckExceptions() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 885
    at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.WaitForIdle() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 948
    at Veldrid.OpenGL.OpenGLGraphicsDevice.WaitForIdleCore() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 239
    at Veldrid.GraphicsDevice.WaitForIdle() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/GraphicsDevice.cs:line 158
    at Veldrid.OpenGL.OpenGLGraphicsDevice.SwapBuffersCore() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 232
    at Veldrid.GraphicsDevice.SwapBuffers() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/GraphicsDevice.cs:line 136
    at getting_started.Scene.Draw() in /Users/marchaubenstock/Workspace/DotNet/henzai/getting_started/Scene.cs:line 168
    at getting_started.Scene.Main(String[] args) in /Users/marchaubenstock/Workspace/DotNet/henzai/getting_started/Scene.cs:line 52
    The terminal process terminated with exit code: 134


Thanks a lot!
Best,
Marc

**Comment by mellinoe** [comment]
Hmm, looks like it's still trying to call some GL functions after the window closes there. That's been a source of bugs in the past. If the repro is as simple as you describe then I should be able to make a fix.

**Comment by mellinoe** [comment]
I'm not reproing that behavior on any of my sample code -- do any of those trigger the problem for you?

The usual source of problems here is if the window is already closed and you continue trying to use the OpenGL GraphicsDevice by issuing commands or creating resources, etc. The sample code essentially checks if the window exists before and after pumping the message loop to make sure it wasn't destroyed before issuing graphics commands. [Here](https://github.com/mellinoe/veldrid-samples/blob/master/src/SampleBase/SampleApplication.cs#L62-L70).

OpenGL is a bit special here because the window itself sort of owns the GL context, and when it goes away, so does the GL context (and with it the `GraphicsDevice`). The other backends "stand on their own", so to speak, and won't immediately start failing when the window dies.

**Comment by geoeo** [comment]
Yes. That if check did the trick! 

The strange this is, I believe I also used to quit my windows with cmd+q before and I never saw this error... or maybe its because I now have the .pdf files since I directly reference the dlls.

Anyway. The UpdateBuffer issue is definitely solved!

**Comment by mellinoe** [comment]
Great -- I'll close this one out, then.
