### ISSUE TITLE
Can't resize main swapchain with DirectX

### ISSUE THREAD

**Issue by bootzin** [mellinoe/veldrid#321]
So, I'm going through a bit of a weird problem right now.

For some reason, when calling Swapchain.Resize(Width, Height), I can't seem to clear color/depth targets with directX, as I get a "SEHException" when I try to do that

The only thing I've found so far was [this](https://stackoverflow.com/questions/28902149/swapping-render-buffers-after-resizing-window-causes-problems) stackoverflow thread with a similar problem, but I couldn't understand how to fix it on my code, since the replies are very specific to the author's code

Also, this only happens when I am rendering to the main swapchain, if I render to a texture it works normally.

I tried calling the resize in various places in my code, including before/after/during the render call, but none of them seemed to work

This seems to have started only recently after I've migrated my code to ECS paradigm, so I may have screwed up somewhere, but I would be glad if someone could help me with this

[Here](https://github.com/bootzin/BootEngine/tree/ecs) is the source code, is case anybody wants to take a look (ecs branch, classes of interest are probably Renderer2D, RenderSystem and EventSystem. The error happens in the Sandbox project)

**Comment by bootzin** [comment]
Update:
On my Renderer2D class, I have a method called `SetPipelineDescrition`. In this method, I update the currently active pipeline description and also store the framebuffer with which I'll be rendering.

Now, the funny thing is, when I haven't bound any framebuffers, I store the **mainswapchain framebuffer** in a variable called `ActiveFramebuffer`, but apparently, when I resize the main swapchain, the reference to the framebuffer is lost (possibly because it's being recreated?), and then, when I try to clear the color/depth target, I get an exception.

Anyway, although I did find the root cause, I still have no idea on how to fix this, so any help would be welcome!

**Comment by mellinoe** [comment]
> when I resize the main swapchain, the reference to the framebuffer is lost (possibly because it's being recreated?)

Yes, you've guessed the problem. When a Swapchain is resized, its Framebuffer needs to be recreated, because the underlying Textures have changed. Instead of storing the Framebuffer alongside the Pipeline, you should pass it into your render function, or track it on the side somewhere else (and update it when a Swapchain resize happens). Note that you do not need to recreate the Pipeline unless the _format_ of the Framebuffer has changed, which will not be the case for a simple Swapchain resize.

**Comment by mellinoe** [comment]
To summarize: avoid storing a reference to your Swapchain's Framebuffer, or make sure to update the reference each time it is resized.
