### ISSUE TITLE
[Question] Native File Dialogs

### ISSUE THREAD

**Issue by bootzin** [mellinoe/veldrid#323]
Is it possible to implement native file dialogs using Veldrid/Sdl2?

If so, how would I go about it? And if not, do you know of any way of doing it in dotnet core? Or maybe a library that can do that using Sdl2? I've tried searching online, but couldn't find anything on the subject

**Comment by mellinoe** [comment]
I don't think there's anything in SDL2 that provides cross-platform file dialogs, unfortunately. It might be super heavy-weight for what you're trying to do, but perhaps [Avalonia ](http://avaloniaui.net/) has a standalone file dialog of some sort that you could use?

**Comment by feliwir** [comment]
@bootzin we use https://github.com/feliwir/SharpFileDialog in OpenSage :)
