### ISSUE TITLE
WaitForFences() throws when timeout is infinite

### ISSUE THREAD

**Issue by bensmooth** [mellinoe/veldrid#324]
Calling [GraphicsDevice.WaitForFences()](https://github.com/mellinoe/veldrid/blob/46252eb6dfaba73b368be28366c4a8bfd96cffb9/src/Veldrid/D3D11/D3D11GraphicsDevice.cs#L529) with nanosecondTimeout=ulong.MaxValue causes the WaitHandle to throw because we are blindly converting ulong.MaxValue to ms by dividing by 1 million and then trying to stuff the result into an int.  This causes the int to overflow and become negative, making WaitHandle throw:
```
System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: millisecondsTimeout
   at System.Threading.WaitHandle.WaitAll(WaitHandle[] waitHandles, Int32 millisecondsTimeout, Boolean exitContext)
   at Veldrid.D3D11.D3D11GraphicsDevice.WaitForFences(Fence[] fences, Boolean waitAll, UInt64 nanosecondTimeout)
   at Veldrid.GraphicsDevice.WaitForFences(Fence[] fences, Boolean waitAll)
```

From looking at the code, I believe this happens in all of the backends except for Vulkan.

**Comment by mellinoe** [comment]
This should be fixed now; thanks for the PR.
