### ISSUE TITLE
Clicks on unfocused window do not register (with solution)

### ISSUE THREAD

**Issue by drojf** [mellinoe/veldrid#339]
I was having an issue where the first click on an unfocused window in my ImGUI.NET program would not be registered. I noticed the ImGUI.NET sample and the NeoDemo program have the same behavior, so I could rule out my project in particular being a problem.

Reproduction Instructions: 
  1. Open the ImGUI.NET sample program/NeoDemo on the left side of your screen 
  2. Open another program on the right side of your screen, and make sure it has focus by clicking on it
  3. Click on a button on the ImGUI.NET sample program/NeoDemo (**you must not** activate focus beforehand by alt tabbing or clicking on the menu bar)
  4. The button won't activate (if you use a debugger, the click is never passed to you from SDL)

I figured out the issue was due to how SDL handles clicks by default from this thread: https://discourse.libsdl.org/t/sdl2-on-focus-gain-first-click-detection/23185

Using C, you need to call `SDL_SetHint(SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH, “1”)` so that the first click both focuses the window and clicks the button.

I then wondered if there was some built-in option in ImGUI.NET or Veldrid which could enable this feature, but couldn't find it. 

Instead I found this issue in Veldrid https://github.com/mellinoe/veldrid/issues/124 which showed me how to call the SDL `SetHint` function directly. The exact function call was `SDL_SetHint_tfuncPtr("SDL_MOUSE_FOCUS_CLICKTHROUGH", "1");` (the string is different to the #define when using C - `"SDL_MOUSE_FOCUS_CLICKTHROUGH"` instead of the define `SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH`)

Doing this fixed the issue - just for demonstration purposes, see this commit which applies the fix (you can clone the fork to try it out): https://github.com/drojf/ImGui.NET/commit/79f518fad5d8eb8b1e10d48cb95e68f80b862f24

Despite this being a fix for the issue, I would still personally want the following:
  - I would want this behavior ("clickthrough") to be the default behavior, which matches the all? the GUI apps I've used. I'm not sure if this should just change how the ImGUI.NET sample program/NeoDemo works, or change how the default Veldrid window is created.
  - I would want the `SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH` functionality to be exposed in Veldrid's WindowCreateInfo() function, in case a user wants the existing behavior where you need to click once for focus, then again to press buttons

**Comment by mellinoe** [comment]
Hey @drojf, thanks for filing the issue and providing so much information. This is a little detail that has bothered me for a while as well, and your proposed solution works very well. I've added `SDL_Hint` to Veldrid.SDL2 and also set this clickthrough flag by default when an SDL2 window is constructed.

**Comment by drojf** [comment]
Thanks!

Fixed in https://github.com/mellinoe/veldrid/commit/9f470fb7000111b1bf3aaf05db0382f8cbe4069e
