### ISSUE TITLE
CommandList per frame

### ISSUE THREAD

**Issue by DrewDaPilot** [mellinoe/veldrid#343]
Hello,

I am having an issue where veldrid decides to instance a command list for each and every frame, resulting in thousands of commandslists being created and my program eventually crashing.

![qrenderdoc_7RALlpfLNK](https://user-images.githubusercontent.com/47063089/104780935-92b06a00-574f-11eb-883e-80008bca1d26.png)

My code can be found here,

https://github.com/DrewDaPilot/VoxEng/blob/main/VoxEng.Core/Rendering/RenderManager.cs

I am not directly instancing new CommandsLists each frame, and the documentation is not clear on when instancing would happen automatically. Any help would be much appreciated.

**Comment by mellinoe** [comment]
One thing I see is that you are not calling Sdl2Window.PumpEvents anywhere. This will eventually cause Windows (or whatever operating system you are working on) to think that your application is no longer responding, and forcibly close it. This doesn't necessarily have anything to do with Veldrid per se.

Second, could you be more specific about what the issue with CommandList allocation is here? Behind the scenes (and it varies between backend), Veldrid may need to allocate or free some native resources, depending on how the native API works. Assuming you are using D3D11 in this case, Veldrid may create native D3D resources as needed.

**Comment by DrewDaPilot** [comment]
I understand. I rewrote my program and it no longer causes a new commandslist to be instanced for each draw call. Not really sure what happened here, but I appreciate your responsiveness and assistance.

Best of luck with the future of veldrid,

Drew.
