### ISSUE TITLE
Sample of setting up GraphicsDevice in UWP

### ISSUE THREAD

**Issue by mgrman** [mellinoe/veldrid#366]
Hi,

I was playing around with use of Veldrid in Xamarin Forms (for later use in MAUI) and noticed there are no samples on how to set up Veldrid in UWP.
I saw there is CreateUWP method for creating SwapChain.

But when I use it in a class that is inheriting SwapChainPanel, like:
```
var ss = SwapchainSource.CreateUwp(this, DisplayInformation.GetForCurrentView().LogicalDpi);
var scd = new SwapchainDescription( ss, Width, Height, PixelFormat.R32_Float, false);
var d3dOptions = new D3D11DeviceOptions()
{
    DeviceCreationFlags = (uint)(DeviceCreationFlags.Debuggable | DeviceCreationFlags.Debug)
};
_gd = GraphicsDevice.CreateD3D11(options,d3dOptions,scd);
```
causes
```
SharpDX.SharpDXException: 'HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: The specified device interface or feature level is not supported on this system.
'
```
Sadly SharpDX seems to be no longer developed and I could not find a solution to that problem.
I am on a PC with latest Windows 10 and dedicated GPU.
Do you have any samples/test projects that are known to be working? Something to start me of in the right direction?
Thank you.

**Comment by mellinoe** [comment]
It's possible that the `DeviceCreationFlags.Debug` flag is causing you issues. Generally, using this flag with the D3D11 backend requires the [Graphics Tools](https://docs.microsoft.com/en-us/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features) optional feature to be installed. However, it's also possible that there's an issue with this codepath, I removed the UWP sample project a long time ago and haven't tested it recently.

Also note that SharpDX is not used in the latest version of Veldrid -- you may want to update and try again to see if anything has changed.

**Comment by mgrman** [comment]
Yeah, I updated to develop builds of Veldrid Version="4.9.0-g02c2c96278" and then it works. So you can close this ticket, at least this ticket can serve as the desired sample.

```
var ss = SwapchainSource.CreateUwp(swapchainPanel, DisplayInformation.GetForCurrentView().LogicalDpi);
var scd = new SwapchainDescription(
    ss,
    width,
    height,
    PixelFormat.R32_Float,
    false);

var options = new GraphicsDeviceOptions(
    debug: false,
    swapchainDepthFormat: PixelFormat.R32_Float,
    syncToVerticalBlank: true,
    resourceBindingModel: ResourceBindingModel.Improved,
    preferDepthRangeZeroToOne: true,
    preferStandardClipSpaceYDirection: true);
var backend = GraphicsBackend.Direct3D11;

var d3dOptions = new D3D11DeviceOptions() 
{
    DeviceCreationFlags= (uint) Vortice.Direct3D11.DeviceCreationFlags.Debug
};

if (backend == GraphicsBackend.Direct3D11)
{
    _gd = GraphicsDevice.CreateD3D11(options, d3dOptions, scd);
}
else
{
    throw new NotImplementedException();
}
graphicsDevice.OnNext(_gd);
swapchain.OnNext(_gd.MainSwapchain);
```

For WPF I found a found also using UPW Swapchain via XAML island works better, than HWND Windows since it does not capture mouse and you can overlay other controls.
