### ISSUE TITLE
#if issue

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#37]
@mellinoe 
Hi.
Take a look here:
https://github.com/mellinoe/veldrid/blob/9dfc41af8e24918919dce55152ea2d080f98f71b/src/Veldrid/CommandList.cs#L210

Seems like a bracket should be outside of #endif?

**Comment by mellinoe** [comment]
Thanks for the catch. Fixed in https://github.com/mellinoe/veldrid/commit/a6a8464b90170f8a489da87e286ba0cabb4c12eb
