### ISSUE TITLE
A way to control texture components/swizzles in a texture view?

### ISSUE THREAD

**Issue by KillzXGaming** [mellinoe/veldrid#372]
I'd like a way to control the channel swizzles with a mask in the texture view.  I'm not sure if all backends support it but I know that
OpenGL does this with   `GL.TexParameter(target, TextureParameterName.TextureSwizzleRgba, mask)` and vulkan has `VK_COMPONENT_SWIZZLE_IDENTITY` with `ImageViewCreateInfo`.`

**Comment by mellinoe** [comment]
Unfortunately, it doesn't look like D3D11 supports texture swizzling, although D3D12 does. That makes this a bit of a non-starter unless there is a feature that I'm missing.

**Comment by KillzXGaming** [comment]
Ah I see. I'll close this then since it can't really be helped.
