### ISSUE TITLE
Veldrid can't be compiled without VALIDATE_USAGE define

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#38]
@mellinoe
2>3rdParty\Veldrid\Source\Veldrid\CommandList.cs(800,36,800,61): error CS1061: 'Pipeline' does not contain a definition for 'GraphicsOutputDescription' and no extension method 'GraphicsOutputDescription' accepting a first argument of type 'Pipeline' could be found (are you missing a using directive or an assembly reference?)

More likely this is because of:
#if VALIDATE_USAGE
internal OutputDescription GraphicsOutputDescription { get; }
#endif

**Comment by mellinoe** [comment]
Fixed with https://github.com/mellinoe/veldrid/commit/9807394ddd540b100498006e6f1c4fbc442b0d76
