### ISSUE TITLE
SDL 2.0.7 for OS X

### ISSUE THREAD

**Issue by Krakean** [mellinoe/veldrid#39]
@mellinoe 
Can you please SDL to 2.0.7 for OS X too? As I can see - https://github.com/mellinoe/veldrid/tree/master/src/Veldrid.SDL2/native- right now is only Windows x64 dll is updated.

**Comment by mellinoe** [comment]
I've updated it: https://github.com/mellinoe/veldrid/commit/4428e3d3d8d7c9ddae8ab43608791bf132b5c41d

By the way, Veldrid will prefer the system library if it is installed over what is in the NuGet package. So if you install it from homebrew (the current version is 2.0.7), then that binary will be used.
