### ISSUE TITLE
Veldrid.ImGui nuget out of date 

### ISSUE THREAD

**Issue by NHodgesVFX** [mellinoe/veldrid#407]
The nugget package for Veldrid.ImGui is out of date compared to the source here. It also seems the src uses ImGui.net 1.72 where the ImGui.net nugget is at 1.78.

I also noticed while looking at Veldrid.ImGui .Csproj that their is a shader for each backend. Is there any reason why it doesn't just use a portable shader?

Thanks for the awesome projects. Veldrid, ImGui.net and the helper projects are great really been enjoying working with them.

**Comment by mellinoe** [comment]
Up-to-date as of now
