### ISSUE TITLE
Is there a way to gather information about shader uniforms

### ISSUE THREAD

**Issue by BarisUckardes** [mellinoe/veldrid#413]
Is there a way to find all the uniforms of a shader.

Such as `glGetActiveAttrib` and `glGetActiveUniform` method in openGL.

**Comment by mellinoe** [comment]
No, this functionality doesn't exist in quite that form. In Veldrid, it's expected that you provide a description of all of the resources used by a set of shaders yourself. If you compile your shaders into SPIR-V (I highly recommend this), then you can use Veldrid.SPIRV to build a [SpirvReflection](https://github.com/mellinoe/veldrid-spirv/blob/master/src/Veldrid.SPIRV/SpirvReflection.cs) object while the code is being compiled. This has some of the information you might be interested in.
