### ISSUE TITLE
which coordinate systems veldrid use?

### ISSUE THREAD

**Issue by qianqians** [mellinoe/veldrid#414]
which coordinate systems veldrid use? i didn't see in documentation

**Comment by jhm-ciberman** [comment]
Short answer: None, it's up to you. 
Long answer: https://veldrid.dev/articles/backend-differences.html

**Comment by mellinoe** [comment]
@jhm-ciberman is correct, there is no coordinate system enforced by Veldrid. You can use whatever you'd like -- the convention will be defined by how your matrix functions are defined, so if you choose to utilize an existing math library, some of those decisions will likely have been made already.

The factory methods in System.Numerics.Matrix4x4 that have such a distinction are right-handed.
