### ISSUE TITLE
why VertexElementDescription not explicit set location in shader?

### ISSUE THREAD

**Issue by qianqians** [mellinoe/veldrid#415]
why VertexElementDescription not explicit set location in shader?

**Comment by mellinoe** [comment]
Locations (as in, integer indices) aren't used uniformly in Veldrid's backends. OpenGL (presumably where you'd like to use locations) doesn't use locations, but matches by name instead. The specific mechanisms are described in [this article](https://veldrid.dev/articles/shaders.html).
