### ISSUE TITLE
asking native file handling 

### ISSUE THREAD

**Issue by John0King** [mellinoe/veldrid#438]
1st, sorry for asking things not related about this project.
you bind a lot using p/invoke  to native dll,   but I find I can't  "reference" the native dll into my project (directly without nuget `<PackageReference />`)

this is my question: https://github.com/dotnet/runtime/discussions/65420

basically:  
```xml
<Content Include="Native\win-x64\vbar.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>runtimes/win-x64/native/vbar.dll</PackagePath>
    </Content>
``` 
this resolve to nuget package,  but it doesn't help for "project" and "`<ProjectReference />`"   
and even if I  put my dll in  `<project dir>\runtimes\win-x64\native\vbar.dll`  , it will only work for `AnyCpu` -`portable` ,  and it doesn't work when I publish as self-contained ,   other native file will goes to top level folder and mine are stay in "runtimes" ,  and  there no record in `App.deps.json`  but other native dll from nuget are in there.

**Comment by mellinoe** [comment]
Unfortunately, I'm not really an expert in this stuff anymore, you'd best ask in one of the dotnet repos or through some other .NET support channel. I can point you to how [NeoDemo does it](https://github.com/mellinoe/veldrid/blob/master/src/NeoDemo/NeoDemo.csproj#L33-L40) which is to just directly reference and copy the native DLLs that its dependencies use. Not ideal, but it gets the job done.
