### ISSUE TITLE
Getting "Segementation fault" while attempting to run a program in Linux.

### ISSUE THREAD

**Issue by Jenrikku** [mellinoe/veldrid#440]
I have cloned the repository, used `dotnet build` and tried to run "NeoDemo" to check if the problem was my code but it turns out that `Segmentation fault` is thrown as well.

SO: Ubuntu 20.04.3
\* Running on a VM under Windows 10, happens both on Hyper-V and Oracle VirtualBox.

![imatge_2022-02-20_141313](https://user-images.githubusercontent.com/60291632/154844309-4a348aaf-7233-4aad-ab0f-747b7057507a.png)

**Comment by mellinoe** [comment]
Can you run it under a debugger like `gdb` to see where it's crashing? If I had to guess, you're likely missing a native dependency, like Vulkan or SDL2, which you can install from the package manager. Hard to say without more information, however.

**Comment by Jenrikku** [comment]
I am not sure how I should debug the program using gdb.

**Comment by Beyley** [comment]
> I am not sure how I should debug the program using gdb.

you can run the command `gdb NATIVE_EXECUTABLE_HERE(not dotnet but like the NeoDemo linux executable you get after building) COREDUMP`
aka: `gdb ./NeoDemo core.36743`

Also, i would HIGHLY reccomend *not* running dotnet under sudo, as it does not need sudo priviledges

**Comment by Jenrikku** [comment]
The exe does not have symbols so the debugger can not work with it. I am not sure if I am able to compile it with them.
![image](https://user-images.githubusercontent.com/60291632/160188254-8c58a221-6ea1-4080-b103-7377bff5eecf.png)

**Comment by Beyley** [comment]
> The exe does not have symbols so the debugger can not work with it. I am not sure if I am able to compile it with them.
> ![image](https://user-images.githubusercontent.com/60291632/160188254-8c58a221-6ea1-4080-b103-7377bff5eecf.png)
> Edit: Not even the Debug build configuration.

you need to actually point it to the coredump

**Comment by Jenrikku** [comment]
> you need to actually point it to the coredump

I am sorry, it is my first time debugging a linux program so I am quite lost. Could you give me more information on how to do so?

**Comment by Jenrikku** [comment]
I will go ahead and close this issue since it does not seem to be related with Veldrid.
