### ISSUE TITLE
metal problem help

### ISSUE THREAD

**Issue by haolange** [mellinoe/veldrid#451]
I use Silk.Net glfw on veldrid. when it start running, it's perfect, but if i move the window it will turn black, and if i recreate CAMetalLayer it will become normal. So why?

<img width="976" alt="{CD005A13-BDDB-24D4-AE84-FBE21EEAFF62}" src="https://user-images.githubusercontent.com/12471727/167005042-dc18a992-a50f-4405-a163-1681b7168a77.png">
<img width="987" alt="{18BF53C7-8E31-A7C2-88E8-2D60C9DB6B02}" src="https://user-images.githubusercontent.com/12471727/167005055-e15e18d6-fcaa-4f9d-a458-5bb6f45ccf17.png">
<img width="995" alt="{32C86F46-393A-2F1F-DBE0-1C48DA3F244A}" src="https://user-images.githubusercontent.com/12471727/167005073-8941e46c-711b-4697-b0cf-84f9a15a6449.png">

**Comment by haolange** [comment]
I found why. Glfw window muse set hint to clear glContext. Otherwise, it will race of metal.

**Comment by mellinoe** [comment]
I don't think there's a bug in Veldrid here, please reopen if I'm mistaken.
