### ISSUE TITLE
[Metal] Strange behaviour with uniforms split up over vertex and fragment shaders.

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#46]
Hello,

I noticed something odd when looking at uniforms and metal.

So I have a resource layout:
`ResourceLayouts = new ResourceLayout[]{_cameraResourceLayout,_materialResourceLayout,_lightResourceLayout}`

Which results in the following uniform bindings in metal

### Vertex
`vertex PixelInput VS(VertexInput input[[stage_in]],constant ProjView &pj [[ buffer(1) ]],constant Light &l [[ buffer(3) ]])`

Sure, light is last in the layout so it gets assigned to 3

### Fragment

`fragment float4 FS(PixelInput input[[stage_in]],constant Material &material [[buffer(1)]])`

I was expecting 2 here, but ok, its the first element in the fragment stage.

However, **changing** the resource layout has no effect on the bindings (?)

`ResourceLayouts = new ResourceLayout[] {_cameraResourceLayout,_lightResourceLayout,_materialResourceLayout}`

### Vertex Expected
`vertex PixelInput VS(VertexInput input[[stage_in]],constant ProjView &pj [[ buffer(1) ]],constant Light &l [[ buffer(2) ]])`

But it is still 3.

Is this intended?

**Comment by mellinoe** [comment]
Could you post more code, like the definitions for these? `_cameraResourceLayout,_materialResourceLayout,_lightResourceLayout`

**Comment by geoeo** [comment]
The whole scene is defined [here](https://github.com/geoeo/henzai/blob/master/asset-loading/Scene.cs)
### Resources

            /// Uniform 1 - Camera
            _cameraProjViewBuffer = _factory.CreateBuffer(new BufferDescription(128,BufferUsage.UniformBuffer | BufferUsage.Dynamic));

            var resourceLayoutElementDescription = new ResourceLayoutElementDescription("projView",ResourceKind.UniformBuffer,ShaderStages.Vertex);
            ResourceLayoutElementDescription[] resourceLayoutElementDescriptions = {resourceLayoutElementDescription};
            var resourceLayoutDescription = new ResourceLayoutDescription(resourceLayoutElementDescriptions);
            BindableResource[] bindableResources = new BindableResource[]{_cameraProjViewBuffer};

            _cameraResourceLayout = _factory.CreateResourceLayout(resourceLayoutDescription);
            var resourceSetDescription = new ResourceSetDescription(_cameraResourceLayout,bindableResources);
            
            _cameraResourceSet = _factory.CreateResourceSet(resourceSetDescription);

            // Uniform 2 - Material
            _materialBuffer = _factory.CreateBuffer(new BufferDescription(48,BufferUsage.UniformBuffer));

            var resourceLayoutElementDescriptionMaterial = new ResourceLayoutElementDescription("material",ResourceKind.UniformBuffer,ShaderStages.Fragment);
            ResourceLayoutElementDescription[] resourceLayoutElementDescriptionsMaterial = {resourceLayoutElementDescriptionMaterial};
            var resourceLayoutDescriptionMaterial = new ResourceLayoutDescription(resourceLayoutElementDescriptionsMaterial);
            BindableResource[] bindableResourcesMaterial = new BindableResource[]{_materialBuffer};

            _materialResourceLayout = _factory.CreateResourceLayout(resourceLayoutDescriptionMaterial);
            var resourceSetDescriptionMaterial = new ResourceSetDescription(_materialResourceLayout,bindableResourcesMaterial);
            
            _materialResourceSet = _factory.CreateResourceSet(resourceSetDescriptionMaterial);

            // Uniform 3 - Light
            _lightBuffer = _factory.CreateBuffer(new BufferDescription(16,BufferUsage.UniformBuffer));

            var resourceLayoutElementDescriptionLight = new ResourceLayoutElementDescription("light",ResourceKind.UniformBuffer,ShaderStages.Vertex);
            ResourceLayoutElementDescription[] resourceLayoutElementDescriptionsLight = {resourceLayoutElementDescriptionLight};
            var resourceLayoutDescriptionLight = new ResourceLayoutDescription(resourceLayoutElementDescriptionsLight);
            BindableResource[] bindableResourcesLight = new BindableResource[]{_lightBuffer};

            _lightResourceLayout = _factory.CreateResourceLayout(resourceLayoutDescriptionLight);
            var resourceSetDescriptionLight = new ResourceSetDescription(_lightResourceLayout,bindableResourcesLight);

           _lightResourceSet = _factory.CreateResourceSet(resourceSetDescriptionLight);

**Comment by mellinoe** [comment]
Hm, I wrote up a quick test and I'm not seeing the same thing. I'm seeing something that matches what you have listed under "Vertex Expected". Scanning through the code matches what I'm seeing as well. How are you determining that the wrong slot is getting used?

**Comment by geoeo** [comment]
Going from:
`ResourceLayouts = new ResourceLayout[]{_cameraResourceLayout,_materialResourceLayout,_lightResourceLayout}`

to 

`ResourceLayouts = new ResourceLayout[] {_cameraResourceLayout,_lightResourceLayout,_materialResourceLayout}`

 should result in a changed buffer slot allocation or?

**Comment by mellinoe** [comment]
It should, yes. Are you also changing the index that you are binding the corresponding `ResourceSet` to?

**Comment by geoeo** [comment]
no! Ok I knew I was missing something.

Thanks!

The headers are now 
## Vertex
`vertex PixelInput VS(VertexInput input[[stage_in]],constant ProjView &pj [[ buffer(1) ]],constant Light &l [[ buffer(2) ]])`

### Fragment
`fragment float4 FS(PixelInput input[[stage_in]],constant Material &material [[buffer(2)]])`

On a similar note. Why is the buffer index in the fragment shader 2 and not either 1 or 3?

**Comment by mellinoe** [comment]
> On a similar note. Why is the buffer index in the fragment shader 2 and not either 1 or 3?

Yeah, it's a bit quirky. The way these numbers are assigned is really simple, but it can lead to things that look confusing initially. This is what is done:

1. Loop through each ResourceLayout
2. Loop through each resource in the layout
3. When a buffer is encountered, increment "buffer index" and assign it to that buffer
  * This is done regardless of its stage flags
  * This buffer index is shared across stages
4. When binding a buffer to the vertex stage, add `VertexBuffers.Count` (the number of vertex input buffers used).
5. When binding a buffer to the fragment stage, don't add `VertexBuffers.Count`. 

Number **5.** is why the fragment buffer index seems like it is off-by-one.

In the future, I want to make this a little better, but it will be a breaking change that needs to be done carefuly. Most likely I will have a GraphicsDeviceOptions flag that influcences how a Pipeline assigns its indices. For Metal I would probably:

* Puts vertex buffers at the END of the slot indices instead of the front. These aren't specified in the shader anyways, so it would be better if they were at the end, so that your "normal" buffers started at 0.
* Assigns buffer/texture/sampler indices individually for each stage, starting at 0.

**Comment by geoeo** [comment]
Makes sense. Makes things clearer. 
Thanks. 

I think it it would be worth copy-pasting these steps into: 

https://mellinoe.github.io/veldrid-docs/articles/shaders.html

I initially looked there, but couldnt find anything.

**Comment by mellinoe** [comment]
Good idea, I will add more detailed info there that makes this clearer.
