### ISSUE TITLE
[Metal] FillMode.Wireframe doesnt work

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#47]
Setting `PolygonFillMode.Wireframe` works with OpenGL no problem, but seems to be ignored with Metal

**Comment by mellinoe** [comment]
You're right, this is being ignored on Metal.

It needs to figure out the [MTLTriangleFillMode](https://developer.apple.com/documentation/metal/mtltrianglefillmode?language=objc) in the MTLPipeline constructor and then call [setTriangleFillMode:](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1516029-settrianglefillmode?language=objc) in MTLCommandList.

I'll fix this later today.

**Comment by mellinoe** [comment]
Fixed in https://github.com/mellinoe/veldrid/commit/7e505def90170766dbd9d4f8d7b91363fab840fa
