### ISSUE TITLE
Support Vulkan on macOS/iOS

### ISSUE THREAD

**Issue by mellinoe** [mellinoe/veldrid#48]
Since MoltenVK is now open source, Veldrid should support using Vulkan on macOS and iOS. I hacked some things together and got the basics working. There's only a few problems with the current code:

* Need to add a little extra code to support creating a swapchain from an NSWindow or UIView.
* The multi-viewport feature is assumed to be supported, but it's not on MoltenVK. Need to actually check that the feature is supported before enabling it and handle other stuff, like what happens when you set a non-zero viewport.
* Geometry shaders are assumed to be supported, but they aren't.
* VkEvents are not supported at all by MoltenVK. Unfortunately, VkCommandList uses events to determine when to recycle staging buffers. This dependency can probably be removed.

Aside from the above, there's still several bugs in MoltenVK that prevent Veldrid from working. After hacking around the bugs that I'm aware of, I'm able to render simple stuff, but NeoDemo renders completely wrong, despite not hitting any errors or warnings.

**Comment by amerkoleci** [comment]
Thumbs up for this, then you can remove metal backend at this point, soon there should be d3d12 support also

**Comment by mellinoe** [comment]
> then you can remove metal backend at this point

Actually, I don't have any intention on removing Metal support any time soon. The Metal backend should always be faster and simpler than Vulkan-on-Metal, because there's one less translation layer to travel through. Deployment of MoltenVK stuff will also more complicated than using Metal, which is simply available as a system component.

**Comment by geoeo** [comment]
> The multi-viewport feature is assumed to be supported, but it's not on MoltenVK. Need to actually check that the feature is supported before enabling it and handle other stuff, like what happens when you set a non-zero viewport.

>Geometry shaders are assumed to be supported, but they aren't.

>VkEvents are not supported at all by MoltenVK. Unfortunately, VkCommandList uses events to determine when to recycle staging buffers. This dependency can probably be removed.

Seems like Veldrid is better than MoltenVK ;)

**Comment by mellinoe** [comment]
To be fair, those are limitations in Metal itself which can't really be worked around. The Metal backend here doesn't support geometry shaders or multiple viewports either. There's no concept of an event in Veldrid, so that one doesn't matter.

**Comment by amerkoleci** [comment]
Metal supports multiple viewport tho, not sure about MoltenVK

**Comment by mellinoe** [comment]
There's some restrictions on it, and I'm assuming that's where MoltenVK's limitation comes in: https://developer.apple.com/documentation/metal/mtlrendercommandencoder/2928178-setviewports

> Only one of the viewports in the array is used for transformations and clipping.

**Comment by mellinoe** [comment]
I tried again today and it seems like things have progressed quite a lot since it was originally open sourced. There's still a couple of issues, but I'm able to fully render NeoDemo after patching them locally, and I don't see any artifacts. I also tried a couple of the projects in veldrid-samples, and they worked as well.

<img width="962" alt="screen shot 2018-05-19 at 10 34 03 pm" src="https://user-images.githubusercontent.com/8918977/40276077-630a1e56-5bb5-11e8-8430-db82879b7acf.png">

MoltenVK patches: https://github.com/KhronosGroup/MoltenVK/pull/161, https://github.com/KhronosGroup/MoltenVK/pull/162

**Comment by mellinoe** [comment]
Veldrid branch: https://github.com/mellinoe/veldrid/tree/moltenvk-2

**Comment by mellinoe** [comment]
The above MoltenVK changes have made their way upstream, and the changes to Veldrid have also been merged in to master. There are still some MoltenVK issues of unknown importance, but things work well enough to run NeoDemo cleanly at this point in time. As far as I know, there are no additional changes that need to be made in Veldrid itself.
