### ISSUE TITLE
Directory.Build.props ProjectDir conflicts

### ISSUE THREAD

**Issue by amerkoleci** [mellinoe/veldrid#5]
Hi,
I copied the Directory.Build.props into my project directory, I had some issue with Visual Studio 2017 not resolving the correct include paths, and it happens when you have native c++ projects into the solution.

$(ProjectDir) overrides the C++ ProjectDir and causes issues with resolve path.

Probably in Veldrid that won't cause issue as you have only Managed projects, just pointing the issue I faced :)

**Comment by mellinoe** [comment]
Ah, unfortunate. Are you able to put it into a different subdirectory so it doesn't conflict?

**Comment by amerkoleci** [comment]
I just removed the ProjectDir from there and it works well.

**Comment by mellinoe** [comment]
Fair enough -- I guess ProjectDir isn't even used in here anyways. I copy-paste that file around and it's probably used in some other repos.

**Comment by amerkoleci** [comment]
Sounds good, feel free to close it :)

**Comment by mellinoe** [comment]
Thanks for the note, though. I will probably rename this property just to be safe 😄 

Out of curiosity: are you planning to use Veldrid in your game engine? I got the impression that you had already implemented a sort of graphics layer yourself.

**Comment by amerkoleci** [comment]
I have native layer for windowing, think about SDL and I have also native rendering layer which will implement all backends like Vulkan, DirectX12 and  then rest, you have everything in C# by using SharpDX and OpenTK, I will try to move to native performance impact operations in the future, for example frustum culling

**Comment by amerkoleci** [comment]
I sent you mail last week but you did not answer

**Comment by mellinoe** [comment]
Ah, that you did! My mistake, I thought I had responded. Look out for an email 😄
