### ISSUE TITLE
Unreachable code in VkTexture.GetSubresourceLayout

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid#51]
https://github.com/mellinoe/veldrid/blob/master/src/Veldrid/Vk/VkTexture.cs#L218
``_stagingBuffer`` is of type ``Vulkan.vkBuffer``, which is a struct, and therefore is never equal to null.

**Comment by mellinoe** [comment]
You're right, that's a mistake. Luckily, the method is only ever called on staging Textures, so it will not matter in all the current codepaths. The logic should definitely be fixed, but TBH I'm not sure there's any reason to call that function on a regular Texture (non-staging).

**Comment by mellinoe** [comment]
@SomeAnon42 I fixed this here: https://github.com/mellinoe/veldrid/commit/e84db0ece093710f51f2715ea32011578f009037
