### ISSUE TITLE
Unable to run AnimatedMesh sample

### ISSUE THREAD

**Issue by taumuon** [mellinoe/veldrid#52]
Hi, I fetched Veldrid.Samples source yesterday, and most of the sample work, but when I try to run the AnimatedMesh sample I get a build error. Below is the full log.

This is in Visual Studio 2017, with .net sdk 2.1.4 x64.

Do you need any more info?

Thanks,
Gary

1>------ Build started: Project: AnimatedMesh, Configuration: Debug Any CPU ------
1>D:\git\veldrid-samples\src\AnimatedMesh\AnimatedMesh.csproj : warning NU1603: AnimatedMesh depends on ShaderGen.Build (>= 1.1.0-g1b11bad785) but ShaderGen.Build 1.1.0-g1b11bad785 was not found. An approximate best match of ShaderGen.Build 1.1.0-g262a77fb72 was resolved.
1>D:\git\veldrid-samples\src\AnimatedMesh\AnimatedMesh.csproj : warning NU1603: AnimatedMesh depends on ShaderGen.Primitives (>= 1.1.0-g1b11bad785) but ShaderGen.Primitives 1.1.0-g1b11bad785 was not found. An approximate best match of ShaderGen.Primitives 1.1.0-g262a77fb72 was resolved.
1>An error was encountered while generating shader code:
1>System.NullReferenceException: Object reference not set to an instance of an object.
1>   at ShaderGen.LanguageBackend.IsIndexerAccess(SymbolInfo member) in C:\projects\shadergen\src\ShaderGen\LanguageBackend.cs:line 151
1>   at ShaderGen.ShaderMethodVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 130
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitArgument(ArgumentSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 254
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
1>   at System.String.Join(String separator, IEnumerable`1 values)
1>   at ShaderGen.ShaderMethodVisitor.VisitBracketedArgumentList(BracketedArgumentListSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 408
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitElementAccessExpression(ElementAccessExpressionSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 403
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitBinaryExpression(BinaryExpressionSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 235
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitEqualsValueClause(EqualsValueClauseSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 90
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitVariableDeclaration(VariableDeclarationSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 388
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 85
1>   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor`1.Visit(SyntaxNode node)
1>   at ShaderGen.ShaderMethodVisitor.VisitBlock(BlockSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 58
1>   at ShaderGen.ShaderMethodVisitor.VisitFunction(BlockSyntax node) in C:\projects\shadergen\src\ShaderGen\ShaderMethodVisitor.cs:line 38
1>   at ShaderGen.HlslBackend.GenerateFullTextCore(String setName, ShaderFunction function) in C:\projects\shadergen\src\ShaderGen\HlslBackend.cs:line 216
1>   at ShaderGen.LanguageBackend.GetCode(String setName, ShaderFunction function) in C:\projects\shadergen\src\ShaderGen\LanguageBackend.cs:line 118
1>   at ShaderGen.LanguageBackend.GetShaderModel(String setName) in C:\projects\shadergen\src\ShaderGen\LanguageBackend.cs:line 73
1>   at ShaderGen.ShaderGenerator.GenerateShaders(ShaderSetInfo ss, ShaderGenerationResult result) in C:\projects\shadergen\src\ShaderGen\ShaderGenerator.cs:line 203
1>   at ShaderGen.ShaderGenerator.GenerateShaders() in C:\projects\shadergen\src\ShaderGen\ShaderGenerator.cs:line 151
1>   at ShaderGen.App.Program.Main(String[] args) in C:\projects\shadergen\src\ShaderGen.App\Program.cs:line 158
1>
1>C:\Users\garym\.nuget\packages\shadergen.build\1.1.0-g262a77fb72\build\ShaderGen.targets(35,5): error MSB3073: The command "dotnet C:\Users\garym\.nuget\packages\shadergen.build\1.1.0-g262a77fb72\build\ShaderGen.App.dll  --ref " D:\git\veldrid-samples\bin\obj\AnimatedMesh\Debug\netcoreapp2.0\_sgreferences.txt " --src " D:\git\veldrid-samples\bin\obj\AnimatedMesh\Debug\netcoreapp2.0\_sgsources.txt " --out " D:\git\veldrid-samples\bin\obj\AnimatedMesh\Shaders " --genlist "D:\git\veldrid-samples\bin\obj\AnimatedMesh\Debug\netcoreapp2.0\_sggeneratedfiles.txt"" exited with code -1.
1>Done building project "AnimatedMesh.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by mellinoe** [comment]
> but ShaderGen.Primitives 1.1.0-g1b11bad785 was not found. 

Hrm... that's not good. I think the prerelease version of ShaderGen that I am referencing was automatically deleted by myget. I should put up a beta version on nuget or something so this doesn't happen again.

Can you try to change the version to `1.1.0-g59bcb10a4b` and see if that works? Change this line: https://github.com/mellinoe/veldrid/blob/master/Directory.Build.props#L16.

Sorry about the difficulty.

**Comment by taumuon** [comment]
Thanks for looking into this!
I changed the version, and I was then able to build, but then I get an exception at runtime, on the line:
_scene = ac.ImportFile(GetAssetPath(monsterAssetPath), 0);

System.IO.FileNotFoundException: 'Could not find or load the native library: Assimp64.dll'

Thanks,
Gary

**Comment by mellinoe** [comment]
I'm not seeing that error -- it should be able to locate Assimp64.dll from the assimpnet-netstandard nuget package. How are you running the application, and what version of Windows are you using?

**Comment by taumuon** [comment]
Hi, I'm setting AnimatedMesh as the startup project in VisualStudio, and then try to launch it from the IDE. I'm running on Windows 10 64 bit.
The Nuget package folder
C:\Users\garym\.nuget\packages\assimpnet-netstandard\3.3.1\lib\netstandard2.0
only contains AssimpNet.dll, not Assimp64.dll.
Thanks, gary

**Comment by mellinoe** [comment]
The native binary will be under the "runtimes" directory, e.g.:

`.nuget\packages\assimpnet-netstandard\3.3.1\runtimes\win-x64`

**Comment by taumuon** [comment]
hi, thanks again for the reply.
I can confirm the binary is there - do you know why it isn't being resolved?
Running
dotnet AnimatedMesh\netcoreapp2.0\AnimatedMesh.dll
fails too

**Comment by mellinoe** [comment]
@taumuon Hm, I'm not sure. That's very strange. Can you try cleaning out your bin directory and restoring the packages again? Optionally, you can delete the `.nuget\packages\assimpnet-netstandard\3.3.1` folder as well to see if that helps.

**Comment by RUSshy** [comment]
It works for me, i use rider 
![image](https://user-images.githubusercontent.com/18348637/40438945-c4851328-5eb9-11e8-971a-da4b3c3ce33d.png)

**Comment by mellinoe** [comment]
Aside from the initial NuGet package problem, there shouldn't be any further issues here. I'm not able to repro anything on any of my machines, so there might be something wrong with a NuGet cache somewhere (totally guessing). Let me know if you continue to have problems running any of the samples.
