### ISSUE TITLE
image.MetaData.HorizontalResolution is not correct, returns 1, and file properties shows 96

### ISSUE THREAD

**Issue by steven-gong** [mellinoe/veldrid#56]
I'm using Veldrid.ImageSharp v4.1.1 from Nuget, and run the following code:
       var fileStream = new FileStream("96Resolution.jpg", FileMode.Open);
       IImageFormat format;
       var image = Image.Load(fileStream, out format);
       if (image.MetaData.HorizontalResolution < 72){ .... } 

Here image.MetaData.HorizontalResolution is 1, but when I check the image properties, its resolution is 96 both vertically and horizontally. Another jpg file returns the correct resolution.
Just attached my test image.
![invalidresolution](https://user-images.githubusercontent.com/21999878/37503662-96f90352-293e-11e8-93fe-92e55720c8f3.jpg)

Thanks

**Comment by mellinoe** [comment]
Hey @steven-gong, I'm not actually the developer of ImageSharp itself. Veldrid.ImageSharp is just an integration library that lets you create GPU textures from images loaded through ImageSharp. If there's a problem with loading image files, then you might want to go check the [ImageSharp repo](https://github.com/SixLabors/ImageSharp), or ask around the chat to see if anyone's seen the problem before.

**Comment by steven-gong** [comment]
Hi Eric,
Thanks, will post the issue there.
Steven
