### ISSUE TITLE
CreateBuffer being public and not overridable undermines DisposableResourceCollector

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#59]
By making this method public and non-overridable it obfuscates the interface to resource generation. It is too easy to accidentally create an object of type DeviceBuffer through CreateBuffer rather than CreateBufferCore when using the DeviceResourceCollector.

https://github.com/mellinoe/veldrid/blob/d5122453394665e446c95b4ebed5eba93c575af4/src/Veldrid/ResourceFactory.cs#L151

**Comment by mellinoe** [comment]
Could you clarify what the issue is about? Is it that the validation logic will run twice in DisposeCollectorResourceFactory?

**Comment by geoeo** [comment]
Nevermind. I should read the source more carefully. Just ignore my issue
