### ISSUE TITLE
Veldrid.SDL2 with .NET Framework

### ISSUE THREAD

**Issue by ZingBallyhoo** [mellinoe/veldrid#74]
Heyo.

I've been kinda interested in using Veldrid.SDL2 to manage the window in a rendering style application. I have to use .NET Framework due to some dependencies that I don't really get a say in.

I've tested a couple of different ways of making it work, but I just can't get it to work properly.

- Referencing Veldrid.SDL2 from .NET Framework project - Causes `System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.` at runtime.
- Referencing Veldrid.SDL2 from .NET Framework project then adding System.Numerics.Vectors - Causes weird `Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute` and `Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute` build errors.
- Copying Veldrid.SDL2 source to .NET Framework project then referencing it - (Assembly name is `Veldrid.SDL2Framework2`) Throws `Veldrid.SDL2Framework2.Version.cs(12, 12): [CS0579] Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute` and `Veldrid.SDL2Framework2.Version.cs(11, 12): [CS0579] Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute` at build.

If you have any idea how to get it working I'd greatly appreciate it 😄 

(everything tested with latest source from master)

**Comment by mellinoe** [comment]
What version of .NET Framework are you targeting? Veldrid targets `netstandard2.0`, so you will need to target .NET 4.6.1 unless you want to retarget Veldrid itself. If you're targeting .NET 4.6.1, then I'm pretty sure everything should work automatically, including adding the appropriate redirects for System.Numerics.Vectors.

The "duplicate assembly attribute" errors don't have much to do with Veldrid, as far as I can tell. It's likely that you have a file with an `AssemblyFileVersionAttribute` in it, and then the .NET SDK is adding a "default" one for you automatically. You can prevent the SDK from adding one by setting `GenerateAssemblyInfo=false` in your project. Or you could just delete it from your .cs file.

**Comment by ZingBallyhoo** [comment]
Thanks!

It seems to work best for my use case if I just switch Veldrid.SDL2 to build for net471, I don't know why I didn't think of that in the first place.
