### ISSUE TITLE
[Regression] Breaking change

### ISSUE THREAD

**Issue by thargy** [mellinoe/veldrid#76]
Upgrading Veldrid NuGet from 4.2.1-gf8034b4392 -> 4.3.0-g12cea4fac5 breaks something.

My project has a compute shader that creates instance data for a vertex shader that renders quads, morphing based on computed instance data.  It works perfectly on the last version, blank screen on update, with no errors or warnings thrown.

**Comment by mellinoe** [comment]
@thargy Does this happen on the D3D11 backend? I recently merged [this](https://github.com/mellinoe/veldrid/commit/ae23cdc81cf923d4acc405eb5957772c0bc09dd6) in, which directly changed something related to compute resource binding.

Do you have a repo somewhere I could try out?

**Comment by geoeo** [comment]
Layout on how uniforms are bound to shaders has changed. You might have to provide updated indices. For me, I just had to decrease the index of my uniforms by 1

**Comment by mellinoe** [comment]
@geoeo Nothing like that should have changed, especially in the last few commits. The only change like that was the addition of `ResourceBindingModel.Improved`, which is opt-in. And that was before the commits in question.

**Comment by mellinoe** [comment]
@thargy I see the issue. The line I removed was indeed important -- or at least, it was there for a reason. I'll update the thread when I have a fix.

**Comment by thargy** [comment]
> I recently merged this in, which directly changed something related to compute resource binding.

That was my guess, is there an easy way for me to manually add this step to see if it 'fixes' the problem?

> Do you have a repo somewhere I could try out?

It's currently a private TeamSystem repo as I'm still learning! If you have a TeamSystem login I can add you?

**Comment by mellinoe** [comment]
I have a fix, but I want to make sure this is covered by a test case before I merge back to master. I'm working on that now.

**Comment by thargy** [comment]
I’ll let you know if it resolves the issue once it’s pushed.  If not, I can try and produce a repo.

Thanks!

**Comment by thargy** [comment]
Tested with `4.3.0-g915270966e` (which is latest timestamp NuGet) and works.
