### ISSUE TITLE
[Possible Bug / User Error] GLSL version #130 UniformBuffer in Slot 0 will not update

### ISSUE THREAD

**Issue by AlzPatz** [mellinoe/veldrid#88]
Hi,

Apologies if this is the wrong place or I am overlooking something simple.

I am having trouble updating a simple uniform buffer under GLSL version 130.
I have distilled an example at the following link:

The idea here is that should the uniform buffer update the rectangle will be white. As the uniform floats are 0 it suggests it is not updating.

Please note I ran into this issue in a more complex program, updating a matrix, but thought it would be simpler to distill into this example.

I understand with a higher version of GLSL i could experiment with uniform blocks and layout indices but I am restricting on this hardware.

Thanks for any thoughts... delete if not appropriate.

(please note only works with OpenGL backend)

https://bitbucket.org/AlzPatz/potentialveldridglsl130issue

Alex

**Comment by mellinoe** [comment]
Unfortunately, this is just something that isn't supported. Veldrid basically requires OpenGL 3.1 at a minimum, but this isn't strictly enforced (as in, you won't get an error if your system doesn't meet that). I haven't looked at the full feature set, but there are likely several other things that Veldrid relies on that also aren't available in such old versions of OpenGL.

If you don't mind me asking, what hardware are you working with that has such an old OpenGL version?

**Comment by AlzPatz** [comment]
Hi, thanks for the response.

I should have been more precise. The hardware is not old.

I am using a Dell XPS 13, 8th Gen i5 8250u. It uses ondie Intel iGPU. I am running Arch linux, using the mesa graphics driver.

glxinfo reports my core OpenGL as 4.5, standard version 3.0.

It is a known issue across distros, that unless you request a forward compatible context, you do not get more than 3.0 with this driver. 

"You only get support for GLSL 3.30 if you work with a forward compatible (core) OpenGL context. You have to request that explicitly"

https://bbs.archlinux.org/viewtopic.php?id=201864

I know arch isn't a formally supported distro for .net core, but I suspect you have the same occurnace on ubuntu with this driver / igpu (I am going to test).

https://askubuntu.com/questions/946211/unable-to-use-glsl-versions-above-130

I believe what is needed, is somewhere in Veldrid.Startup whereby you can (perhaps optionally), ask it to request SDL_GLContextFlag with ForwardCompatible. 

I'm not sure if you want to force ForwardCompatible for everyone, but perhaps if there is a minimum version you get back below 3.1, you can try with this flag?

I was going to try and make the suggested changes myself, but arch did bite me, as NerdBank.GitVersioning won't build on arch currently due to LibGit2Sharp not working properly :(

So onto the [temp] solution...

I want to use ForwardCompatible, so would appreciate this inclusion in the future, but for now I have simply switched to GLSL ES 3.2. Not sure if this will cause me problems later, but you can see from the new commit it now updates the uniform OK :)

-

I would be interested to know if you would be willing to include any changes to set the Forward Compatible Flag?

**Comment by AlzPatz** [comment]
np, i'll give it a shot

**Comment by AlzPatz** [comment]
It's a libcurl issue for arch, "The issue seems to be with a prebuild library (probably libgit2) which was linked against libcurl -> libcurl.so.4 which also contained backwards compatible libcurl.so.3 code, while arch-linux libcurl.so.4 does not." - I tried a few other options, libcurl-compat but no luck. anyway no bother :)

**Comment by mellinoe** [comment]
@AlzPatz Did the change over in #89 fix this?

**Comment by AlzPatz** [comment]
Yep - confirmed the fix works for me on arch Linux using Mesa intel drivers

**Comment by mellinoe** [comment]
Sounds good. I'm planning on putting out a stable 4.3.0 version pretty soon, once a few more miscellaneous fixes get in. I'll close this one out now.
