### ISSUE TITLE
[Question] Getting a correct rendering environment 

### ISSUE THREAD

**Issue by dmitsuki** [mellinoe/veldrid#92]
I'm currently trying to get basic rendering down in Veldrid, and am trying to render a textured quad. 

I have the following code. The issue is while no error is presented anywhere, nothing is rendering. Have I made some mistake somewhere in setting up the Veldrid state to begin rendering? 

`public class App
    {
        Sdl2Window AppWindow;
        GraphicsDevice Device;
        ResourceFactory Factory;

        CommandList CmdList;
        DeviceBuffer CanvasVertextBuffer;
        DeviceBuffer CanvasIndexBuffer;
        DeviceBuffer ModelBuffer; 
        DeviceBuffer ProjectionBuffer;
        ResourceSet ModelProjectionSet;
        ResourceLayout ModelProjectionLayout; 
        Texture CanvasTexture;
        TextureView CanvasTextureView;
        ResourceSet CanvasTextureSet; 
        ResourceLayout CanvasTextureLayout; 
        Pipeline CanvasPipeline; 
        ImGuiRenderer GuiRenderer;

        string ImageUrl = @"C:\LocalProjects\GarPixel\GarPixel\asset\elf.png";

        //Quad points 
        readonly float[] QuadVerts = new float[] {
             // Pos      // Tex
            0.0f, 1.0f, 0.0f, 1.0f,
            1.0f, 0.0f, 1.0f, 0.0f,
            0.0f, 0.0f, 0.0f, 0.0f,

            0.0f, 1.0f, 0.0f, 1.0f,
            1.0f, 1.0f, 1.0f, 1.0f,
            1.0f, 0.0f, 1.0f, 0.0f
         };

        ushort[] QuadIndices = { 0, 1, 2, 3 }; 

        public App()
        {
            WindowCreateInfo windowCI = new WindowCreateInfo()
            {
                X = 100,
                Y = 100,
                WindowWidth = 1280,
                WindowHeight = 720,
                WindowTitle = "Gar Pixel"
            };
            AppWindow = VeldridStartup.CreateWindow(ref windowCI);
            Device = VeldridStartup.CreateGraphicsDevice(AppWindow, GraphicsBackend.OpenGL);
            CreateResources(); 
        }

        const string VertexShaderSource = @"
            #version 330
            layout(location = 0) in vec4 posuv;

            out vec2 TexCoords;

            uniform mat4 model;
            uniform mat4 projection; 

            void main(void)
            {
                TexCoords = posuv.zw; 
                gl_Position = projection * model * vec4(posuv.xy, 0.0, 1.0);
            }
        ";

        const string FragmentShaderSource = @"
            #version 330
            in vec2 TexCoords;
            out vec4 color; 

            uniform sampler2D image; 

            void main(void)
            {
                color = texture(image, TexCoords);
            }
        ";

        private void CreateResources()
        {
            Factory = Device.ResourceFactory;

            CmdList = Factory.CreateCommandList();
            GuiRenderer = new ImGuiRenderer(
                Device,
                Device.MainSwapchain.Framebuffer.OutputDescription,
                AppWindow.Width,
                AppWindow.Height
                );

            AppWindow.Resized += () =>
            {
                GuiRenderer.WindowResized(AppWindow.Width, AppWindow.Height);
                Device.MainSwapchain.Resize((uint)AppWindow.Width, (uint)AppWindow.Height);

            };
            
            CanvasVertextBuffer = Factory.CreateBuffer(new BufferDescription((uint)(QuadVerts.Length * sizeof(float)), 
                BufferUsage.VertexBuffer));
            CanvasIndexBuffer = Factory.CreateBuffer(new BufferDescription(4 * sizeof(ushort), BufferUsage.IndexBuffer));
            Device.UpdateBuffer(CanvasVertextBuffer, 0, QuadVerts);
            Device.UpdateBuffer(CanvasIndexBuffer, 0, QuadIndices);

            ModelBuffer = Factory.CreateBuffer(new BufferDescription(
                64, 
                BufferUsage.UniformBuffer
                ));
            ProjectionBuffer = Factory.CreateBuffer(new BufferDescription(
                64,
                BufferUsage.UniformBuffer
                ));

            ModelProjectionLayout = Factory.CreateResourceLayout
                (
                    new ResourceLayoutDescription
                    (
                        new ResourceLayoutElementDescription
                        (
                            "model",
                            ResourceKind.UniformBuffer,
                            ShaderStages.Vertex
                        ),
                        new ResourceLayoutElementDescription
                        (
                            "projection",
                            ResourceKind.UniformBuffer,
                            ShaderStages.Vertex
                        )
                    )
                );

            ModelProjectionSet = Factory.CreateResourceSet(
                new ResourceSetDescription(ModelProjectionLayout, ModelBuffer, ProjectionBuffer)); 

            VertexLayoutDescription vertexLayout = new VertexLayoutDescription(
                new VertexElementDescription[]
                {
                    new VertexElementDescription(
                    "posuv",
                    VertexElementSemantic.Position,
                    VertexElementFormat.Float4
                    )
                }
            );
            Shader vertexShader = Factory.CreateShader(new ShaderDescription(
                ShaderStages.Vertex,
                Encoding.ASCII.GetBytes(VertexShaderSource),
                "VS"
                ));
            Shader fragmentShader = Factory.CreateShader(new ShaderDescription(
                ShaderStages.Fragment,
                Encoding.ASCII.GetBytes(FragmentShaderSource),
                "FS"
                ));

            CanvasTextureLayout = Factory.CreateResourceLayout(
                new ResourceLayoutDescription(
                    new ResourceLayoutElementDescription("image", ResourceKind.TextureReadOnly, ShaderStages.Fragment)
                    )
            );

            CanvasTexture = new ImageSharpTexture(ImageUrl, false).CreateDeviceTexture(Device, Factory);
            CanvasTextureView = Factory.CreateTextureView(CanvasTexture);
            CanvasTextureSet = Factory.CreateResourceSet
                (
                    new ResourceSetDescription(
                        CanvasTextureLayout,
                        CanvasTextureView)
                );

            GraphicsPipelineDescription pipelineDescription = new GraphicsPipelineDescription
                (
                    BlendStateDescription.SingleAlphaBlend,
                    DepthStencilStateDescription.Disabled,
                    RasterizerStateDescription.CullNone,
                    PrimitiveTopology.TriangleList,
                    new ShaderSetDescription(
                        new VertexLayoutDescription[]
                        {
                            new VertexLayoutDescription(
                                16,
                                new VertexElementDescription
                                (
                                    "posuv", 
                                    VertexElementSemantic.Position, VertexElementFormat.Float4
                                )
                            )
                        },
                        new Shader[] { vertexShader, fragmentShader }
                        ),
                    new[] { ModelProjectionLayout, CanvasTextureLayout },
                    Device.MainSwapchain.Framebuffer.OutputDescription
                );
            pipelineDescription.BlendState = BlendStateDescription.SingleOverrideBlend;

            CanvasPipeline = Factory.CreateGraphicsPipeline(pipelineDescription); 
        }

        public void Run()
        {
            while(AppWindow.Exists)
            {
                InputSnapshot snapshot = AppWindow.PumpEvents();

                GuiRenderer.Update(1f / 60f, snapshot);

                bool showWindow = true;
                ImGuiNative.igShowDemoWindow(ref showWindow); 
                if(ImGui.BeginWindow("Test"))
                {
                    ImGui.Text("Hello");
                    if (ImGui.Button("Quit"))
                    {
                    }
                    ImGui.EndWindow(); 
                }

                Device.UpdateBuffer(ProjectionBuffer, 0,
                    Matrix4x4.CreateOrthographic(AppWindow.Width, AppWindow.Height,
                    -1, 1));

                Matrix4x4 model = Matrix4x4.Identity;
                model *= Matrix4x4.CreateTranslation(500, 500, 0); 
                model *= Matrix4x4.CreateScale(5000);

                Device.UpdateBuffer(ModelBuffer, 0, model); 

                CmdList.Begin();
                CmdList.SetFramebuffer(Device.MainSwapchain.Framebuffer);
                CmdList.ClearColorTarget(0, new RgbaFloat(.3f, .3f, .3f, 1f));
                GuiRenderer.Render(Device, CmdList);

                CmdList.SetPipeline(CanvasPipeline);
                CmdList.SetVertexBuffer(0,CanvasVertextBuffer);
                CmdList.SetIndexBuffer(CanvasIndexBuffer, IndexFormat.UInt16); 
                CmdList.SetGraphicsResourceSet(0, ModelProjectionSet);
                CmdList.SetGraphicsResourceSet(1, CanvasTextureSet);
                CmdList.DrawIndexed(4, 1, 0, 0, 0);  
                
                CmdList.End();
                Device.SubmitCommands(CmdList);
                Device.SwapBuffers(Device.MainSwapchain); 
            }
        }
    }`

**Comment by mellinoe** [comment]
@dmitsuki I tried out your code and I've noticed a few problems:

* Your indices aren't correct. You are using `0, 1, 2, 3`, which doesn't work for `PrimitiveTopology.TriangleList`, which is what you're using in your Pipeline description. TriangleList always needs an index count that is a multiple of 3. Based on how you defined the vertex data, you can change it to `0, 1, 2, 3, 4, 5`.
* After the above, you should draw with six indices, instead of 4: `CmdList.DrawIndexed(6);`
* Your texture coordinates are flipped. The vertices at the top should have the lowest Y UV index, instead of the highest. This will be obvious once the quad gets rendered, though -- it looks upside down.
* Your model matrix is putting the quad way offscreen, so it gets clipped. If I change it to this, it works:
```C#
Matrix4x4 model = Matrix4x4.Identity;
model *= Matrix4x4.CreateScale(200);
model *= Matrix4x4.CreateTranslation(100, 100, 0);
```
* Not a big deal, but you're not using the `vertexLayout` array you define above the Pipeline description. You redefine the array inside of the ShaderSetDescription.

**Comment by dmitsuki** [comment]
Even after implementing those changes, nothing appears on my screen. A gist with the code for brevity of post
https://gist.github.com/dmitsuki/53065e7d840bf8e10464fe33686c662c

(vertex data is same though, don't care if uv's are upside down yet lol)

**Comment by mellinoe** [comment]
Let me check again -- perhaps there was something I fixed and forgot to mention.

**Comment by mellinoe** [comment]
Sorry, there actually was another problem that I fixed and didn't mention.

Your shader is using "naked" uniform variables, which aren't supported in Veldrid. In GLSL, you need to put all your uniform variables inside of a "uniform block". So, your vertex shader would become:

```
layout(std140) uniform model
{
    mat4 _modelMat;
};
layout(std140) uniform projection
{
    mat4 _projectionMat;
};
```

The name of the resource (the one that you put into ResourceLayoutElementDescription) is the "block" name. The names above are "model" and "projection" as your code already expect.

Then, you just change the last line to refer to the variables inside the block:

```
gl_Position = _projectionMat * _modelMat * vec4(posuv.xy, 0.0, 1.0);
```

**Comment by dmitsuki** [comment]
Thanks, this solved it. I didn't know this about veldrid and Shaders.
