### ISSUE TITLE
Prevent blocking during window resize?

### ISSUE THREAD

**Issue by joethephish** [mellinoe/veldrid#93]
When resizing a window (macOS Sierra, OpenGL backend),  it seems that the call to `window.PumpEvents()` doesn't return until you release the mouse button, meaning that the window goes black and doesn't start redrawing again until the mouse is released.

Is this a shortcoming of SDL2 or is there something that can be done to dynamically redraw every frame at the intermediate size? It would be great if it was possible to have a fluid resizing animation as you drag!

**Comment by mellinoe** [comment]
As far as I know, this is a limitation of SDL2. I haven't tried this on macOS, but I tried for a long time to get this working on Windows, and was not able to. I tried various obscure workarounds that folks had suggested around the web, but nothing worked.

**Comment by joethephish** [comment]
Oh dear, how frustrating. Thanks anyway!
