### ISSUE TITLE
[Question] Make a "screenshot" of window content(using SwapchainFramebuffer?)

### ISSUE THREAD

**Issue by distorn** [mellinoe/veldrid#99]
I have some graphics on the screen successfully rendered with veldrid in Sdl2Window. My goal is to make a "screenshot" of these graphics and then save it to file using ImageSharp.

My first idea was to use graphicsDevice.SwapchainFramebuffer somehow and get bytes from this buffer. As I understand SwapchainFramebuffer is a final destination for the data rendered on the screen, but maybe I'm wrong as I don't have much experience in low-level graphics programming concepts.

Didn't find a way to do that using commandList.CopyBuffer() as this function accepts only instances of DeviceBuffer.

Then I tried to copy data from SwapchainFramebuffer ColorTarget's Texture, but for some reason I got only "zero valued pixels" here despite the fact that I have graphics already rendered on the screen.

Here is my code that I call after rendering completed:

```C#
var frameTexture = graphicsDevice.SwapchainFramebuffer.ColorTargets[0].Target;

Texture stage = graphicsDevice.ResourceFactory.CreateTexture(TextureDescription.Texture2D(
	frameTexture.Width,
	frameTexture.Height,
	1,
	1,
	PixelFormat.R8_G8_B8_A8_UNorm,
	TextureUsage.Staging));

CommandList cl = graphicsDevice.ResourceFactory.CreateCommandList();
cl.Begin();
commandList.SetFramebuffer(graphicsDevice.MainSwapchain.Framebuffer);
commandList.CopyTexture(
	frameTexture, 0, 0, 0, 0, 0,
	stage, 0, 0, 0, 0, 0,
	stage.Width, stage.Height, 1, 1);
cl.End();

graphicsDevice.SubmitCommands(cl);
graphicsDevice.WaitForIdle();

MappedResourceView<Rgba32> map = graphicsDevice.Map<Rgba32>(stage, MapMode.Read);

Rgba32[] pixelData = new Rgba32[stage.Width * stage.Height];
for (int y = 0; y < stage.Height; y++)
{
	for (int x = 0; x < stage.Width; x++)
	{
		int index = (int)(y * stage.Width + x);
		pixelData[index] = map[x, y]; // <-- I have only zeroes here
	}
}

graphicsDevice.Unmap(stage);
```

So what I do wrong and what would be a proper way to capture current pixels rendered on the screen?
Thanks.

**Comment by mellinoe** [comment]
Swapchain Framebuffers are a bit special in that not all backends actually give you access to the underlying Texture objects. Veldrid lets you look at them and inspect their dimensions, format, etc. but it's not always possible to copy from them, resolve them, etc. To take a screenshot, the best option is to render your scene to a separate Framebuffer which you created yourself. You can then do what you have written above, but copying from that separate Framebuffer.

**Comment by distorn** [comment]
@mellinoe Thanks for clarifications. 

After several evenings of puzzling out how to create custom framebuffer and other stuff, finally I've achieved my goal. Almost.. ) I noticed a few strange(at least for me) things:

First, the texture object of default color target created by veldrid has Texture1D type, although it's DeviceTexture is Texture2D. Not sure if it's not a bug and how to recreate this object with different texture types, so to make my solution work I had to override my texture type to Texture2D, and it works OK.

![veldrid-debug](https://user-images.githubusercontent.com/11734800/42725142-7d7b8d3a-8787-11e8-82e5-d183dbfad079.png)

Another "issue" is that for some reason I have strange(for me, again) pixel format for default color target: B8_G8_R8_A8_UNorm. Why it's not R8_G8_B8_A8_UNorm, is it something D3D11 specific? Can I override this format on GraphicsDevice creation or something like that?

If it would be helpful for somebody, here is my updated code working with custom framebuffer:

```C#
private void SaveScreenToFile()
{
	var rf = new DisposeCollectorResourceFactory(graphicsDevice.ResourceFactory);

	var colorTargetTexture = graphicsDevice.SwapchainFramebuffer.ColorTargets[0].Target;
	var pixelFormat = colorTargetTexture.Format; // <- PixelFormat.B8_G8_R8_A8_UNorm, is it OK?

	var textureDescription = colorTargetTexture.GetDescription();
	textureDescription.Usage = TextureUsage.RenderTarget;
	textureDescription.Type = TextureType.Texture2D;
	textureDescription.Format = pixelFormat;

	var textureForRender = rf.CreateTexture(textureDescription);

	var depthTexture = graphicsDevice.SwapchainFramebuffer.DepthTarget.Value.Target;
	var depthTextureForRender = rf.CreateTexture(depthTexture.GetDescription());

	var framebufferDescription = new FramebufferDescription(depthTextureForRender, textureForRender);
	var framebuffer = rf.CreateFramebuffer(framebufferDescription);

	Texture stage = rf.CreateTexture(TextureDescription.Texture2D(
		textureForRender.Width,
		textureForRender.Height,
		1,
		1,
		pixelFormat,
		TextureUsage.Staging));

	commandList.Begin();
	commandList.SetFramebuffer(framebuffer);

	RedrawContent();

	commandList.CopyTexture(
		textureForRender, 0, 0, 0, 0, 0,
		stage, 0, 0, 0, 0, 0,
		stage.Width, stage.Height, 1, 1);
	commandList.End();

	graphicsDevice.SubmitCommands(commandList);

	MappedResourceView<Rgba32> map = graphicsDevice.Map<Rgba32>(stage, MapMode.Read);

	Rgba32[] pixelData = new Rgba32[stage.Width * stage.Height];
	for (int y = 0; y < stage.Height; y++)
	{
		for (int x = 0; x < stage.Width; x++)
		{
			int index = (int)(y * stage.Width + x);
			pixelData[index] = map[x, y]; // <- I have to convert BRGA to RGBA pixels here
		}
	}

	graphicsDevice.Unmap(stage);
	rf.DisposeCollector.DisposeAll();
...
}
```
And here is additional extension method that I wrote. Probably it would be great to have such helper methods(in Veldrid.Utilities?) for all other DeviceResource types that are created using their Description types.

```C#
public static TextureDescription GetDescription(this Texture texture)
{
	return new TextureDescription(
		texture.Width, texture.Height,
		texture.Depth, texture.MipLevels, texture.ArrayLayers,
		texture.Format, texture.Usage, texture.Type, texture.SampleCount
	);
}
```

**Comment by distorn** [comment]
@mellinoe Thanks for your answers. Now, all regarding this topic is clear for me.

> Potentially, these helpers could be added directly to the types themselves. My only hesitation is some functionality will be "duplicated", e.g. Texture.Width and Texture.Description.Width are the same thing, and that's slightly confusing.

Yeah, this idea also came to my mind. Probably this functionality won't be so frequently-used, so placing it in pluggable extension methods from a separate namespace is OK. On the other hand, if it would be built-in in types itself, it would be more likely for programmers to find that these methods exist. So, it's up to you, and I will be happy with any approach here.

> By the way, if there's anything missing in the documentation for these topics, let me know and I will try to improve them where possible.

Veldrid documentation is relatively good for a non-commercial project on this stage of development. And of course as we are dealing with open-source there is always an ability to download sources and look what happened under the hood and how things are interconnected. All methods that I was interested in had at least a few lines of doc comments. I think that probably the main problem is not a Veldrid documentation itself but lack of my knowledge in some common low-level graphics programming concepts.)
